import fs from "node:fs/promises";
import path from "node:path";
import { PassThrough } from "node:stream";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { describe, expect, it } from "vitest";
import { createDefaultConfig, writeConfig } from "../../src/config.js";
import { runSliceCommitCommand } from "../../src/internal/slice-commit.js";
import type { CclawConfig, LockfileTwinPolicy } from "../../src/types.js";
import { createTempProject } from "../helpers/index.js";

const execFileAsync = promisify(execFile);

async function git(cwd: string, args: string[]): Promise<string> {
  const { stdout } = await execFileAsync("git", args, { cwd });
  return stdout.trim();
}

interface IoCapture {
  stdout: PassThrough;
  stderr: PassThrough;
  readStdout: () => string;
  readStderr: () => string;
}

function createIoCapture(): IoCapture {
  const stdout = new PassThrough();
  const stderr = new PassThrough();
  let out = "";
  let err = "";
  stdout.on("data", (chunk) => {
    out += String(chunk ?? "");
  });
  stderr.on("data", (chunk) => {
    err += String(chunk ?? "");
  });
  return {
    stdout,
    stderr,
    readStdout: () => out,
    readStderr: () => err
  };
}

interface ProjectSetupOptions {
  manifest: { path: string; before: string; after: string };
  lockfile: { path: string; before: string; after: string };
  policy: LockfileTwinPolicy | undefined;
  isolation?: "in-place" | "worktree";
}

async function setupSliceProject(label: string, opts: ProjectSetupOptions): Promise<string> {
  const root = await createTempProject(label);
  const config: CclawConfig = createDefaultConfig(["claude"]);
  if (config.tdd) {
    config.tdd.isolationMode = opts.isolation ?? "in-place";
    if (opts.policy) config.tdd.lockfileTwinPolicy = opts.policy;
  }
  await writeConfig(root, config);
  await git(root, ["init"]);
  await git(root, ["config", "user.email", "tests@example.com"]);
  await git(root, ["config", "user.name", "Test Runner"]);
  // Seed both manifest and lockfile in HEAD so drift starts clean.
  await fs.mkdir(path.join(root, path.dirname(opts.manifest.path) || "."), { recursive: true });
  await fs.writeFile(path.join(root, opts.manifest.path), opts.manifest.before, "utf8");
  await fs.mkdir(path.join(root, path.dirname(opts.lockfile.path) || "."), { recursive: true });
  await fs.writeFile(path.join(root, opts.lockfile.path), opts.lockfile.before, "utf8");
  await git(root, ["add", "."]);
  await git(root, ["commit", "-m", "init"]);
  // Now produce drift.
  await fs.writeFile(path.join(root, opts.manifest.path), opts.manifest.after, "utf8");
  await fs.writeFile(path.join(root, opts.lockfile.path), opts.lockfile.after, "utf8");
  return root;
}

describe("slice-commit lockfile twin policy (7.6.0 — Defect 3)", () => {
  describe("rust (Cargo.toml + Cargo.lock)", () => {
    it("auto-include (default): folds Cargo.lock into the slice commit", async () => {
      const root = await setupSliceProject("twin-rust-auto-include", {
        manifest: {
          path: "Cargo.toml",
          before: "[package]\nname = \"x\"\n",
          after: "[package]\nname = \"x\"\n[dev-dependencies]\nproptest = \"1\"\n"
        },
        lockfile: {
          path: "Cargo.lock",
          before: "# initial\n",
          after: "# regenerated by cargo build\n"
        },
        policy: "auto-include"
      });
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-1",
          "--span-id=span-S-1",
          "--task-id=T-1",
          "--title=close S-1",
          "--claimed-paths=Cargo.toml"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode, io.readStderr()).toBe(0);
      const payload = JSON.parse(io.readStdout().trim()) as {
        ok?: boolean;
        lockfileTwinsIncluded?: string[];
        stackAdapterId?: string;
      };
      expect(payload.ok).toBe(true);
      expect(payload.stackAdapterId).toBe("rust");
      expect(payload.lockfileTwinsIncluded).toEqual(["Cargo.lock"]);
      const showOut = await git(root, ["show", "--name-only", "--pretty=format:", "HEAD"]);
      const files = showOut.split(/\r?\n/gu).map((line) => line.trim()).filter(Boolean);
      expect(files).toContain("Cargo.toml");
      expect(files).toContain("Cargo.lock");
    });

    it("auto-revert: restores Cargo.lock and commits only the manifest", async () => {
      const root = await setupSliceProject("twin-rust-auto-revert", {
        manifest: {
          path: "Cargo.toml",
          before: "[package]\nname = \"x\"\n",
          after: "[package]\nname = \"x\"\n[dev-dependencies]\nproptest = \"1\"\n"
        },
        lockfile: {
          path: "Cargo.lock",
          before: "# initial\n",
          after: "# regenerated by cargo build\n"
        },
        policy: "auto-revert"
      });
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-1",
          "--span-id=span-S-1",
          "--task-id=T-1",
          "--claimed-paths=Cargo.toml"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode, io.readStderr()).toBe(0);
      const payload = JSON.parse(io.readStdout().trim()) as {
        ok?: boolean;
        lockfileTwinsReverted?: string[];
      };
      expect(payload.ok).toBe(true);
      expect(payload.lockfileTwinsReverted).toEqual(["Cargo.lock"]);
      const showOut = await git(root, ["show", "--name-only", "--pretty=format:", "HEAD"]);
      const files = showOut.split(/\r?\n/gu).map((line) => line.trim()).filter(Boolean);
      expect(files).toContain("Cargo.toml");
      expect(files).not.toContain("Cargo.lock");
    });

    it("strict-fence: rejects Cargo.lock drift as slice_commit_path_drift", async () => {
      const root = await setupSliceProject("twin-rust-strict-fence", {
        manifest: {
          path: "Cargo.toml",
          before: "[package]\nname = \"x\"\n",
          after: "[package]\nname = \"x\"\n[dev-dependencies]\nproptest = \"1\"\n"
        },
        lockfile: {
          path: "Cargo.lock",
          before: "# initial\n",
          after: "# regenerated by cargo build\n"
        },
        policy: "strict-fence"
      });
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-1",
          "--span-id=span-S-1",
          "--task-id=T-1",
          "--claimed-paths=Cargo.toml"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode).toBe(2);
      const payload = JSON.parse(io.readStderr().trim()) as {
        errorCode?: string;
        details?: { driftPaths?: string[]; lockfileTwinPolicy?: string };
      };
      expect(payload.errorCode).toBe("slice_commit_path_drift");
      expect(payload.details?.driftPaths).toContain("Cargo.lock");
      expect(payload.details?.lockfileTwinPolicy).toBe("strict-fence");
    });
  });

  describe("node (package.json + package-lock.json)", () => {
    it("auto-include: folds package-lock.json into the slice commit", async () => {
      const root = await setupSliceProject("twin-node-auto-include", {
        manifest: {
          path: "package.json",
          before: "{\n  \"name\": \"x\"\n}\n",
          after: "{\n  \"name\": \"x\",\n  \"devDependencies\": { \"vitest\": \"1.0.0\" }\n}\n"
        },
        lockfile: {
          path: "package-lock.json",
          before: "{\n  \"name\": \"x\",\n  \"lockfileVersion\": 3\n}\n",
          after: "{\n  \"name\": \"x\",\n  \"lockfileVersion\": 3,\n  \"packages\": {} \n}\n"
        },
        policy: "auto-include"
      });
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-2",
          "--span-id=span-S-2",
          "--task-id=T-2",
          "--claimed-paths=package.json"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode, io.readStderr()).toBe(0);
      const payload = JSON.parse(io.readStdout().trim()) as {
        ok?: boolean;
        lockfileTwinsIncluded?: string[];
        stackAdapterId?: string;
      };
      expect(payload.ok).toBe(true);
      expect(payload.stackAdapterId).toBe("node");
      expect(payload.lockfileTwinsIncluded).toEqual(["package-lock.json"]);
    });
  });

  describe("python (pyproject.toml + poetry.lock)", () => {
    it("auto-include: folds poetry.lock into the slice commit", async () => {
      const root = await setupSliceProject("twin-python-auto-include", {
        manifest: {
          path: "pyproject.toml",
          before: "[tool.poetry]\nname = \"x\"\n",
          after: "[tool.poetry]\nname = \"x\"\n[tool.poetry.dev-dependencies]\npytest = \"^7\"\n"
        },
        lockfile: {
          path: "poetry.lock",
          before: "# initial\n",
          after: "# regenerated by poetry install\n"
        },
        policy: "auto-include"
      });
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-3",
          "--span-id=span-S-3",
          "--task-id=T-3",
          "--claimed-paths=pyproject.toml"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode, io.readStderr()).toBe(0);
      const payload = JSON.parse(io.readStdout().trim()) as {
        ok?: boolean;
        lockfileTwinsIncluded?: string[];
        stackAdapterId?: string;
      };
      expect(payload.ok).toBe(true);
      expect(payload.stackAdapterId).toBe("python");
      expect(payload.lockfileTwinsIncluded).toEqual(["poetry.lock"]);
    });
  });

  describe("non-twin drift", () => {
    it("auto-include policy still rejects non-twin drift", async () => {
      const root = await setupSliceProject("twin-non-twin-drift", {
        manifest: {
          path: "Cargo.toml",
          before: "[package]\nname = \"x\"\n",
          after: "[package]\nname = \"x\"\n[dev-dependencies]\nproptest = \"1\"\n"
        },
        lockfile: {
          path: "Cargo.lock",
          before: "# initial\n",
          after: "# regenerated\n"
        },
        policy: "auto-include"
      });
      // Add an unclaimed-source-file drift on top of the lockfile drift.
      await fs.mkdir(path.join(root, "src"), { recursive: true });
      await fs.writeFile(path.join(root, "src/unrelated.rs"), "fn unrelated() {}\n", "utf8");
      const io = createIoCapture();
      const exitCode = await runSliceCommitCommand(
        root,
        [
          "--json",
          "--slice=S-1",
          "--span-id=span-S-1",
          "--task-id=T-1",
          "--claimed-paths=Cargo.toml"
        ],
        { stdout: io.stdout, stderr: io.stderr }
      );
      expect(exitCode).toBe(2);
      const payload = JSON.parse(io.readStderr().trim()) as {
        errorCode?: string;
        details?: { driftPaths?: string[] };
      };
      expect(payload.errorCode).toBe("slice_commit_path_drift");
      expect(payload.details?.driftPaths ?? []).toContain("src/unrelated.rs");
      expect(payload.details?.driftPaths ?? []).not.toContain("Cargo.lock");
    });
  });
});
