/**
 * Hook generators for all supported harnesses.
 *
 * SessionStart: injects using-cclaw + flow state + knowledge + checkpoint/activity summary.
 * Stop: writes checkpoint.json and reminds about flow consistency.
 * Harness hook JSON wiring is generated in observe.ts.
 */

import { RUNTIME_ROOT } from "../constants.js";
import { META_SKILL_NAME } from "./meta-skill.js";

export interface HookRuntimeOptions {}

const ESCAPE_FN = `escape_json() {
  local str="$1"
  str=\${str//\\\\/\\\\\\\\}
  str=\${str//\\"/\\\\\\"}
  str=\${str//$'\\t'/\\\\t}
  str=\${str//$'\\n'/\\\\n}
  printf '%s' "$str"
}`;

const DETECT_ROOT = `HARNESS="codex"
if [ -n "\${CLAUDE_PROJECT_DIR:-}" ]; then
  HARNESS="claude"
elif [ -n "\${CURSOR_PROJECT_DIR:-}" ] || [ -n "\${CURSOR_PROJECT_ROOT:-}" ]; then
  HARNESS="cursor"
elif [ -n "\${OPENCODE_PROJECT_DIR:-}" ] || [ -n "\${OPENCODE_PROJECT_ROOT:-}" ]; then
  HARNESS="opencode"
fi

ROOT=""
for candidate in "\${CCLAW_PROJECT_ROOT:-}" "\${CLAUDE_PROJECT_DIR:-}" "\${CURSOR_PROJECT_DIR:-}" "\${CURSOR_PROJECT_ROOT:-}" "\${OPENCODE_PROJECT_DIR:-}" "\${OPENCODE_PROJECT_ROOT:-}" "\${PWD:-}"; do
  if [ -n "$candidate" ] && [ -d "$candidate/${RUNTIME_ROOT}" ]; then
    ROOT="$candidate"
    break
  fi
done
if [ -z "$ROOT" ]; then
  ROOT="\${CCLAW_PROJECT_ROOT:-\${CLAUDE_PROJECT_DIR:-\${CURSOR_PROJECT_DIR:-\${CURSOR_PROJECT_ROOT:-\${OPENCODE_PROJECT_DIR:-\${OPENCODE_PROJECT_ROOT:-\${PWD}}}}}}}"
fi`;

/** Shared bash preamble for generated hook scripts. */
export const RUNTIME_SHELL_DETECT_ROOT = DETECT_ROOT;

export function sessionStartScript(_options: HookRuntimeOptions = {}): string {
  return `#!/usr/bin/env bash
# cclaw session-start hook — generated by cclaw sync
# Injects using-cclaw + flow status + active artifacts + compact knowledge digest + checkpoint/activity summary.
set -euo pipefail

${DETECT_ROOT}

STATE_FILE="$ROOT/${RUNTIME_ROOT}/state/flow-state.json"
ACTIVE_FEATURE_FILE="$ROOT/${RUNTIME_ROOT}/state/active-feature.json"
CHECKPOINT_FILE="$ROOT/${RUNTIME_ROOT}/state/checkpoint.json"
ACTIVITY_FILE="$ROOT/${RUNTIME_ROOT}/state/stage-activity.jsonl"
SUGGESTION_MEMORY_FILE="$ROOT/${RUNTIME_ROOT}/state/suggestion-memory.json"
CONTEXT_WARNINGS_FILE="$ROOT/${RUNTIME_ROOT}/state/context-warnings.jsonl"
CONTEXT_MODE_FILE="$ROOT/${RUNTIME_ROOT}/state/context-mode.json"
CONTEXTS_DIR="$ROOT/${RUNTIME_ROOT}/contexts"
KNOWLEDGE_FILE="$ROOT/${RUNTIME_ROOT}/knowledge.jsonl"
KNOWLEDGE_DIGEST_FILE="$ROOT/${RUNTIME_ROOT}/state/knowledge-digest.md"
META_SKILL="$ROOT/${RUNTIME_ROOT}/skills/${META_SKILL_NAME}/SKILL.md"

# --- Read flow state ---
STAGE="none"
COMPLETED="0"
ACTIVE_RUN="none"
ACTIVE_FEATURE="default"
ACTIVE_CONTEXT_MODE="default"
CONTEXT_MODE_NOTE=""
if [ -f "$STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    STAGE=$(jq -r '.currentStage // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    COMPLETED=$(jq -r '(.completedStages | length) // 0' "$STATE_FILE" 2>/dev/null || echo "0")
    ACTIVE_RUN=$(jq -r '.activeRunId // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
  else
    if command -v python3 >/dev/null 2>&1; then
      STAGE=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

stage = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("currentStage")
    if isinstance(value, str) and value:
        stage = value
except Exception:
    pass
print(stage)
PY
)
      COMPLETED=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

count = 0
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("completedStages")
    if isinstance(value, list):
        count = len(value)
except Exception:
    pass
print(count)
PY
)
      ACTIVE_RUN=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

run = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("activeRunId")
    if isinstance(value, str) and value:
        run = value
except Exception:
    pass
print(run)
PY
)
    else
      STAGE=$(grep -o '"currentStage"[[:space:]]*:[[:space:]]*"[^"]*"' "$STATE_FILE" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/' || echo "none")
      COMPLETED_RAW=$(grep -o '"completedStages"[[:space:]]*:[[:space:]]*\\[[^]]*\\]' "$STATE_FILE" 2>/dev/null | head -1 || echo "")
      if [ -n "$COMPLETED_RAW" ]; then
        COMPLETED=$(printf '%s' "$COMPLETED_RAW" | grep -o '"[^"]*"' | wc -l | tr -d ' ' 2>/dev/null || echo "0")
      else
        COMPLETED="0"
      fi
      ACTIVE_RUN=$(grep -o '"activeRunId"[[:space:]]*:[[:space:]]*"[^"]*"' "$STATE_FILE" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/' || echo "none")
    fi
  fi
fi

if [ -f "$ACTIVE_FEATURE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    ACTIVE_FEATURE=$(jq -r '.activeFeature // "default"' "$ACTIVE_FEATURE_FILE" 2>/dev/null || echo "default")
  elif command -v python3 >/dev/null 2>&1; then
    ACTIVE_FEATURE=$(python3 - "$ACTIVE_FEATURE_FILE" <<'PY'
import json
import sys
feature = "default"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("activeFeature")
    if isinstance(value, str) and value:
        feature = value
except Exception:
    pass
print(feature)
PY
)
  fi
fi

if [ -f "$CONTEXT_MODE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    ACTIVE_CONTEXT_MODE=$(jq -r '.activeMode // "default"' "$CONTEXT_MODE_FILE" 2>/dev/null || echo "default")
  elif command -v python3 >/dev/null 2>&1; then
    ACTIVE_CONTEXT_MODE=$(python3 - "$CONTEXT_MODE_FILE" <<'PY'
import json
import sys
mode = "default"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("activeMode")
    if isinstance(value, str) and value:
        mode = value
except Exception:
    pass
print(mode)
PY
)
  fi
fi

if [ -f "$CONTEXTS_DIR/$ACTIVE_CONTEXT_MODE.md" ]; then
  CONTEXT_MODE_NOTE="Context mode: $ACTIVE_CONTEXT_MODE (guide: ${RUNTIME_ROOT}/contexts/$ACTIVE_CONTEXT_MODE.md)"
else
  CONTEXT_MODE_NOTE="Context mode: $ACTIVE_CONTEXT_MODE"
fi

# --- Checkpoint summary ---
CHECKPOINT_SUMMARY=""
if [ -f "$CHECKPOINT_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    CHECKPOINT_SUMMARY=$(jq -r '"Checkpoint: stage=" + (.stage // "none") + ", status=" + (.status // "unknown") + ", run=" + (.runId // "none") + ", at=" + (.timestamp // "unknown")' "$CHECKPOINT_FILE" 2>/dev/null || echo "")
  elif command -v python3 >/dev/null 2>&1; then
    CHECKPOINT_SUMMARY=$(python3 - "$CHECKPOINT_FILE" <<'PY'
import json
import sys

try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    stage = data.get("stage", "none")
    status = data.get("status", "unknown")
    run_id = data.get("runId", "none")
    ts = data.get("timestamp", "unknown")
    print(f"Checkpoint: stage={stage}, status={status}, run={run_id}, at={ts}")
except Exception:
    print("")
PY
)
  fi
fi

SESSION_DIGEST=""
DIGEST_PATH="$ROOT/${RUNTIME_ROOT}/state/session-digest.md"
if [ -f "$DIGEST_PATH" ]; then
  SESSION_DIGEST=$(cat "$DIGEST_PATH" 2>/dev/null || echo "")
fi

# --- Recent stage activity summary ---
ACTIVITY_SUMMARY=""
if [ -f "$ACTIVITY_FILE" ] && [ -s "$ACTIVITY_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    ACTIVITY_SUMMARY=$(tail -n 5 "$ACTIVITY_FILE" 2>/dev/null | jq -r -s '
      map(select(type=="object"))
      | map("- " + (.ts // "unknown") + " [" + (.phase // "unknown") + "] " + (.tool // "unknown") + " (stage=" + (.stage // "unknown") + ", run=" + (.runId // "none") + ")")
      | join("\\n")
    ' 2>/dev/null || echo "")
  else
    ACTIVITY_SUMMARY=$(tail -n 3 "$ACTIVITY_FILE" 2>/dev/null || echo "")
  fi
fi

# --- Latest context warning ---
CONTEXT_WARNING=""
if [ -f "$CONTEXT_WARNINGS_FILE" ] && [ -s "$CONTEXT_WARNINGS_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    CONTEXT_WARNING=$(tail -n 1 "$CONTEXT_WARNINGS_FILE" 2>/dev/null | jq -r '.note // ""' 2>/dev/null || echo "")
  else
    CONTEXT_WARNING=$(tail -n 1 "$CONTEXT_WARNINGS_FILE" 2>/dev/null || echo "")
  fi
fi

# --- Proactive stage suggestion memory (persistent opt-out) ---
SUGGESTIONS_ENABLED="true"
STAGE_MUTED="false"
if [ -f "$SUGGESTION_MEMORY_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    SUGGESTIONS_ENABLED=$(jq -r 'if (.enabled // true) then "true" else "false" end' "$SUGGESTION_MEMORY_FILE" 2>/dev/null || echo "true")
    STAGE_MUTED=$(jq -r --arg stage "$STAGE" 'if ((.mutedStages // []) | index($stage)) == null then "false" else "true" end' "$SUGGESTION_MEMORY_FILE" 2>/dev/null || echo "false")
  elif command -v python3 >/dev/null 2>&1; then
    SUGGESTIONS_ENABLED=$(python3 - "$SUGGESTION_MEMORY_FILE" <<'PY'
import json
import sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        value = json.load(handle)
    enabled = value.get("enabled", True)
    print("true" if enabled else "false")
except Exception:
    print("true")
PY
)
    STAGE_MUTED=$(python3 - "$SUGGESTION_MEMORY_FILE" "$STAGE" <<'PY'
import json
import sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        value = json.load(handle)
    muted = value.get("mutedStages", [])
    print("true" if isinstance(muted, list) and sys.argv[2] in muted else "false")
except Exception:
    print("false")
PY
)
  fi
fi

STAGE_SUGGESTION=""
if [ "$SUGGESTIONS_ENABLED" = "true" ] && [ "$STAGE_MUTED" != "true" ]; then
  case "$STAGE" in
    brainstorm) STAGE_SUGGESTION="Suggestion: list 2-3 alternatives and ask a single focused clarifying question before direction lock." ;;
    scope) STAGE_SUGGESTION="Suggestion: lock explicit in-scope/out-of-scope boundaries and choose one scope mode." ;;
    design) STAGE_SUGGESTION="Suggestion: map failure modes per new codepath and confirm architecture boundaries before moving forward." ;;
    spec) STAGE_SUGGESTION="Suggestion: ensure every acceptance criterion is measurable and mapped to a concrete test." ;;
    plan) STAGE_SUGGESTION="Suggestion: group tasks into dependency waves and keep WAIT_FOR_CONFIRM pending until approval." ;;
    tdd) STAGE_SUGGESTION="Suggestion: execute RED → GREEN → REFACTOR for each selected slice and capture evidence per cycle." ;;
    review) STAGE_SUGGESTION="Suggestion: run Layer 1 before Layer 2 and reconcile findings into 07-review-army.json." ;;
    ship) STAGE_SUGGESTION="Suggestion: verify preflight + rollback plan before selecting exactly one finalization mode." ;;
    *) STAGE_SUGGESTION="" ;;
  esac
fi

if [ -n "$STAGE_SUGGESTION" ]; then
  NOW_TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
  TMP_SUGGESTION_FILE="$SUGGESTION_MEMORY_FILE.tmp.$$"
  if command -v jq >/dev/null 2>&1 && [ -f "$SUGGESTION_MEMORY_FILE" ]; then
    jq --arg stage "$STAGE" --arg ts "$NOW_TS" '
      .lastSuggestedStage = $stage
      | .lastSuggestedAt = $ts
      | .enabled = (.enabled // true)
      | .mutedStages = (if (.mutedStages | type) == "array" then .mutedStages else [] end)
    ' "$SUGGESTION_MEMORY_FILE" > "$TMP_SUGGESTION_FILE" 2>/dev/null || true
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$SUGGESTION_MEMORY_FILE" "$TMP_SUGGESTION_FILE" "$STAGE" "$NOW_TS" <<'PY'
import json
import sys
from pathlib import Path

source = Path(sys.argv[1])
target = Path(sys.argv[2])
stage = sys.argv[3]
ts = sys.argv[4]
payload = {"enabled": True, "mutedStages": []}
if source.exists():
    try:
        parsed = json.loads(source.read_text(encoding="utf-8"))
        if isinstance(parsed, dict):
            payload.update(parsed)
    except Exception:
        pass
if not isinstance(payload.get("mutedStages"), list):
    payload["mutedStages"] = []
if not isinstance(payload.get("enabled"), bool):
    payload["enabled"] = True
payload["lastSuggestedStage"] = stage
payload["lastSuggestedAt"] = ts
target.write_text(json.dumps(payload, indent=2) + "\\n", encoding="utf-8")
PY
  fi
  if [ -s "$TMP_SUGGESTION_FILE" ]; then
    mv "$TMP_SUGGESTION_FILE" "$SUGGESTION_MEMORY_FILE" 2>/dev/null || rm -f "$TMP_SUGGESTION_FILE" 2>/dev/null || true
  fi
fi

# --- Read meta-skill (full file) ---
META_CONTENT=""
if [ -f "$META_SKILL" ]; then
  META_CONTENT=$(cat "$META_SKILL" 2>/dev/null || echo "")
fi

# --- Build compact knowledge digest (stage-biased, top entries only) ---
KNOWLEDGE_DIGEST=""
LEARNINGS_COUNT=0
if [ -f "$KNOWLEDGE_FILE" ] && [ -s "$KNOWLEDGE_FILE" ]; then
  LEARNINGS_COUNT=$(grep -c '^{' "$KNOWLEDGE_FILE" 2>/dev/null || echo "0")
  if command -v jq >/dev/null 2>&1; then
    KNOWLEDGE_DIGEST=$(tail -n 200 "$KNOWLEDGE_FILE" 2>/dev/null | jq -Rsc --arg stage "$STAGE" '
      split("\\n")
      | map(select(length > 0))
      | map(try fromjson catch null)
      | map(select(type == "object"))
      | map(select((.stage // null) == $stage or (.stage // null) == null))
      | reverse
      | .[0:8]
      | map("- [" + ((.confidence // "unknown")|tostring) + " • " + ((.stage // "global")|tostring) + " • " + ((.domain // "general")|tostring) + "] " + ((.trigger // "trigger")|tostring) + " -> " + ((.action // "action")|tostring))
      | join("\\n")
    ' 2>/dev/null || echo "")
  elif command -v python3 >/dev/null 2>&1; then
    KNOWLEDGE_DIGEST=$(python3 - "$KNOWLEDGE_FILE" "$STAGE" <<'PY'
import json
import sys

path = sys.argv[1]
stage = sys.argv[2]
entries = []
try:
    with open(path, "r", encoding="utf-8") as fh:
        lines = fh.readlines()[-200:]
    for raw in lines:
        raw = raw.strip()
        if not raw:
            continue
        try:
            obj = json.loads(raw)
        except Exception:
            continue
        if not isinstance(obj, dict):
            continue
        row_stage = obj.get("stage")
        if row_stage not in (stage, None):
            continue
        entries.append(obj)
except Exception:
    entries = []

entries = list(reversed(entries))[:8]
out = []
for obj in entries:
    conf = str(obj.get("confidence", "unknown"))
    row_stage = str(obj.get("stage", "global"))
    domain = str(obj.get("domain", "general"))
    trigger = str(obj.get("trigger", "trigger"))
    action = str(obj.get("action", "action"))
    out.append(f"- [{conf} • {row_stage} • {domain}] {trigger} -> {action}")
print("\\n".join(out))
PY
)
  else
    KNOWLEDGE_DIGEST=$(tail -n 8 "$KNOWLEDGE_FILE" 2>/dev/null || echo "")
  fi
fi

if [ -n "$KNOWLEDGE_DIGEST" ]; then
  printf '# Knowledge digest (auto-generated)\\n\\n%s\\n' "$KNOWLEDGE_DIGEST" > "$KNOWLEDGE_DIGEST_FILE" 2>/dev/null || true
elif [ -f "$KNOWLEDGE_DIGEST_FILE" ]; then
  printf '# Knowledge digest (auto-generated)\\n\\n(no matching entries for current stage)\\n' > "$KNOWLEDGE_DIGEST_FILE" 2>/dev/null || true
fi

# --- Installed cclaw-cli version vs. project's recorded version (one-block
# upgrade-check, gstack-style). Purely informational — we never block. ---
VERSION_NOTE=""
INSTALLED_VERSION=""
PROJECT_VERSION=""
# Version lookup is skipped by default — spawning the cli on every session
# start adds ~10s on Node-based installs. Opt-in via CCLAW_HOOK_VERSION_CHECK=1.
if [ "\${CCLAW_HOOK_VERSION_CHECK:-0}" = "1" ] && command -v cclaw >/dev/null 2>&1; then
  INSTALLED_VERSION=$(cclaw --version 2>/dev/null | head -1 | awk '{print $NF}' || echo "")
fi
CONFIG_FILE="$ROOT/${RUNTIME_ROOT}/config.json"
if [ -f "$CONFIG_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    PROJECT_VERSION=$(jq -r '.version // ""' "$CONFIG_FILE" 2>/dev/null || echo "")
  else
    PROJECT_VERSION=$(grep -o '"version"[[:space:]]*:[[:space:]]*"[^"]*"' "$CONFIG_FILE" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/' || echo "")
  fi
fi
if [ -n "$INSTALLED_VERSION" ] && [ -n "$PROJECT_VERSION" ] && [ "$INSTALLED_VERSION" != "$PROJECT_VERSION" ]; then
  VERSION_NOTE="cclaw-cli $INSTALLED_VERSION installed; project recorded $PROJECT_VERSION — run 'cclaw sync' to realign."
fi

# --- Routing-check: AGENTS.md / CLAUDE.md must contain the cclaw block. ---
ROUTING_NOTE=""
ROUTING_MISSING=""
for routing_file in "$ROOT/AGENTS.md" "$ROOT/CLAUDE.md"; do
  if [ -f "$routing_file" ]; then
    if ! grep -q "cclaw-start" "$routing_file" 2>/dev/null; then
      ROUTING_MISSING="$ROUTING_MISSING $(basename "$routing_file")"
    fi
  fi
done
if [ -n "$ROUTING_MISSING" ]; then
  ROUTING_NOTE="Routing block missing from:\${ROUTING_MISSING}. Run 'cclaw sync' to re-inject."
fi

# --- Build context message ---
CTX="cclaw loaded. Flow: stage=$STAGE ($COMPLETED/8 completed, run=$ACTIVE_RUN, feature=$ACTIVE_FEATURE). Active artifacts: ${RUNTIME_ROOT}/artifacts/. Feature snapshots: ${RUNTIME_ROOT}/features/$ACTIVE_FEATURE/. Learnings: $LEARNINGS_COUNT entries."
if [ -n "$VERSION_NOTE" ]; then
  CTX="$CTX
$VERSION_NOTE"
fi
if [ -n "$ROUTING_NOTE" ]; then
  CTX="$CTX
$ROUTING_NOTE"
fi
if [ -n "$CONTEXT_MODE_NOTE" ]; then
  CTX="$CTX
$CONTEXT_MODE_NOTE"
fi
if [ -n "$CHECKPOINT_SUMMARY" ]; then
  CTX="$CTX
$CHECKPOINT_SUMMARY"
fi
if [ -n "$SESSION_DIGEST" ]; then
  CTX="$CTX
Last session:
$SESSION_DIGEST"
fi
if [ -n "$ACTIVITY_SUMMARY" ]; then
  CTX="$CTX
Recent stage activity:
$ACTIVITY_SUMMARY"
fi
if [ -n "$CONTEXT_WARNING" ]; then
  CTX="$CTX
Latest context warning:
$CONTEXT_WARNING"
fi
if [ -n "$STAGE_SUGGESTION" ]; then
  CTX="$CTX
$STAGE_SUGGESTION
To disable suggestions persistently set ${RUNTIME_ROOT}/state/suggestion-memory.json -> enabled=false."
fi
if [ -n "$KNOWLEDGE_DIGEST" ]; then
  CTX="$CTX
Knowledge digest (top relevant entries):
$KNOWLEDGE_DIGEST"
fi
if [ -n "$META_CONTENT" ]; then
  CTX="$CTX

$META_CONTENT"
fi

# --- Escape for JSON ---
${ESCAPE_FN}
MSG=$(escape_json "$CTX")

# --- Output harness-specific JSON ---
case "$HARNESS" in
  claude)
    printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\\n' "$MSG"
    ;;
  cursor)
    printf '{"additional_context":"%s"}\\n' "$MSG"
    ;;
  codex)
    printf '{"hookSpecificOutput":{"hookEventName":"SessionStart","additionalContext":"%s"}}\\n' "$MSG"
    ;;
  *)
    printf '{"additional_context":"%s"}\\n' "$MSG"
    ;;
esac
`;
}

export function stopCheckpointScript(): string {
  return `#!/usr/bin/env bash
# cclaw stop hook — generated by cclaw sync
# Writes checkpoint state and reminds agent about flow/session consistency.
set -euo pipefail

${DETECT_ROOT}

INPUT=$(cat 2>/dev/null || echo '{}')

STATE_DIR="$ROOT/${RUNTIME_ROOT}/state"
STATE_FILE="$STATE_DIR/flow-state.json"
CHECKPOINT_FILE="$STATE_DIR/checkpoint.json"
CHECKPOINT_TMP="$STATE_DIR/checkpoint.json.tmp.$$"
CHECKPOINT_LOCK_DIR="$STATE_DIR/.checkpoint.lock"
STAGE="none"
ACTIVE_RUN="none"
LOOP_COUNT=""

if command -v jq >/dev/null 2>&1; then
  LOOP_COUNT=$(echo "$INPUT" | jq -r '.loop_count // 0' 2>/dev/null || echo "")
elif command -v python3 >/dev/null 2>&1; then
  LOOP_COUNT=$(INPUT_JSON="$INPUT" python3 - <<'PY'
import json
import os

try:
    data = json.loads(os.environ.get("INPUT_JSON", "{}"))
    print(data.get("loop_count", 0))
except Exception:
    print("")
PY
)
fi
[ -n "$LOOP_COUNT" ] || LOOP_COUNT="0"

if [ -f "$STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    STAGE=$(jq -r '.currentStage // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    ACTIVE_RUN=$(jq -r '.activeRunId // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
  elif command -v python3 >/dev/null 2>&1; then
    STAGE=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

stage = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("currentStage")
    if isinstance(value, str) and value:
        stage = value
except Exception:
    pass
print(stage)
PY
)
    ACTIVE_RUN=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

run = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("activeRunId")
    if isinstance(value, str) and value:
        run = value
except Exception:
    pass
print(run)
PY
)
  fi
fi

DIRTY_STATE="unknown"
if command -v git >/dev/null 2>&1; then
  if git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
    if [ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ]; then
      DIRTY_STATE="dirty"
    else
      DIRTY_STATE="clean"
    fi
  fi
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
mkdir -p "$STATE_DIR" 2>/dev/null || true
CHECKPOINT_WRITTEN=0

cleanup_checkpoint_tmp() {
  rm -f "$CHECKPOINT_TMP" 2>/dev/null || true
}

acquire_checkpoint_lock() {
  local attempt=0
  while ! mkdir "$CHECKPOINT_LOCK_DIR" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -ge 200 ]; then
      return 1
    fi
    sleep 0.02
  done
  return 0
}

release_checkpoint_lock() {
  rmdir "$CHECKPOINT_LOCK_DIR" 2>/dev/null || true
}

cleanup_checkpoint_state() {
  cleanup_checkpoint_tmp
  release_checkpoint_lock
}
trap cleanup_checkpoint_state EXIT INT TERM

acquire_checkpoint_lock || exit 0

if command -v jq >/dev/null 2>&1; then
  EXISTING_JSON="{}"
  if [ -f "$CHECKPOINT_FILE" ]; then
    EXISTING_JSON=$(jq -c '.' "$CHECKPOINT_FILE" 2>/dev/null || echo "{}")
  fi

  if jq -n \
    --argjson existing "$EXISTING_JSON" \
    --arg stage "$STAGE" \
    --arg run "$ACTIVE_RUN" \
    --arg ts "$TS" \
    --arg dirty "$DIRTY_STATE" \
    --arg harness "$HARNESS" \
    '
      ($existing | if type == "object" then . else {} end) as $base
      | $base + {
          stage: $stage,
          runId: $run,
          status: (if (($base.status // "") | tostring | length) > 0 then ($base.status | tostring) else "in_progress" end),
          dirtyState: $dirty,
          lastCompletedStep: (if ($base.lastCompletedStep | type) == "string" then $base.lastCompletedStep else "" end),
          remainingSteps: (if ($base.remainingSteps | type) == "array" then $base.remainingSteps else [] end),
          blockers: (if ($base.blockers | type) == "array" then $base.blockers else [] end),
          harness: $harness,
          timestamp: $ts
        }
    ' > "$CHECKPOINT_TMP" 2>/dev/null; then
    if mv "$CHECKPOINT_TMP" "$CHECKPOINT_FILE" 2>/dev/null; then
      CHECKPOINT_WRITTEN=1
    fi
  fi
fi

if [ "$CHECKPOINT_WRITTEN" -eq 0 ] && command -v python3 >/dev/null 2>&1; then
  if python3 - "$CHECKPOINT_FILE" "$CHECKPOINT_TMP" "$STAGE" "$ACTIVE_RUN" "$DIRTY_STATE" "$HARNESS" "$TS" <<'PY'
import json
import sys
from pathlib import Path

checkpoint_path, checkpoint_tmp_path, stage, run_id, dirty_state, harness, ts = sys.argv[1:8]
checkpoint_file = Path(checkpoint_path)
checkpoint_tmp_file = Path(checkpoint_tmp_path)
payload = {}
if checkpoint_file.exists():
    try:
        current = json.loads(checkpoint_file.read_text(encoding="utf-8"))
        if isinstance(current, dict):
            payload = dict(current)
    except Exception:
        payload = {}

payload["stage"] = stage
payload["runId"] = run_id
payload["dirtyState"] = dirty_state
payload["harness"] = harness
payload["timestamp"] = ts
if not isinstance(payload.get("status"), str) or not payload["status"].strip():
    payload["status"] = "in_progress"
if not isinstance(payload.get("lastCompletedStep"), str):
    payload["lastCompletedStep"] = ""
if not isinstance(payload.get("remainingSteps"), list):
    payload["remainingSteps"] = []
if not isinstance(payload.get("blockers"), list):
    payload["blockers"] = []

try:
    checkpoint_tmp_file.write_text(json.dumps(payload, indent=2) + "\\n", encoding="utf-8")
except Exception:
    raise SystemExit(1)
PY
  then
    if mv "$CHECKPOINT_TMP" "$CHECKPOINT_FILE" 2>/dev/null; then
      CHECKPOINT_WRITTEN=1
    fi
  fi
fi

if [ "$CHECKPOINT_WRITTEN" -eq 0 ]; then
  printf '{\n  "stage": "%s",\n  "runId": "%s",\n  "status": "in_progress",\n  "dirtyState": "%s",\n  "lastCompletedStep": "",\n  "remainingSteps": [],\n  "blockers": [],\n  "harness": "%s",\n  "timestamp": "%s"\n}\n' \
    "$STAGE" "$ACTIVE_RUN" "$DIRTY_STATE" "$HARNESS" "$TS" > "$CHECKPOINT_TMP" 2>/dev/null || true
  if [ -s "$CHECKPOINT_TMP" ] && mv "$CHECKPOINT_TMP" "$CHECKPOINT_FILE" 2>/dev/null; then
    CHECKPOINT_WRITTEN=1
  fi
fi

cleanup_checkpoint_state
trap - EXIT INT TERM

CHECKPOINT_NOTE="Checkpoint updated at ${RUNTIME_ROOT}/state/checkpoint.json."
if [ "$CHECKPOINT_WRITTEN" -eq 0 ]; then
  CHECKPOINT_NOTE="Checkpoint update failed. Review ${RUNTIME_ROOT}/state/checkpoint.json manually."
fi

RUN_SYNC_NOTE="Run metadata sync removed; active artifacts stay in ${RUNTIME_ROOT}/artifacts until cclaw archive."

# --- Escape for JSON ---
${ESCAPE_FN}
MSG=$(escape_json "Cclaw: session ending (stage=$STAGE, run=$ACTIVE_RUN). $CHECKPOINT_NOTE $RUN_SYNC_NOTE Before stopping: (1) confirm flow-state reflects reality, (2) ensure artifact changes match current feature intent, (3) if you discovered a non-obvious rule/pattern, append one strict-schema JSON line to ${RUNTIME_ROOT}/knowledge.jsonl, (4) commit or revert pending changes.")

# --- Output harness-specific JSON ---
case "$HARNESS" in
  claude)
    printf '{"systemMessage":"%s"}\\n' "$MSG"
    ;;
  cursor)
    if [ "\${LOOP_COUNT:-0}" -eq 0 ]; then
      printf '{"followup_message":"%s"}\\n' "$MSG"
    else
      printf '{}\\n'
    fi
    ;;
  codex)
    printf '{"systemMessage":"%s"}\\n' "$MSG"
    ;;
  *)
    printf '{"systemMessage":"%s"}\\n' "$MSG"
    ;;
esac
`;
}

export function preCompactScript(): string {
  return `#!/usr/bin/env bash
# cclaw pre-compact hook — generated by cclaw sync
# Persists a session digest before the harness compacts/clears context, so the
# next session-start hook can restore the most important state without the agent
# having to re-derive it from scratch.
set -uo pipefail

${DETECT_ROOT}

INPUT=$(cat 2>/dev/null || echo '{}')

STATE_DIR="$ROOT/${RUNTIME_ROOT}/state"
STATE_FILE="$STATE_DIR/flow-state.json"
DELEGATION_FILE="$STATE_DIR/delegation-log.json"
KNOWLEDGE_FILE="$ROOT/${RUNTIME_ROOT}/knowledge.jsonl"
DIGEST_FILE="$STATE_DIR/session-digest.md"
DIGEST_TMP="$STATE_DIR/session-digest.md.tmp.$$"

mkdir -p "$STATE_DIR" 2>/dev/null || true

cleanup_digest_tmp() {
  rm -f "$DIGEST_TMP" 2>/dev/null || true
}
trap cleanup_digest_tmp EXIT INT TERM

STAGE="none"
TRACK="standard"
COMPLETED="0"
SKIPPED=""
ACTIVE_RUN="none"
PASSED_GATES=""
BLOCKED_GATES=""

if [ -f "$STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    STAGE=$(jq -r '.currentStage // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    TRACK=$(jq -r '.track // "standard"' "$STATE_FILE" 2>/dev/null || echo "standard")
    COMPLETED=$(jq -r '(.completedStages // []) | length' "$STATE_FILE" 2>/dev/null || echo "0")
    SKIPPED=$(jq -r '(.skippedStages // []) | join(",")' "$STATE_FILE" 2>/dev/null || echo "")
    ACTIVE_RUN=$(jq -r '.activeRunId // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    PASSED_GATES=$(jq -r --arg stage "$STAGE" '(.stageGates[$stage].passed // []) | join(",")' "$STATE_FILE" 2>/dev/null || echo "")
    BLOCKED_GATES=$(jq -r --arg stage "$STAGE" '(.stageGates[$stage].blocked // []) | join(",")' "$STATE_FILE" 2>/dev/null || echo "")
  elif command -v python3 >/dev/null 2>&1; then
    OUTPUT=$(python3 - "$STATE_FILE" <<'PY'
import json, sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
except Exception:
    data = {}
stage = data.get("currentStage") or "none"
track = data.get("track") or "standard"
completed = data.get("completedStages") or []
skipped = data.get("skippedStages") or []
run = data.get("activeRunId") or "none"
gates = (data.get("stageGates") or {}).get(stage) or {}
passed = gates.get("passed") or []
blocked = gates.get("blocked") or []
print(stage)
print(track)
print(len(completed) if isinstance(completed, list) else 0)
print(",".join(skipped) if isinstance(skipped, list) else "")
print(run)
print(",".join(passed) if isinstance(passed, list) else "")
print(",".join(blocked) if isinstance(blocked, list) else "")
PY
)
    {
      IFS= read -r STAGE
      IFS= read -r TRACK
      IFS= read -r COMPLETED
      IFS= read -r SKIPPED
      IFS= read -r ACTIVE_RUN
      IFS= read -r PASSED_GATES
      IFS= read -r BLOCKED_GATES
    } <<EOF
$OUTPUT
EOF
  fi
fi

DELEGATION_PENDING=""
if [ -f "$DELEGATION_FILE" ] && command -v jq >/dev/null 2>&1; then
  DELEGATION_PENDING=$(jq -r --arg stage "$STAGE" '
    (.entries // [])
    | map(select((.stage // "") == $stage and (.status // "") != "completed" and (.status // "") != "waived"))
    | map(.agent // "unknown")
    | unique
    | join(",")
  ' "$DELEGATION_FILE" 2>/dev/null || echo "")
fi

KNOWLEDGE_TAIL=""
if [ -f "$KNOWLEDGE_FILE" ] && [ -s "$KNOWLEDGE_FILE" ]; then
  KNOWLEDGE_TAIL=$(tail -n 12 "$KNOWLEDGE_FILE" 2>/dev/null || echo "")
fi

GIT_HEAD=""
GIT_BRANCH=""
GIT_DIRTY="unknown"
if command -v git >/dev/null 2>&1 && git -C "$ROOT" rev-parse --is-inside-work-tree >/dev/null 2>&1; then
  GIT_HEAD=$(git -C "$ROOT" rev-parse --short HEAD 2>/dev/null || echo "")
  GIT_BRANCH=$(git -C "$ROOT" rev-parse --abbrev-ref HEAD 2>/dev/null || echo "")
  if [ -n "$(git -C "$ROOT" status --porcelain 2>/dev/null)" ]; then
    GIT_DIRTY="dirty"
  else
    GIT_DIRTY="clean"
  fi
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")

{
  printf '# Session Digest\n'
  printf '_Generated by pre-compact hook at %s_\n\n' "$TS"
  printf '## Flow snapshot\n'
  printf '- track: %s\n' "$TRACK"
  printf '- current stage: %s\n' "$STAGE"
  printf '- completed: %s stages\n' "$COMPLETED"
  printf '- skipped: %s\n' "\${SKIPPED:-(none)}"
  printf '- run: %s\n\n' "$ACTIVE_RUN"
  printf '## Gates (current stage)\n'
  printf '- passed: %s\n' "\${PASSED_GATES:-(none)}"
  printf '- blocked: %s\n\n' "\${BLOCKED_GATES:-(none)}"
  printf '## Outstanding delegations\n'
  printf '- pending: %s\n\n' "\${DELEGATION_PENDING:-(none)}"
  printf '## Git\n'
  printf '- branch: %s\n' "\${GIT_BRANCH:-(unknown)}"
  printf '- head: %s\n' "\${GIT_HEAD:-(unknown)}"
  printf '- worktree: %s\n\n' "$GIT_DIRTY"
  if [ -n "$KNOWLEDGE_TAIL" ]; then
    printf '## Knowledge tail\n'
    printf '%s\n' "$KNOWLEDGE_TAIL"
  fi
} > "$DIGEST_TMP" 2>/dev/null || true

if [ -s "$DIGEST_TMP" ]; then
  mv "$DIGEST_TMP" "$DIGEST_FILE" 2>/dev/null || rm -f "$DIGEST_TMP" 2>/dev/null || true
fi

trap - EXIT INT TERM
exit 0
`;
}

// ---------------------------------------------------------------------------
// hooks.json generators are defined in observe.ts (shared across harnesses).
// ---------------------------------------------------------------------------

export { claudeHooksJsonWithObservation as claudeHooksJson } from "./observe.js";
export { cursorHooksJsonWithObservation as cursorHooksJson } from "./observe.js";
export { codexHooksJsonWithObservation as codexHooksJson } from "./observe.js";

// ---------------------------------------------------------------------------
// OpenCode plugin — JS module
// ---------------------------------------------------------------------------

export function opencodePluginJs(_options: HookRuntimeOptions = {}): string {
  return `// cclaw OpenCode plugin — generated by cclaw sync
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export default function cclawPlugin(ctx) {
  const root = ctx.directory || process.cwd();
  const runtimeDir = join(root, "${RUNTIME_ROOT}");
  const stateDir = join(runtimeDir, "state");
  const flowStatePath = join(stateDir, "flow-state.json");
  const checkpointPath = join(stateDir, "checkpoint.json");
  const activityPath = join(stateDir, "stage-activity.jsonl");
  const contextWarningsPath = join(stateDir, "context-warnings.jsonl");
  const contextModePath = join(stateDir, "context-mode.json");
  const contextsDir = join(runtimeDir, "contexts");
  const sessionDigestPath = join(stateDir, "session-digest.md");
  const knowledgePath = join(runtimeDir, "knowledge.jsonl");
  const knowledgeDigestPath = join(stateDir, "knowledge-digest.md");
  const metaSkillPath = join(runtimeDir, "skills/${META_SKILL_NAME}/SKILL.md");

  function ensureRuntimeDirs() {
    try {
      mkdirSync(runtimeDir, { recursive: true });
    } catch {
      // ignore
    }
    try {
      mkdirSync(stateDir, { recursive: true });
    } catch {
      // ignore
    }
  }

  function readFlowState() {
    try {
      const raw = readFileSync(flowStatePath, "utf8");
      const state = JSON.parse(raw);
      return {
        stage: typeof state.currentStage === "string" ? state.currentStage : "none",
        completed: Array.isArray(state.completedStages) ? state.completedStages.length : 0,
        activeRunId: typeof state.activeRunId === "string" ? state.activeRunId : "none"
      };
    } catch {
      return { stage: "none", completed: 0, activeRunId: "none" };
    }
  }

  function readFileText(filePath) {
    try {
      return readFileSync(filePath, "utf8");
    } catch {
      return "";
    }
  }

  function readTailLines(filePath, maxLines) {
    const text = readFileText(filePath).trim();
    if (!text) return [];
    return text.split(/\\r?\\n/).slice(-maxLines);
  }

  function readCheckpointSummary() {
    try {
      const raw = readFileText(checkpointPath);
      if (!raw) return "";
      const cp = JSON.parse(raw);
      return \`Checkpoint: stage=\${cp.stage || "none"}, status=\${cp.status || "unknown"}, run=\${cp.runId || "none"}, at=\${cp.timestamp || "unknown"}\`;
    } catch {
      return "";
    }
  }

  function readContextMode() {
    let mode = "default";
    try {
      const parsed = JSON.parse(readFileText(contextModePath));
      if (parsed && typeof parsed.activeMode === "string" && parsed.activeMode.trim().length > 0) {
        mode = parsed.activeMode.trim();
      }
    } catch {
      // keep default
    }
    const guidePath = join(contextsDir, mode + ".md");
    const guide = existsSync(guidePath) ? "${RUNTIME_ROOT}/contexts/" + mode + ".md" : "";
    return { mode, guide };
  }

  function readRecentActivity() {
    try {
      const lines = readTailLines(activityPath, 5);
      if (lines.length === 0) return [];
      return lines
        .map((line) => {
          try {
            return JSON.parse(line);
          } catch {
            return null;
          }
        })
        .filter(Boolean)
        .map((entry) => \`- \${entry.ts || "unknown"} [\${entry.phase || "unknown"}] \${entry.tool || "unknown"} (stage=\${entry.stage || "unknown"}, run=\${entry.runId || "none"})\`);
    } catch {
      return [];
    }
  }

  function readLatestContextWarning() {
    try {
      const line = readTailLines(contextWarningsPath, 1)[0];
      if (!line) return "";
      try {
        const parsed = JSON.parse(line);
        if (parsed && typeof parsed.note === "string") return parsed.note;
      } catch {
        // non-json fallback
      }
      return line;
    } catch {
      return "";
    }
  }

  function readKnowledgeDigest() {
    const digest = readFileText(knowledgeDigestPath).trim();
    if (!digest) {
      return readTailLines(knowledgePath, 12);
    }
    return digest
      .split(/\\r?\\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .filter((line) => !line.startsWith("#"));
  }

  function buildBootstrap() {
    const flow = readFlowState();
    const parts = [
      \`cclaw loaded. Flow: stage=\${flow.stage} (\${flow.completed}/8 completed, run=\${flow.activeRunId}). Active artifacts: ${RUNTIME_ROOT}/artifacts/\`
    ];
    const contextMode = readContextMode();
    parts.push(
      contextMode.guide
        ? \`Context mode: \${contextMode.mode} (guide: \${contextMode.guide})\`
        : \`Context mode: \${contextMode.mode}\`
    );

    const checkpoint = readCheckpointSummary();
    if (checkpoint) parts.push(checkpoint);

    const digest = readFileText(sessionDigestPath).trim();
    if (digest) parts.push("Last session:", digest);

    const activity = readRecentActivity();
    if (activity.length > 0) parts.push("Recent stage activity:", ...activity);

    const warning = readLatestContextWarning();
    if (warning) parts.push("Latest context warning:", warning);

    const knowledge = readKnowledgeDigest();
    if (knowledge.length > 0) parts.push("Knowledge digest (top relevant entries):", ...knowledge);

    parts.push(
      "If you discover a non-obvious rule or pattern, append one strict-schema JSON line to .cclaw/knowledge.jsonl using type: rule, pattern, lesson, or compound."
    );

    const meta = readFileText(metaSkillPath).trim();
    if (meta) parts.push("", meta);
    return parts.join("\\n");
  }

  let bootstrapCache = "";

  function refreshBootstrapCache() {
    bootstrapCache = buildBootstrap();
  }

  function getBootstrap() {
    if (!bootstrapCache) refreshBootstrapCache();
    return bootstrapCache;
  }

  async function runHookScript(scriptFileName, payload = {}) {
    const { spawnSync } = await import("node:child_process");
    const scriptPath = join(root, "${RUNTIME_ROOT}/hooks/" + scriptFileName);
    const input = typeof payload === "string" ? payload : JSON.stringify(payload ?? {});
    try {
      spawnSync("bash", [scriptPath], {
        cwd: root,
        timeout: 20000,
        stdio: ["pipe", "ignore", "ignore"],
        input
      });
    } catch {
      // advisory-only runtime path
    }
  }

  function normalizeToolPayload(input, output) {
    if (typeof output === "undefined") return input ?? {};
    return { input: input ?? {}, output: output ?? {} };
  }

  function resolveEventType(payload) {
    if (typeof payload === "string") return payload;
    if (payload && typeof payload === "object") {
      if (typeof payload.type === "string") return payload.type;
      if (typeof payload.name === "string") return payload.name;
      if (payload.event && typeof payload.event === "object") {
        if (typeof payload.event.type === "string") return payload.event.type;
        if (typeof payload.event.name === "string") return payload.event.name;
      }
    }
    return "";
  }

  function resolveEventData(payload) {
    if (payload && typeof payload === "object" && payload.event && typeof payload.event === "object") {
      return payload.event;
    }
    return payload;
  }

  ensureRuntimeDirs();

  return {
    event: async (payload) => {
      const eventType = resolveEventType(payload);
      const eventData = resolveEventData(payload);
      if (
        eventType === "session.created" ||
        eventType === "session.resumed" ||
        eventType === "session.compacted" ||
        eventType === "session.cleared"
      ) {
        // Avoid writing directly to stdout in lifecycle hooks because it can
        // interfere with OpenCode TUI rendering. Bootstrap is injected via
        // the system transform hook instead.
        refreshBootstrapCache();
      }
      if (eventType === "session.idle") {
        await runHookScript("stop-checkpoint.sh", { loop_count: 0 });
      }
      if (eventType === "tool.execute.before") {
        const toolPayload = normalizeToolPayload(eventData, undefined);
        await runHookScript("prompt-guard.sh", toolPayload);
        await runHookScript("workflow-guard.sh", toolPayload);
      }
      if (eventType === "tool.execute.after") {
        const toolPayload = normalizeToolPayload(eventData, undefined);
        await runHookScript("context-monitor.sh", toolPayload);
      }
    },
    "tool.execute.before": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      await runHookScript("prompt-guard.sh", payload);
      await runHookScript("workflow-guard.sh", payload);
    },
    "tool.execute.after": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      await runHookScript("context-monitor.sh", payload);
    },
    "experimental.chat.system.transform": (payload) => {
      const bootstrap = getBootstrap();
      if (typeof payload === "string") {
        return payload.includes("cclaw loaded.") ? payload : \`\${payload}\\n\\n\${bootstrap}\`;
      }
      if (payload && typeof payload === "object" && typeof payload.system === "string") {
        if (payload.system.includes("cclaw loaded.")) return payload;
        return { ...payload, system: \`\${payload.system}\\n\\n\${bootstrap}\` };
      }
      return payload;
    }
  };
}
`;
}
// ---------------------------------------------------------------------------
// AGENTS.md block for hooks
// ---------------------------------------------------------------------------

export function hooksAgentsMdBlock(): string {
  return `### Hooks (real lifecycle integration)

Cclaw generates real hook integrations across harnesses:
- **Claude/Cursor/Codex:** lifecycle rehydration + PreToolUse/PostToolUse + Stop
- **OpenCode:** session lifecycle + system transform rehydration + bootstrap parity (digest/warnings/knowledge snapshot)

| Harness | Hook file | Events |
|---------|-----------|--------|
| Claude Code | \`.claude/hooks/hooks.json\` | SessionStart(startup/resume/clear/compact), PreToolUse, PostToolUse, Stop |
| Cursor | \`.cursor/hooks.json\` | sessionStart/sessionResume/sessionClear/sessionCompact, preToolUse, postToolUse, stop |
| Codex | \`.codex/hooks.json\` | SessionStart(startup/resume/clear/compact), PreToolUse, PostToolUse, Stop |
| OpenCode | \`${RUNTIME_ROOT}/hooks/opencode-plugin.mjs\` | session.created/updated/resumed/cleared/compacted/idle, tool.execute.before/after, system transform |

Hook state files:
- \`${RUNTIME_ROOT}/state/stage-activity.jsonl\`
- \`${RUNTIME_ROOT}/state/checkpoint.json\`
`;
}
