/**
 * Tool observation system — captures PreToolUse/PostToolUse events
 * to .cclaw/observations.jsonl for continuous learning.
 *
 * observe.sh: reads hook JSON from stdin, extracts tool name + truncated I/O,
 * appends a JSONL line to .cclaw/observations.jsonl.
 *
 * summarize-observations.sh: run at session stop, reads recent observations,
 * identifies patterns, and appends new learnings to .cclaw/learnings.jsonl.
 */

import { RUNTIME_ROOT } from "../constants.js";
import { RUNTIME_SHELL_DETECT_ROOT } from "./hooks.js";

export interface PromptGuardOptions {
  strictMode?: boolean;
}

export function promptGuardScript(options: PromptGuardOptions = {}): string {
  const promptGuardMode = options.strictMode === true ? "strict" : "advisory";
  return `#!/usr/bin/env bash
# cclaw prompt guard hook — generated by cclaw sync
# Advisory-only guard for risky writes into ${RUNTIME_ROOT} runtime files.
set -uo pipefail
PROMPT_GUARD_MODE="${promptGuardMode}"

HARNESS="codex"
if [ -n "\${CLAUDE_PROJECT_DIR:-}" ]; then
  HARNESS="claude"
elif [ -n "\${CURSOR_PROJECT_DIR:-}" ] || [ -n "\${CURSOR_PROJECT_ROOT:-}" ]; then
  HARNESS="cursor"
elif [ -n "\${OPENCODE_PROJECT_DIR:-}" ] || [ -n "\${OPENCODE_PROJECT_ROOT:-}" ]; then
  HARNESS="opencode"
fi

${RUNTIME_SHELL_DETECT_ROOT}

STATE_DIR="$ROOT/${RUNTIME_ROOT}/state"
GUARD_LOG="$STATE_DIR/prompt-guard.jsonl"
mkdir -p "$STATE_DIR" 2>/dev/null || true

INPUT=$(cat 2>/dev/null || echo '{}')
[ -n "$INPUT" ] || exit 0

TOOL="unknown"
PAYLOAD=""
if command -v jq >/dev/null 2>&1; then
  TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // .tool // "unknown"' 2>/dev/null || echo "unknown")
  PAYLOAD=$(printf '%s' "$INPUT" | jq -r '.tool_input // .input // .arguments // .params // .payload // {} | tostring' 2>/dev/null || echo "")
elif command -v python3 >/dev/null 2>&1; then
  TOOL=$(INPUT_JSON="$INPUT" python3 - <<'PY'
import json
import os

try:
    value = json.loads(os.environ.get("INPUT_JSON", "{}"))
except Exception:
    value = {}
tool = value.get("tool_name") or value.get("tool") or "unknown"
print(tool if isinstance(tool, str) else "unknown")
PY
)
  PAYLOAD=$(printf '%s' "$INPUT")
else
  PAYLOAD=$(printf '%s' "$INPUT")
fi

if [ -z "$PAYLOAD" ]; then
  PAYLOAD=$(printf '%s' "$INPUT")
fi

PAYLOAD_LOWER=$(printf '%s' "$PAYLOAD" | tr '[:upper:]' '[:lower:]')
TOOL_LOWER=$(printf '%s' "$TOOL" | tr '[:upper:]' '[:lower:]')
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
REASONS=""

case "$TOOL_LOWER" in
  write|edit|multiedit|delete|applypatch|runcommand|shell|terminal|execcommand)
    if printf '%s' "$PAYLOAD_LOWER" | grep -Eq '\.cclaw/(state|artifacts|hooks|skills|commands|agents|runs|learnings)'; then
      REASONS="write_to_cclaw_runtime"
    fi
    ;;
esac

if printf '%s' "$PAYLOAD_LOWER" | grep -Eq '(rm[[:space:]]+-rf[[:space:]]+\.cclaw|curl[[:space:]].*https?://|wget[[:space:]].*https?://|base64[[:space:]]+-d|eval[(]|python[[:space:]]+-c)'; then
  if [ -n "$REASONS" ]; then
    REASONS="$REASONS,suspicious_payload_pattern"
  else
    REASONS="suspicious_payload_pattern"
  fi
fi

if [ -n "$REASONS" ]; then
  NOTE="Cclaw advisory: potential risky write intent detected for ${RUNTIME_ROOT} runtime (\${REASONS}). Prefer installer commands or explicit confirmation before mutating runtime internals."
  if command -v jq >/dev/null 2>&1; then
    ENTRY=$(jq -n -c \
      --arg ts "$TS" \
      --arg harness "$HARNESS" \
      --arg tool "$TOOL" \
      --arg reasons "$REASONS" \
      --arg note "$NOTE" \
      '{ts:$ts,harness:$harness,tool:$tool,reasons:($reasons|split(",")),note:$note}' 2>/dev/null || echo "")
  elif command -v python3 >/dev/null 2>&1; then
    ENTRY=$(TS="$TS" HARNESS="$HARNESS" TOOL="$TOOL" REASONS="$REASONS" NOTE="$NOTE" python3 - <<'PY'
import json, os

ts = os.environ.get("TS") or ""
harness = os.environ.get("HARNESS") or ""
tool = os.environ.get("TOOL") or "unknown"
reasons_raw = os.environ.get("REASONS") or ""
note = os.environ.get("NOTE") or ""
reasons = [r for r in reasons_raw.split(",") if r]
print(json.dumps({"ts": ts, "harness": harness, "tool": tool, "reasons": reasons, "note": note}, ensure_ascii=False))
PY
)
  else
    ENTRY=""
  fi

  if [ -n "$ENTRY" ]; then
    printf '%s\n' "$ENTRY" >> "$GUARD_LOG" 2>/dev/null || true
  fi
  if [ "$PROMPT_GUARD_MODE" = "strict" ]; then
    printf '[cclaw] %s (blocked by strict mode)\n' "$NOTE" >&2
    exit 1
  fi
  printf '[cclaw] %s\n' "$NOTE" >&2
fi

exit 0
`;
}

export function workflowGuardScript(): string {
  return `#!/usr/bin/env bash
# cclaw workflow guard hook — generated by cclaw sync
# Enforces stage-aware command discipline and recent flow-state read hygiene.
set -uo pipefail
WORKFLOW_GUARD_MODE="\${CCLAW_WORKFLOW_GUARD_MODE:-advisory}"
MAX_FLOW_READ_AGE_SEC="\${CCLAW_WORKFLOW_GUARD_MAX_AGE_SEC:-1800}"

${RUNTIME_SHELL_DETECT_ROOT}

STATE_DIR="$ROOT/${RUNTIME_ROOT}/state"
FLOW_STATE_FILE="$STATE_DIR/flow-state.json"
GUARD_STATE_FILE="$STATE_DIR/workflow-guard.json"
GUARD_LOG="$STATE_DIR/workflow-guard.jsonl"
mkdir -p "$STATE_DIR" 2>/dev/null || true

INPUT=$(cat 2>/dev/null || echo '{}')
[ -n "$INPUT" ] || exit 0

TOOL="unknown"
PAYLOAD=""
if command -v jq >/dev/null 2>&1; then
  TOOL=$(printf '%s' "$INPUT" | jq -r '.tool_name // .tool // "unknown"' 2>/dev/null || echo "unknown")
  PAYLOAD=$(printf '%s' "$INPUT" | jq -r '.tool_input // .input // .arguments // .params // .payload // {} | tostring' 2>/dev/null || echo "")
elif command -v python3 >/dev/null 2>&1; then
  TOOL=$(INPUT_JSON="$INPUT" python3 - <<'PY'
import json
import os
try:
    value = json.loads(os.environ.get("INPUT_JSON", "{}"))
except Exception:
    value = {}
tool = value.get("tool_name") or value.get("tool") or "unknown"
print(tool if isinstance(tool, str) else "unknown")
PY
)
  PAYLOAD=$(printf '%s' "$INPUT")
else
  PAYLOAD=$(printf '%s' "$INPUT")
fi

[ -n "$PAYLOAD" ] || PAYLOAD=$(printf '%s' "$INPUT")
TOOL_LOWER=$(printf '%s' "$TOOL" | tr '[:upper:]' '[:lower:]')
PAYLOAD_LOWER=$(printf '%s' "$PAYLOAD" | tr '[:upper:]' '[:lower:]')
TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
NOW_EPOCH=$(date +%s 2>/dev/null || echo "0")
REASONS=""

CURRENT_STAGE="none"
if [ -f "$FLOW_STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    CURRENT_STAGE=$(jq -r '.currentStage // "none"' "$FLOW_STATE_FILE" 2>/dev/null || echo "none")
  elif command -v python3 >/dev/null 2>&1; then
    CURRENT_STAGE=$(python3 - "$FLOW_STATE_FILE" <<'PY'
import json
import sys
stage = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        parsed = json.load(fh)
    value = parsed.get("currentStage")
    if isinstance(value, str) and value:
        stage = value
except Exception:
    pass
print(stage)
PY
)
  fi
fi

LAST_FLOW_READ_AT=0
if [ -f "$GUARD_STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    LAST_FLOW_READ_AT=$(jq -r '.lastFlowReadAtEpoch // 0' "$GUARD_STATE_FILE" 2>/dev/null || echo "0")
  elif command -v python3 >/dev/null 2>&1; then
    LAST_FLOW_READ_AT=$(python3 - "$GUARD_STATE_FILE" <<'PY'
import json
import sys
value = 0
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        parsed = json.load(fh)
    raw = parsed.get("lastFlowReadAtEpoch", 0)
    if isinstance(raw, (int, float)):
        value = int(raw)
except Exception:
    pass
print(value)
PY
)
  fi
fi
[ -n "$LAST_FLOW_READ_AT" ] || LAST_FLOW_READ_AT=0

stage_index() {
  case "$1" in
    brainstorm) echo 1 ;;
    scope) echo 2 ;;
    design) echo 3 ;;
    spec) echo 4 ;;
    plan) echo 5 ;;
    test) echo 6 ;;
    build) echo 7 ;;
    review) echo 8 ;;
    ship) echo 9 ;;
    *) echo 0 ;;
  esac
}

is_mutating_tool() {
  case "$1" in
    write|edit|multiedit|multi_edit|delete|applypatch|apply_patch) return 0 ;;
    *) return 1 ;;
  esac
}

is_preimplementation_stage() {
  case "$1" in
    brainstorm|scope|design|spec|plan) return 0 ;;
    *) return 1 ;;
  esac
}

detect_target_stage() {
  local text="$1"
  for stage in brainstorm scope design spec plan test build review ship; do
    if printf '%s' "$text" | grep -Eq "(/cc-$stage|cc-$stage)\\b"; then
      printf '%s' "$stage"
      return 0
    fi
  done
  printf ''
  return 0
}

TARGET_STAGE=$(detect_target_stage "$PAYLOAD_LOWER")
if [ -n "$TARGET_STAGE" ] && [ "$CURRENT_STAGE" != "none" ]; then
  CURRENT_IDX=$(stage_index "$CURRENT_STAGE")
  TARGET_IDX=$(stage_index "$TARGET_STAGE")
  if [ "$CURRENT_IDX" -gt 0 ] && [ "$TARGET_IDX" -gt 0 ]; then
    if [ "$TARGET_IDX" -gt $((CURRENT_IDX + 1)) ]; then
      REASONS="stage_jump_\${CURRENT_STAGE}_to_\${TARGET_STAGE}"
    fi
  fi
fi

if is_preimplementation_stage "$CURRENT_STAGE" && is_mutating_tool "$TOOL_LOWER"; then
  if ! printf '%s' "$PAYLOAD_LOWER" | grep -Eq '\.cclaw/'; then
    if [ -n "$REASONS" ]; then
      REASONS="$REASONS,implementation_write_before_\${CURRENT_STAGE}_completion"
    else
      REASONS="implementation_write_before_\${CURRENT_STAGE}_completion"
    fi
  fi
fi

if [ -n "$TARGET_STAGE" ]; then
  if [ "$LAST_FLOW_READ_AT" -le 0 ] || [ "$NOW_EPOCH" -le 0 ] || [ $((NOW_EPOCH - LAST_FLOW_READ_AT)) -gt "$MAX_FLOW_READ_AGE_SEC" ]; then
    if [ -n "$REASONS" ]; then
      REASONS="$REASONS,stage_invocation_without_recent_flow_read"
    else
      REASONS="stage_invocation_without_recent_flow_read"
    fi
  fi
fi

SHOULD_RECORD_FLOW_READ=0
case "$TOOL_LOWER" in
  read|readfile|open|view|cat) SHOULD_RECORD_FLOW_READ=1 ;;
esac

if [ "$SHOULD_RECORD_FLOW_READ" -eq 1 ] && printf '%s' "$PAYLOAD_LOWER" | grep -Eq '\.cclaw/state/flow-state\.json'; then
  TMP_STATE_FILE="$GUARD_STATE_FILE.tmp.$$"
  if command -v jq >/dev/null 2>&1 && [ -f "$GUARD_STATE_FILE" ]; then
    jq --arg ts "$TS" --argjson epoch "$NOW_EPOCH" '
      .lastFlowReadAt = $ts
      | .lastFlowReadAtEpoch = $epoch
    ' "$GUARD_STATE_FILE" > "$TMP_STATE_FILE" 2>/dev/null || true
  elif command -v python3 >/dev/null 2>&1; then
    python3 - "$GUARD_STATE_FILE" "$TMP_STATE_FILE" "$TS" "$NOW_EPOCH" <<'PY'
import json
import sys
from pathlib import Path
source = Path(sys.argv[1])
target = Path(sys.argv[2])
ts = sys.argv[3]
epoch = int(float(sys.argv[4])) if sys.argv[4] else 0
payload = {}
if source.exists():
    try:
        raw = json.loads(source.read_text(encoding="utf-8"))
        if isinstance(raw, dict):
            payload.update(raw)
    except Exception:
        pass
payload["lastFlowReadAt"] = ts
payload["lastFlowReadAtEpoch"] = epoch
target.write_text(json.dumps(payload, indent=2) + "\\n", encoding="utf-8")
PY
  fi
  if [ -s "$TMP_STATE_FILE" ]; then
    mv "$TMP_STATE_FILE" "$GUARD_STATE_FILE" 2>/dev/null || rm -f "$TMP_STATE_FILE" 2>/dev/null || true
  else
    printf '{\\n  "lastFlowReadAt": "%s",\\n  "lastFlowReadAtEpoch": %s\\n}\\n' "$TS" "$NOW_EPOCH" > "$GUARD_STATE_FILE" 2>/dev/null || true
  fi
fi

if [ -n "$REASONS" ]; then
  NOTE="Cclaw workflow guard: detected potential flow violation (\${REASONS}). Re-read ${RUNTIME_ROOT}/state/flow-state.json, avoid source edits before build/test stages, and continue from current stage ordering."
  if command -v jq >/dev/null 2>&1; then
    ENTRY=$(jq -n -c \
      --arg ts "$TS" \
      --arg tool "$TOOL" \
      --arg stage "$CURRENT_STAGE" \
      --arg target "$TARGET_STAGE" \
      --arg reasons "$REASONS" \
      --arg note "$NOTE" \
      '{ts:$ts,tool:$tool,currentStage:$stage,targetStage:$target,reasons:($reasons|split(",")),note:$note}' 2>/dev/null || echo "")
  else
    ENTRY=""
  fi
  if [ -n "$ENTRY" ]; then
    printf '%s\n' "$ENTRY" >> "$GUARD_LOG" 2>/dev/null || true
  fi
  SHOULD_BLOCK="false"
  if printf '%s' "$REASONS" | grep -Eq 'implementation_write_before_'; then
    SHOULD_BLOCK="true"
  fi
  if [ "$WORKFLOW_GUARD_MODE" = "strict" ] || [ "$SHOULD_BLOCK" = "true" ]; then
    printf '[cclaw] %s (blocked by workflow guard)\n' "$NOTE" >&2
    exit 1
  fi
  printf '[cclaw] %s\n' "$NOTE" >&2
fi

exit 0
`;
}

export function observeScript(): string {
  return `#!/usr/bin/env bash
# cclaw observe hook — generated by cclaw sync
# Captures PreToolUse/PostToolUse events to ${RUNTIME_ROOT}/observations.jsonl
# Reads hook JSON from stdin, extracts tool + truncated I/O, appends JSONL.
# Always exits 0 to never block the agent.
set -uo pipefail

# Phase: "pre" or "post" passed as $1 by the hook runner
PHASE="\${1:-post}"

${RUNTIME_SHELL_DETECT_ROOT}

OBS_FILE="$ROOT/${RUNTIME_ROOT}/observations.jsonl"
STATE_FILE="$ROOT/${RUNTIME_ROOT}/state/flow-state.json"
ACTIVITY_FILE="$ROOT/${RUNTIME_ROOT}/state/stage-activity.jsonl"
LOCK_DIR="$ROOT/${RUNTIME_ROOT}/state/.observe.lock"
MAX_LEN=2000

# Guard: skip if disabled or observations dir missing
[ -f "$ROOT/${RUNTIME_ROOT}/.observe-disabled" ] && exit 0
[ -d "$ROOT/${RUNTIME_ROOT}" ] || exit 0
mkdir -p "$ROOT/${RUNTIME_ROOT}/state" 2>/dev/null || true

escape_json() {
  local str="$1"
  str=\${str//\\\\/\\\\\\\\}
  str=\${str//\\"/\\\\\\"}
  str=\${str//$'\\t'/\\\\t}
  str=\${str//$'\\n'/\\\\n}
  printf '%s' "$str"
}

acquire_lock() {
  local attempt=0
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -ge 200 ]; then
      return 1
    fi
    sleep 0.02
  done
  return 0
}

release_lock() {
  rmdir "$LOCK_DIR" 2>/dev/null || true
}

rotate_file() {
  local file_path="$1"
  local keep_lines="$2"
  if [ ! -f "$file_path" ]; then
    return
  fi
  local line_count
  line_count=$(wc -l < "$file_path" 2>/dev/null | tr -d ' ')
  if [ -z "$line_count" ]; then
    return
  fi
  if [ "$line_count" -gt $((keep_lines * 2)) ]; then
    local tmp_path="\${file_path}.tmp.$$"
    if tail -n "$keep_lines" "$file_path" > "$tmp_path" 2>/dev/null; then
      mv "$tmp_path" "$file_path" 2>/dev/null || rm -f "$tmp_path" 2>/dev/null || true
    fi
  fi
}

sync_run_artifacts() {
  if [ "$PHASE" != "post" ]; then
    return
  fi
  [ -n "$ACTIVE_RUN" ] || return
  if [ "$ACTIVE_RUN" = "none" ]; then
    return
  fi

  local tool_lower
  tool_lower=$(printf '%s' "$TOOL" | tr '[:upper:]' '[:lower:]')
  case "$tool_lower" in
    write|edit|multiedit|multi_edit|delete|applypatch|runcommand|shell|terminal|execcommand) ;;
    *) return ;;
  esac

  local active_dir="$ROOT/${RUNTIME_ROOT}/artifacts"
  local run_dir="$ROOT/${RUNTIME_ROOT}/runs/$ACTIVE_RUN/artifacts"
  [ -d "$active_dir" ] || return
  mkdir -p "$run_dir" 2>/dev/null || return

  for run_file in "$run_dir"/*; do
    [ -e "$run_file" ] || continue
    [ -f "$run_file" ] || continue
    local base_name
    base_name=$(basename "$run_file")
    local active_file="$active_dir/$base_name"
    if [ ! -f "$active_file" ]; then
      rm -f "$run_file" 2>/dev/null || true
      continue
    fi
    if command -v cmp >/dev/null 2>&1 && cmp -s "$active_file" "$run_file" 2>/dev/null; then
      continue
    fi
    cp "$active_file" "$run_file" 2>/dev/null || true
  done

  for active_file in "$active_dir"/*; do
    [ -e "$active_file" ] || continue
    [ -f "$active_file" ] || continue
    local base_name
    base_name=$(basename "$active_file")
    local run_file="$run_dir/$base_name"
    if [ -f "$run_file" ] && command -v cmp >/dev/null 2>&1 && cmp -s "$active_file" "$run_file" 2>/dev/null; then
      continue
    fi
    cp "$active_file" "$run_file" 2>/dev/null || true
  done
}

# Read stdin (hook JSON)
INPUT=$(cat 2>/dev/null || echo '{}')
[ -z "$INPUT" ] && exit 0

# Extract fields from hook payload.
TOOL="unknown"
PAYLOAD=""
if command -v jq >/dev/null 2>&1; then
  TOOL=$(echo "$INPUT" | jq -r '.tool_name // .tool // "unknown"' 2>/dev/null || echo "unknown")
  if [ "$PHASE" = "pre" ]; then
    PAYLOAD=$(echo "$INPUT" | jq -r --arg max "$MAX_LEN" '.tool_input // .input // {} | tostring | .[0:($max|tonumber)]' 2>/dev/null || echo "")
  else
    PAYLOAD=$(echo "$INPUT" | jq -r --arg max "$MAX_LEN" '.tool_response // .tool_output // .output // .result_json // "" | tostring | .[0:($max|tonumber)]' 2>/dev/null || echo "")
  fi
else
  TOOL=$(printf '%s' "$INPUT" | sed -n -E 's/.*"tool_name"[[:space:]]*:[[:space:]]*"([^"]+)".*/\\1/p' | head -1)
  if [ -z "$TOOL" ]; then
    TOOL=$(printf '%s' "$INPUT" | sed -n -E 's/.*"tool"[[:space:]]*:[[:space:]]*"([^"]+)".*/\\1/p' | head -1)
  fi
  [ -n "$TOOL" ] || TOOL="unknown"
  PAYLOAD=$(printf '%s' "$INPUT" | cut -c1-"$MAX_LEN")
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
STAGE="none"
ACTIVE_RUN="none"
if [ -f "$STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    STAGE=$(jq -r '.currentStage // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    ACTIVE_RUN=$(jq -r '.activeRunId // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
  elif command -v python3 >/dev/null 2>&1; then
    STAGE=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

stage = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("currentStage")
    if isinstance(value, str) and value:
        stage = value
except Exception:
    pass
print(stage)
PY
)
    ACTIVE_RUN=$(python3 - "$STATE_FILE" <<'PY'
import json
import sys

run_id = "none"
try:
    with open(sys.argv[1], "r", encoding="utf-8") as fh:
        data = json.load(fh)
    value = data.get("activeRunId")
    if isinstance(value, str) and value:
        run_id = value
except Exception:
    pass
print(run_id)
PY
)
  else
    STAGE=$(grep -o '"currentStage"[[:space:]]*:[[:space:]]*"[^"]*"' "$STATE_FILE" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/' || echo "none")
    ACTIVE_RUN=$(grep -o '"activeRunId"[[:space:]]*:[[:space:]]*"[^"]*"' "$STATE_FILE" 2>/dev/null | head -1 | sed 's/.*"\\([^"]*\\)"$/\\1/' || echo "none")
  fi
fi

# Skip observation of cclaw hooks to avoid recursion
case "$TOOL" in
  cclaw*|*cclaw-hook*|observe) exit 0 ;;
esac

if [ "$PHASE" = "pre" ]; then
  EVENT="tool_start"
else
  EVENT="tool_complete"
fi

# Scrub potential secrets (env vars, tokens, keys) — BSD/macOS sed compatible
PAYLOAD=$(echo "$PAYLOAD" | sed -E 's/[A-Za-z0-9_]*([Kk][Ee][Yy]|[Tt][Oo][Kk][Ee][Nn]|[Ss][Ee][Cc][Rr][Ee][Tt]|[Pp][Aa][Ss][Ss][Ww][Oo][Rr][Dd]|[Cc][Rr][Ee][Dd][Ee][Nn][Tt][Ii][Aa][Ll])[A-Za-z0-9_]*[=:][^ ",}]+/[REDACTED]/g' 2>/dev/null || echo "$PAYLOAD")

# Build JSONL lines.
if command -v jq >/dev/null 2>&1; then
  EVENT_JSON=$(jq -n -c \\
    --arg ts "$TS" \\
    --arg event "$EVENT" \\
    --arg tool "$TOOL" \\
    --arg phase "$PHASE" \\
    --arg stage "$STAGE" \\
    --arg runId "$ACTIVE_RUN" \\
    --arg payload "$PAYLOAD" \\
    '{ts:$ts,event:$event,tool:$tool,phase:$phase,stage:$stage,runId:$runId,data:$payload}' 2>/dev/null || echo "")
  ACTIVITY_JSON=$(jq -n -c \\
    --arg ts "$TS" \\
    --arg event "$EVENT" \\
    --arg tool "$TOOL" \\
    --arg phase "$PHASE" \\
    --arg stage "$STAGE" \\
    --arg runId "$ACTIVE_RUN" \\
    '{ts:$ts,event:$event,tool:$tool,phase:$phase,stage:$stage,runId:$runId}' 2>/dev/null || echo "")
else
  EVENT_JSON=$(printf '{"ts":"%s","event":"%s","tool":"%s","phase":"%s","stage":"%s","runId":"%s","data":"%s"}' \\
    "$(escape_json "$TS")" \\
    "$(escape_json "$EVENT")" \\
    "$(escape_json "$TOOL")" \\
    "$(escape_json "$PHASE")" \\
    "$(escape_json "$STAGE")" \\
    "$(escape_json "$ACTIVE_RUN")" \\
    "$(escape_json "$PAYLOAD")")
  ACTIVITY_JSON=$(printf '{"ts":"%s","event":"%s","tool":"%s","phase":"%s","stage":"%s","runId":"%s"}' \\
    "$(escape_json "$TS")" \\
    "$(escape_json "$EVENT")" \\
    "$(escape_json "$TOOL")" \\
    "$(escape_json "$PHASE")" \\
    "$(escape_json "$STAGE")" \\
    "$(escape_json "$ACTIVE_RUN")")
fi

if acquire_lock; then
  trap release_lock EXIT INT TERM
  [ -n "$EVENT_JSON" ] && printf '%s\\n' "$EVENT_JSON" >> "$OBS_FILE" 2>/dev/null
  [ -n "$ACTIVITY_JSON" ] && printf '%s\\n' "$ACTIVITY_JSON" >> "$ACTIVITY_FILE" 2>/dev/null
  rotate_file "$OBS_FILE" 4000
  rotate_file "$ACTIVITY_FILE" 3000
  release_lock
  trap - EXIT INT TERM
fi

sync_run_artifacts

exit 0
`;
}

export function contextMonitorScript(): string {
  return `#!/usr/bin/env bash
# cclaw context monitor hook — generated by cclaw sync
# Advisory-only context pressure warnings (best effort).
set -uo pipefail

HARNESS="codex"
if [ -n "\${CLAUDE_PROJECT_DIR:-}" ]; then
  HARNESS="claude"
elif [ -n "\${CURSOR_PROJECT_DIR:-}" ] || [ -n "\${CURSOR_PROJECT_ROOT:-}" ]; then
  HARNESS="cursor"
elif [ -n "\${OPENCODE_PROJECT_DIR:-}" ] || [ -n "\${OPENCODE_PROJECT_ROOT:-}" ]; then
  HARNESS="opencode"
fi

${RUNTIME_SHELL_DETECT_ROOT}

STATE_DIR="$ROOT/${RUNTIME_ROOT}/state"
MONITOR_STATE="$STATE_DIR/context-monitor.json"
WARNINGS_FILE="$STATE_DIR/context-warnings.jsonl"
mkdir -p "$STATE_DIR" 2>/dev/null || true

INPUT=$(cat 2>/dev/null || echo '{}')
[ -n "$INPUT" ] || exit 0

REMAINING_PERCENT=""
if command -v python3 >/dev/null 2>&1; then
  REMAINING_PERCENT=$(INPUT_JSON="$INPUT" python3 - <<'PY'
import json
import os
from typing import Any

raw = os.environ.get("INPUT_JSON", "{}")
try:
    payload = json.loads(raw)
except Exception:
    print("")
    raise SystemExit(0)

def pick(path: list[str]) -> Any:
    node: Any = payload
    for key in path:
        if not isinstance(node, dict):
            return None
        node = node.get(key)
    return node

def as_percent(value: Any, invert: bool = False):
    if not isinstance(value, (int, float)):
        return None
    number = float(value)
    if number <= 1.0:
        number *= 100.0
    if invert:
        number = 100.0 - number
    if number < 0:
        number = 0.0
    if number > 100:
        number = 100.0
    return number

candidates = [
    (["context", "remaining_percent"], False),
    (["context", "remainingPercent"], False),
    (["context_usage", "remaining_percent"], False),
    (["context_usage", "remainingPercent"], False),
    (["contextUsage", "remainingPercent"], False),
    (["context_window", "remaining_percent"], False),
    (["remaining_context_percent"], False),
    (["remainingContextPercent"], False),
    (["remaining_context_ratio"], False),
    (["remainingContextRatio"], False),
    (["context", "used_percent"], True),
    (["context", "usedPercent"], True),
    (["context_usage", "used_percent"], True),
    (["context_usage", "usedPercent"], True),
    (["contextUsage", "usedPercent"], True),
    (["context_window", "used_ratio"], True),
    (["context_window", "usedRatio"], True),
]

for path, invert in candidates:
    value = pick(path)
    percent = as_percent(value, invert=invert)
    if percent is not None:
        print(f"{percent:.2f}")
        raise SystemExit(0)

print("")
PY
)
fi

[ -n "$REMAINING_PERCENT" ] || exit 0

BAND="none"
if awk "BEGIN { exit !($REMAINING_PERCENT <= 20) }"; then
  BAND="critical"
elif awk "BEGIN { exit !($REMAINING_PERCENT <= 35) }"; then
  BAND="warning"
fi

TTL_SECONDS_RAW="\${CCLAW_CONTEXT_MONITOR_TTL_SEC:-900}"
if printf '%s' "$TTL_SECONDS_RAW" | grep -Eq '^[0-9]+$'; then
  TTL_SECONDS="$TTL_SECONDS_RAW"
else
  TTL_SECONDS="900"
fi

LAST_BAND="none"
LAST_ADVISORY_BAND="none"
LAST_ADVISORY_AT=""
LAST_ADVISORY_EPOCH="0"
if [ -f "$MONITOR_STATE" ]; then
  if command -v jq >/dev/null 2>&1; then
    LAST_BAND=$(jq -r '.lastBand // "none"' "$MONITOR_STATE" 2>/dev/null || echo "none")
    LAST_ADVISORY_BAND=$(jq -r '.lastAdvisoryBand // .lastBand // "none"' "$MONITOR_STATE" 2>/dev/null || echo "none")
    LAST_ADVISORY_AT=$(jq -r '.lastAdvisoryAt // ""' "$MONITOR_STATE" 2>/dev/null || echo "")
    LAST_ADVISORY_EPOCH=$(jq -r 'try ((.lastAdvisoryAt // "" | fromdateiso8601)) catch 0' "$MONITOR_STATE" 2>/dev/null || echo "0")
  elif command -v python3 >/dev/null 2>&1; then
    STATE_META=$(python3 - "$MONITOR_STATE" <<'PY'
import json
import sys
try:
    with open(sys.argv[1], "r", encoding="utf-8") as handle:
        value = json.load(handle)
    last_band = value.get("lastBand")
    if not isinstance(last_band, str):
        last_band = "none"
    advisory_band = value.get("lastAdvisoryBand")
    if not isinstance(advisory_band, str):
        advisory_band = last_band
    advisory_at = value.get("lastAdvisoryAt")
    if not isinstance(advisory_at, str):
        advisory_at = ""
    advisory_epoch = 0
    if advisory_at:
        try:
            from datetime import datetime
            normalized = advisory_at.replace("Z", "+00:00")
            advisory_epoch = int(datetime.fromisoformat(normalized).timestamp())
        except Exception:
            advisory_epoch = 0
    print(f"{last_band}|{advisory_band}|{advisory_at}|{advisory_epoch}")
except Exception:
    print("none|none||0")
PY
)
    LAST_BAND=$(printf '%s' "$STATE_META" | cut -d'|' -f1)
    LAST_ADVISORY_BAND=$(printf '%s' "$STATE_META" | cut -d'|' -f2)
    LAST_ADVISORY_AT=$(printf '%s' "$STATE_META" | cut -d'|' -f3)
    LAST_ADVISORY_EPOCH=$(printf '%s' "$STATE_META" | cut -d'|' -f4)
  fi
fi

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
NOW_EPOCH=$(date +%s 2>/dev/null || echo "0")
if ! printf '%s' "$LAST_ADVISORY_EPOCH" | grep -Eq '^[0-9]+$'; then
  LAST_ADVISORY_EPOCH="0"
fi

SHOULD_EMIT="false"
if [ "$BAND" != "none" ]; then
  if [ "$BAND" != "$LAST_ADVISORY_BAND" ]; then
    SHOULD_EMIT="true"
  elif [ "$TTL_SECONDS" -eq 0 ]; then
    SHOULD_EMIT="true"
  else
    ELAPSED=$((NOW_EPOCH - LAST_ADVISORY_EPOCH))
    if [ "$ELAPSED" -ge "$TTL_SECONDS" ]; then
      SHOULD_EMIT="true"
    fi
  fi
fi

NEXT_ADVISORY_BAND="$LAST_ADVISORY_BAND"
NEXT_ADVISORY_AT="$LAST_ADVISORY_AT"
if [ "$SHOULD_EMIT" = "true" ]; then
  NOTE="Cclaw advisory: context remaining is \${REMAINING_PERCENT}% (\${BAND}). Consider checkpointing or compacting soon."
  if command -v jq >/dev/null 2>&1; then
    ENTRY=$(jq -n -c \
      --arg ts "$TS" \
      --arg harness "$HARNESS" \
      --arg band "$BAND" \
      --arg remaining "$REMAINING_PERCENT" \
      --arg note "$NOTE" \
      '{ts:$ts,harness:$harness,band:$band,remainingPercent:($remaining|tonumber),note:$note}' 2>/dev/null || echo "")
  else
    ENTRY=$(printf '{"ts":"%s","harness":"%s","band":"%s","remainingPercent":"%s","note":"%s"}' "$TS" "$HARNESS" "$BAND" "$REMAINING_PERCENT" "$NOTE")
  fi

  if [ -n "$ENTRY" ]; then
    printf '%s\n' "$ENTRY" >> "$WARNINGS_FILE" 2>/dev/null || true
  fi
  printf '[cclaw] %s\n' "$NOTE" >&2
  NEXT_ADVISORY_BAND="$BAND"
  NEXT_ADVISORY_AT="$TS"
fi

TMP_STATE="$MONITOR_STATE.tmp.$$"
if command -v jq >/dev/null 2>&1; then
  jq -n \
    --arg ts "$TS" \
    --arg band "$BAND" \
    --arg advisoryBand "$NEXT_ADVISORY_BAND" \
    --arg advisoryAt "$NEXT_ADVISORY_AT" \
    --arg remaining "$REMAINING_PERCENT" \
    --arg harness "$HARNESS" \
    '{lastUpdated:$ts,lastBand:$band,lastRemainingPercent:($remaining|tonumber),harness:$harness,lastAdvisoryBand:$advisoryBand,lastAdvisoryAt:$advisoryAt}' > "$TMP_STATE" 2>/dev/null || true
else
  printf '{\n  "lastUpdated": "%s",\n  "lastBand": "%s",\n  "lastRemainingPercent": %s,\n  "harness": "%s",\n  "lastAdvisoryBand": "%s",\n  "lastAdvisoryAt": "%s"\n}\n' \
    "$TS" "$BAND" "$REMAINING_PERCENT" "$HARNESS" "$NEXT_ADVISORY_BAND" "$NEXT_ADVISORY_AT" > "$TMP_STATE" 2>/dev/null || true
fi
if [ -s "$TMP_STATE" ]; then
  mv "$TMP_STATE" "$MONITOR_STATE" 2>/dev/null || rm -f "$TMP_STATE" 2>/dev/null || true
fi

exit 0
`;
}

export function summarizeObservationsRuntimeModule(): string {
  return `#!/usr/bin/env node
import fs from "node:fs";

const [, , observationsPath, learningsPath, timestampArg] = process.argv;

function readTailText(filePath, maxBytes = 524288) {
  let fd;
  try {
    fd = fs.openSync(filePath, "r");
    const size = fs.fstatSync(fd).size;
    if (!Number.isFinite(size) || size <= 0) return "";
    const bytesToRead = Math.min(size, maxBytes);
    const buffer = Buffer.allocUnsafe(bytesToRead);
    fs.readSync(fd, buffer, 0, bytesToRead, size - bytesToRead);
    return buffer.toString("utf8");
  } catch {
    return "";
  } finally {
    if (fd !== undefined) {
      try {
        fs.closeSync(fd);
      } catch {
        // ignore
      }
    }
  }
}

function readTailLines(filePath, maxLines, maxBytes = 524288) {
  const raw = readTailText(filePath, maxBytes).trim();
  if (!raw) return [];
  return raw.split(/\\r?\\n/).slice(-maxLines);
}

function writeAppend(filePath, lines) {
  if (!lines.length) return;
  try {
    fs.appendFileSync(filePath, lines.join("\\n") + "\\n", "utf8");
  } catch {
    // advisory-only runtime path
  }
}

function parseLine(line) {
  const trimmed = line.trim();
  if (!trimmed) return null;
  try {
    const parsed = JSON.parse(trimmed);
    if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
      return parsed;
    }
    return null;
  } catch {
    return null;
  }
}

function toText(value) {
  if (typeof value === "string") return value;
  try {
    return JSON.stringify(value);
  } catch {
    return "";
  }
}

const keyPattern = /^[A-Za-z0-9][A-Za-z0-9._-]*$/;
const errorPattern = /(error|fail|timeout|exception)/i;
const timestamp = timestampArg || new Date().toISOString();
const observationLines = readTailLines(observationsPath, 4000, 1024 * 1024);
const learningLines = readTailLines(learningsPath, 6000, 1024 * 1024);

const observations = observationLines
  .map(parseLine)
  .filter(Boolean);

if (observations.length < 5) {
  process.exit(0);
}

const toolUsage = new Map();
const toolErrors = new Map();
const stageErrors = new Map();
const longPayload = new Map();

for (const obs of observations) {
  const toolRaw = typeof obs.tool === "string" ? obs.tool : "unknown";
  const stageRaw = typeof obs.stage === "string" ? obs.stage : "none";
  const tool = toolRaw.trim().replace(/[^A-Za-z0-9._-]+/g, "-") || "unknown";
  const stage = stageRaw.trim().replace(/[^A-Za-z0-9._-]+/g, "-") || "none";
  const payload = toText(obs.data);
  toolUsage.set(tool, (toolUsage.get(tool) || 0) + 1);
  if (payload.length >= 1500) {
    longPayload.set(tool, (longPayload.get(tool) || 0) + 1);
  }
  if (obs.event === "tool_complete" && errorPattern.test(payload)) {
    toolErrors.set(tool, (toolErrors.get(tool) || 0) + 1);
    stageErrors.set(stage, (stageErrors.get(stage) || 0) + 1);
  }
}

const candidates = [];

for (const [tool, errors] of toolErrors.entries()) {
  if (errors < 3) continue;
  candidates.push({
    ts: timestamp,
    skill: "observation",
    type: "pitfall",
    key: "frequent-errors-" + tool,
    insight: "Tool " + tool + " produced " + errors + " error-like completions in a single session; add a preflight checklist before using it.",
    confidence: Math.min(9, 4 + Math.floor(errors / 2)),
    source: "observed"
  });
}

for (const [tool, total] of toolUsage.entries()) {
  if (total < 8) continue;
  const errors = toolErrors.get(tool) || 0;
  if (errors > Math.max(1, Math.floor(total * 0.15))) continue;
  candidates.push({
    ts: timestamp,
    skill: "observation",
    type: "pattern",
    key: "reliable-tool-" + tool,
    insight: "Tool " + tool + " was used " + total + " times with low failure rate; prefer it as a first option for similar tasks.",
    confidence: Math.min(8, 3 + Math.floor(total / 3)),
    source: "observed"
  });
}

for (const [stage, errors] of stageErrors.entries()) {
  if (stage === "none" || errors < 4) continue;
  candidates.push({
    ts: timestamp,
    skill: "observation",
    type: "pitfall",
    key: "stage-hotspot-" + stage,
    insight: "Stage " + stage + " produced " + errors + " error-like tool completions in one session; add stage-specific checks before execution.",
    confidence: Math.min(8, 3 + Math.floor(errors / 2)),
    source: "observed"
  });
}

for (const [tool, count] of longPayload.entries()) {
  if (count < 3) continue;
  candidates.push({
    ts: timestamp,
    skill: "observation",
    type: "preference",
    key: "truncate-heavy-payloads-" + tool,
    insight: "Tool " + tool + " produced large payloads repeatedly; summarize outputs earlier to avoid context pressure.",
    confidence: Math.min(7, 3 + Math.floor(count / 2)),
    source: "observed"
  });
}

const toolFilePathCounts = new Map();
function extractFilePathsFromPayload(dataVal) {
  const text = toText(dataVal);
  if (!text) return [];
  const found = [];
  const seen = new Set();
  try {
    const obj = JSON.parse(text);
    if (obj && typeof obj === "object" && !Array.isArray(obj)) {
      const keys = [
        "path",
        "file_path",
        "filePath",
        "target_file",
        "file",
        "filepath",
        "old_path",
        "new_path",
        "targetPath"
      ];
      for (const k of keys) {
        if (!Object.prototype.hasOwnProperty.call(obj, k)) continue;
        const v = obj[k];
        if (typeof v === "string" && v.length > 1 && (v.includes("/") || v.includes("\\\\"))) {
          const norm = v.replace(/\\\\/g, "/").replace(/\\/+/g, "/");
          if (!seen.has(norm)) {
            seen.add(norm);
            found.push(norm);
          }
        }
      }
    }
  } catch {
    // ignore JSON parse errors
  }
  return found;
}

for (const obs of observations) {
  const toolRaw = typeof obs.tool === "string" ? obs.tool : "unknown";
  const tool = toolRaw.trim().replace(/[^A-Za-z0-9._-]+/g, "-") || "unknown";
  for (const filePath of extractFilePathsFromPayload(obs.data)) {
    const pairKey = JSON.stringify([tool, filePath]);
    toolFilePathCounts.set(pairKey, (toolFilePathCounts.get(pairKey) || 0) + 1);
  }
}

for (const [pairKey, uses] of toolFilePathCounts.entries()) {
  if (uses < 5) continue;
  let tool = "unknown";
  let filePath = "";
  try {
    const parsed = JSON.parse(pairKey);
    if (!Array.isArray(parsed) || parsed.length !== 2) continue;
    if (typeof parsed[0] === "string") tool = parsed[0];
    if (typeof parsed[1] === "string") filePath = parsed[1];
  } catch {
    continue;
  }
  if (!filePath) continue;
  const parts = filePath.split(/[/\\\\]/);
  let basename = parts[parts.length - 1] || filePath;
  basename = basename.trim().replace(/[^A-Za-z0-9._-]+/g, "-") || "file";
  const key = "file-affinity-" + tool + "-" + basename;
  if (!keyPattern.test(key)) continue;
  candidates.push({
    ts: timestamp,
    skill: "observation",
    type: "pattern",
    key: key,
    insight:
      "Tool " +
      tool +
      " frequently targets " +
      filePath +
      "; consider pre-loading it for this stage.",
    confidence: 4,
    source: "observed"
  });
}

if (observations.length >= 10) {
  const stages = new Set();
  for (const obs of observations) {
    const s = typeof obs.stage === "string" ? obs.stage.trim() : "none";
    stages.add(s || "none");
  }
  if (stages.size === 1) {
    const onlyStage = [...stages][0];
    if (onlyStage && onlyStage !== "none") {
      const stageSan = onlyStage.replace(/[^A-Za-z0-9._-]+/g, "-") || "none";
      const times = [];
      for (const obs of observations) {
        if (typeof obs.ts === "string") {
          const ms = Date.parse(obs.ts);
          if (!Number.isNaN(ms)) times.push(ms);
        }
      }
      times.sort((a, b) => a - b);
      if (times.length >= 2) {
        const spanMin = Math.max(
          1,
          Math.round((times[times.length - 1] - times[0]) / 60000)
        );
        const M = observations.length;
        const velKey = "stage-velocity-" + stageSan;
        if (keyPattern.test(velKey)) {
          candidates.push({
            ts: timestamp,
            skill: "observation",
            type: "operational",
            key: velKey,
            insight:
              "Stage " +
              onlyStage +
              " took approximately " +
              spanMin +
              " minutes with " +
              M +
              " tool calls.",
            confidence: 3,
            source: "observed"
          });
        }
      }
    }
  }
}

const valid = [];
const bestCandidate = new Map();
for (const candidate of candidates) {
  if (typeof candidate.key !== "string" || !keyPattern.test(candidate.key)) continue;
  if (typeof candidate.insight !== "string" || candidate.insight.trim().length < 16) continue;
  if (!Number.isInteger(candidate.confidence) || candidate.confidence < 1 || candidate.confidence > 10) continue;
  const token = candidate.key + ":" + candidate.type;
  const current = bestCandidate.get(token);
  if (!current || candidate.confidence > current.confidence) {
    bestCandidate.set(token, candidate);
  }
}
for (const value of bestCandidate.values()) {
  valid.push(value);
}

const bestExisting = new Map();
for (const line of learningLines) {
  const parsed = parseLine(line);
  if (!parsed) continue;
  if (typeof parsed.key !== "string" || typeof parsed.type !== "string") continue;
  if (typeof parsed.confidence !== "number" || !Number.isInteger(parsed.confidence)) continue;
  const token = parsed.key + ":" + parsed.type;
  const current = bestExisting.get(token) || 0;
  if (parsed.confidence > current) {
    bestExisting.set(token, parsed.confidence);
  }
}

const appended = [];
for (const candidate of valid) {
  const token = candidate.key + ":" + candidate.type;
  const current = bestExisting.get(token) || 0;
  if (candidate.confidence > current) {
    appended.push(JSON.stringify(candidate));
    bestExisting.set(token, candidate.confidence);
  }
}

writeAppend(learningsPath, appended);
process.exit(0);
`;
}

export function summarizeObservationsScript(): string {
  return `#!/usr/bin/env bash
# cclaw stop-summarize hook — generated by cclaw sync
# Analyzes recent observations and creates learnings entries.
# Runs as part of the stop hook chain.
set -uo pipefail

${RUNTIME_SHELL_DETECT_ROOT}

OBS_FILE="$ROOT/${RUNTIME_ROOT}/observations.jsonl"
LEARNINGS_FILE="$ROOT/${RUNTIME_ROOT}/learnings.jsonl"
ACTIVITY_FILE="$ROOT/${RUNTIME_ROOT}/state/stage-activity.jsonl"
LOCK_DIR="$ROOT/${RUNTIME_ROOT}/state/.observe.lock"
mkdir -p "$ROOT/${RUNTIME_ROOT}/state" 2>/dev/null || true
[ -f "$LEARNINGS_FILE" ] || : > "$LEARNINGS_FILE" 2>/dev/null || true

# Guard
[ -f "$OBS_FILE" ] || exit 0
[ -s "$OBS_FILE" ] || exit 0

acquire_lock() {
  local attempt=0
  while ! mkdir "$LOCK_DIR" 2>/dev/null; do
    attempt=$((attempt + 1))
    if [ "$attempt" -ge 200 ]; then
      return 1
    fi
    sleep 0.02
  done
  return 0
}

release_lock() {
  rmdir "$LOCK_DIR" 2>/dev/null || true
}

rotate_file() {
  local file_path="$1"
  local keep_lines="$2"
  if [ ! -f "$file_path" ]; then
    return
  fi
  local line_count
  line_count=$(wc -l < "$file_path" 2>/dev/null | tr -d ' ')
  if [ -z "$line_count" ]; then
    return
  fi
  if [ "$line_count" -gt $((keep_lines * 2)) ]; then
    local tmp_path="\${file_path}.tmp.$$"
    if tail -n "$keep_lines" "$file_path" > "$tmp_path" 2>/dev/null; then
      mv "$tmp_path" "$file_path" 2>/dev/null || rm -f "$tmp_path" 2>/dev/null || true
    fi
  fi
}

acquire_lock || exit 0
trap release_lock EXIT INT TERM

# Count observations in this session
OBS_COUNT=$(wc -l < "$OBS_FILE" 2>/dev/null | tr -d ' ')
[ "$OBS_COUNT" -lt 5 ] && exit 0

TS=$(date -u +"%Y-%m-%dT%H:%M:%SZ" 2>/dev/null || echo "")
RUNTIME_SUMMARIZER="$ROOT/${RUNTIME_ROOT}/hooks/summarize-observations.mjs"
if command -v node >/dev/null 2>&1 && [ -f "$RUNTIME_SUMMARIZER" ]; then
  node "$RUNTIME_SUMMARIZER" "$OBS_FILE" "$LEARNINGS_FILE" "$TS" >/dev/null 2>&1 || true
elif command -v python3 >/dev/null 2>&1; then
  python3 - "$OBS_FILE" "$LEARNINGS_FILE" "$TS" <<'PY' >/dev/null 2>&1
import json
import re
import sys
from collections import Counter
from pathlib import Path

obs_path = Path(sys.argv[1])
learnings_path = Path(sys.argv[2])
timestamp = sys.argv[3]

error_pattern = re.compile(r"(error|fail)", re.IGNORECASE)
key_pattern = re.compile(r"^[A-Za-z0-9][A-Za-z0-9._-]*$")

observations = []
for line in obs_path.read_text(encoding="utf-8").splitlines():
    line = line.strip()
    if not line:
        continue
    try:
        value = json.loads(line)
    except Exception:
        continue
    if isinstance(value, dict):
        observations.append(value)

if len(observations) < 5:
    raise SystemExit(0)

tool_counts: Counter[str] = Counter()
error_counts: Counter[str] = Counter()
stage_error_counts: Counter[str] = Counter()

for event in observations:
    tool = event.get("tool")
    if not isinstance(tool, str) or not tool:
        tool = "unknown"
    stage = event.get("stage")
    if not isinstance(stage, str) or not stage:
        stage = "none"

    tool_counts[tool] += 1

    payload = event.get("data")
    if isinstance(payload, str):
        payload_text = payload
    else:
        try:
            payload_text = json.dumps(payload, ensure_ascii=False)
        except Exception:
            payload_text = ""

    if event.get("event") == "tool_complete" and error_pattern.search(payload_text):
        error_counts[tool] += 1
        stage_error_counts[stage] += 1

candidates: list[dict[str, object]] = []
if error_counts:
    top_tool, top_count = error_counts.most_common(1)[0]
    if top_count >= 3:
        candidates.append({
            "ts": timestamp,
            "skill": "observation",
            "type": "pitfall",
            "key": f"frequent-errors-{top_tool}",
            "insight": f"Tool {top_tool} had {top_count} error-like outputs in one session; add a preflight checklist before using it.",
            "confidence": min(9, 4 + (top_count // 2)),
            "source": "observed"
        })

if tool_counts:
    top_tool, top_total = tool_counts.most_common(1)[0]
    if top_total >= 8 and error_counts.get(top_tool, 0) <= 1:
        candidates.append({
            "ts": timestamp,
            "skill": "observation",
            "type": "pattern",
            "key": f"reliable-tool-{top_tool}",
            "insight": f"Tool {top_tool} was used {top_total} times with low failure rate; prefer it as first option for similar tasks.",
            "confidence": min(8, 3 + (top_total // 3)),
            "source": "observed"
        })

if stage_error_counts:
    top_stage, top_stage_count = stage_error_counts.most_common(1)[0]
    if top_stage != "none" and top_stage_count >= 4:
        candidates.append({
            "ts": timestamp,
            "skill": "observation",
            "type": "pitfall",
            "key": f"stage-hotspot-{top_stage}",
            "insight": f"Stage {top_stage} produced {top_stage_count} error-like tool completions in one session; stage-specific guardrails are needed.",
            "confidence": min(8, 3 + (top_stage_count // 2)),
            "source": "observed"
        })

def is_valid(entry: dict[str, object]) -> bool:
    ts = entry.get("ts")
    key = entry.get("key")
    insight = entry.get("insight")
    conf = entry.get("confidence")
    typ = entry.get("type")
    source = entry.get("source")

    if not isinstance(ts, str) or not ts:
        return False
    if not isinstance(key, str) or not key_pattern.match(key):
        return False
    if not isinstance(insight, str) or len(insight.strip()) < 16:
        return False
    if not isinstance(conf, int) or conf < 1 or conf > 10:
        return False
    if typ not in {"pitfall", "pattern", "preference"}:
        return False
    if source not in {"observed", "user-stated"}:
        return False
    return True

best_existing: dict[str, int] = {}
if learnings_path.exists():
    for line in learnings_path.read_text(encoding="utf-8").splitlines():
        line = line.strip()
        if not line:
            continue
        try:
            entry = json.loads(line)
        except Exception:
            continue
        if not isinstance(entry, dict):
            continue
        key = entry.get("key")
        typ = entry.get("type")
        conf = entry.get("confidence")
        if isinstance(key, str) and isinstance(typ, str) and isinstance(conf, int):
            token = f"{key}:{typ}"
            best_existing[token] = max(best_existing.get(token, 0), conf)

appended: list[str] = []
with learnings_path.open("a", encoding="utf-8") as handle:
    for candidate in candidates:
        if not is_valid(candidate):
            continue
        token = f"{candidate['key']}:{candidate['type']}"
        confidence = int(candidate["confidence"])
        if confidence <= best_existing.get(token, 0):
            continue
        handle.write(json.dumps(candidate, ensure_ascii=False) + "\\n")
        best_existing[token] = confidence
        appended.append(str(candidate["key"]))

raise SystemExit(0)
PY
elif command -v jq >/dev/null 2>&1; then
  ERROR_PATTERNS=$(jq -r 'select(.event=="tool_complete") | select(.data | test("error|Error|ERROR|fail|Fail|FAIL"; "g")) | .tool' "$OBS_FILE" 2>/dev/null | sort | uniq -c | sort -rn | head -3)
  if [ -n "$ERROR_PATTERNS" ]; then
    TOP_ERROR_TOOL=$(echo "$ERROR_PATTERNS" | head -1 | awk '{print $2}')
    TOP_ERROR_COUNT=$(echo "$ERROR_PATTERNS" | head -1 | awk '{print $1}')
    if [ "$TOP_ERROR_COUNT" -ge 3 ]; then
      CANDIDATE=$(jq -n -c \\
        --arg ts "$TS" \\
        --arg tool "$TOP_ERROR_TOOL" \\
        --arg count "$TOP_ERROR_COUNT" \\
        '{ts:$ts,skill:"observation",type:"pitfall",key:("frequent-errors-"+$tool),insight:("Tool "+$tool+" had "+$count+" error-like outputs in one session; add a preflight checklist before using it."),confidence:(5 + (($count|tonumber) / 2 | floor)),source:"observed"}' 2>/dev/null || echo "")
      if [ -n "$CANDIDATE" ]; then
        CANDIDATE=$(echo "$CANDIDATE" | jq -c 'if .confidence > 10 then .confidence = 10 else . end' 2>/dev/null || echo "")
      fi

      if [ -n "$CANDIDATE" ]; then
        CANDIDATE_OK=$(echo "$CANDIDATE" | jq -r '
          (.ts|type=="string") and
          (.key|type=="string") and
          (.type|type=="string") and
          (.insight|type=="string" and (length >= 16)) and
          (.confidence|type=="number" and . >= 1 and . <= 10) and
          (.source|type=="string")
        ' 2>/dev/null || echo "false")
        if [ "$CANDIDATE_OK" = "true" ]; then
          CANDIDATE_KEY=$(echo "$CANDIDATE" | jq -r '.key' 2>/dev/null || echo "")
          CANDIDATE_TYPE=$(echo "$CANDIDATE" | jq -r '.type' 2>/dev/null || echo "")
          CANDIDATE_CONF=$(echo "$CANDIDATE" | jq -r '.confidence' 2>/dev/null || echo "0")
          EXISTING_CONF=$(jq -r --arg key "$CANDIDATE_KEY" --arg type "$CANDIDATE_TYPE" '
            select(.key == $key and .type == $type) | (.confidence // 0)
          ' "$LEARNINGS_FILE" 2>/dev/null | sort -nr | head -1)
          [ -n "$EXISTING_CONF" ] || EXISTING_CONF=0
          if [ "$CANDIDATE_CONF" -gt "$EXISTING_CONF" ]; then
            printf '%s\\n' "$CANDIDATE" >> "$LEARNINGS_FILE" 2>/dev/null || true
          fi
        fi
      fi
    fi
  fi
fi

# Archive observations (rotate to prevent unbounded growth)
ARCHIVE_DIR="$ROOT/${RUNTIME_ROOT}/observations.archive"
mkdir -p "$ARCHIVE_DIR" 2>/dev/null
ARCHIVE_FILE="$ARCHIVE_DIR/$(date -u +"%Y%m%d-%H%M%S").jsonl"
cp "$OBS_FILE" "$ARCHIVE_FILE" 2>/dev/null || true
: > "$OBS_FILE" 2>/dev/null || true

# Retain only the most recent 30 archives.
ARCHIVE_LIST=$(ls -1t "$ARCHIVE_DIR"/*.jsonl 2>/dev/null || true)
COUNT=0
for file in $ARCHIVE_LIST; do
  COUNT=$((COUNT + 1))
  if [ "$COUNT" -gt 30 ]; then
    rm -f "$file" 2>/dev/null || true
  fi
done

# Write session digest for cross-session context
STATE_FILE="$ROOT/${RUNTIME_ROOT}/state/flow-state.json"
DIGEST_FILE="$ROOT/${RUNTIME_ROOT}/state/session-digest.md"
STAGE_NOW="none"
RUN_DIGEST_ID="none"
if [ -f "$STATE_FILE" ]; then
  if command -v jq >/dev/null 2>&1; then
    STAGE_NOW=$(jq -r '.currentStage // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
    RUN_DIGEST_ID=$(jq -r '.activeRunId // "none"' "$STATE_FILE" 2>/dev/null || echo "none")
  fi
fi
{
  printf '%s\\n' "# Session Digest"
  printf '%s\\n' "- Stage: $STAGE_NOW"
  printf '%s\\n' "- Observations: $OBS_COUNT"
  printf '%s\\n' "- Timestamp: $TS"
  printf '%s\\n' "- Run: $RUN_DIGEST_ID"
} > "$DIGEST_FILE" 2>/dev/null || true

# Keep stage activity bounded by line count.
rotate_file "$ACTIVITY_FILE" 2000

release_lock
trap - EXIT INT TERM

exit 0
`;
}

/**
 * Updated hooks.json generators with PreToolUse/PostToolUse observation.
 */

export function claudeHooksJsonWithObservation(): string {
  return JSON.stringify({
    cclawHookSchemaVersion: 1,
    hooks: {
      SessionStart: [{
        matcher: "startup|resume|clear|compact",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`
        }]
      }],
      PreToolUse: [{
        matcher: "*",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/prompt-guard.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/workflow-guard.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/observe.sh pre`
        }]
      }],
      PostToolUse: [{
        matcher: "*",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/context-monitor.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/observe.sh post`
        }]
      }],
      Stop: [{
        hooks: [
          {
            type: "command",
            command: `bash ${RUNTIME_ROOT}/hooks/summarize-observations.sh`,
            timeout: 15
          },
          {
            type: "command",
            command: `bash ${RUNTIME_ROOT}/hooks/stop-checkpoint.sh`,
            timeout: 10
          }
        ]
      }]
    }
  }, null, 2);
}

export function cursorHooksJsonWithObservation(): string {
  return JSON.stringify({
    cclawHookSchemaVersion: 1,
    version: 1,
    hooks: {
      sessionStart: [{
        command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`
      }],
      sessionResume: [{
        command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`
      }],
      sessionClear: [{
        command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`
      }],
      sessionCompact: [{
        command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`
      }],
      preToolUse: [{
        matcher: "*",
        command: `bash ${RUNTIME_ROOT}/hooks/prompt-guard.sh`
      }, {
        matcher: "*",
        command: `bash ${RUNTIME_ROOT}/hooks/workflow-guard.sh`
      }, {
        matcher: "*",
        command: `bash ${RUNTIME_ROOT}/hooks/observe.sh pre`
      }],
      postToolUse: [{
        matcher: "*",
        command: `bash ${RUNTIME_ROOT}/hooks/context-monitor.sh`
      }, {
        matcher: "*",
        command: `bash ${RUNTIME_ROOT}/hooks/observe.sh post`
      }],
      stop: [
        { command: `bash ${RUNTIME_ROOT}/hooks/summarize-observations.sh`, timeout: 15 },
        { command: `bash ${RUNTIME_ROOT}/hooks/stop-checkpoint.sh`, timeout: 10 }
      ]
    }
  }, null, 2);
}

export function codexHooksJsonWithObservation(): string {
  return JSON.stringify({
    cclawHookSchemaVersion: 1,
    hooks: {
      SessionStart: [{
        matcher: "startup|resume|clear|compact",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/session-start.sh`,
          statusMessage: "Loading cclaw flow state"
        }]
      }],
      PreToolUse: [{
        matcher: "*",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/prompt-guard.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/workflow-guard.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/observe.sh pre`
        }]
      }],
      PostToolUse: [{
        matcher: "*",
        hooks: [{
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/context-monitor.sh`
        }, {
          type: "command",
          command: `bash ${RUNTIME_ROOT}/hooks/observe.sh post`
        }]
      }],
      Stop: [{
        hooks: [
          {
            type: "command",
            command: `bash ${RUNTIME_ROOT}/hooks/summarize-observations.sh`,
            timeout: 15
          },
          {
            type: "command",
            command: `bash ${RUNTIME_ROOT}/hooks/stop-checkpoint.sh`,
            timeout: 10
          }
        ]
      }]
    }
  }, null, 2);
}
