import { RUNTIME_ROOT } from "../constants.js";
import { META_SKILL_NAME } from "./meta-skill.js";

export function opencodePluginJs(_options: Record<string, never> = {}): string {
  return `// cclaw OpenCode plugin — generated by cclaw sync
import { existsSync, mkdirSync } from "node:fs";
import { readFile, stat } from "node:fs/promises";
import { join } from "node:path";

export default function cclawPlugin(ctx) {
  const root = ctx.directory || process.cwd();
  const runtimeDir = join(root, "${RUNTIME_ROOT}");
  const stateDir = join(runtimeDir, "state");
  const flowStatePath = join(stateDir, "flow-state.json");
  const checkpointPath = join(stateDir, "checkpoint.json");
  const activityPath = join(stateDir, "stage-activity.jsonl");
  const contextWarningsPath = join(stateDir, "context-warnings.jsonl");
  const contextModePath = join(stateDir, "context-mode.json");
  const contextsDir = join(runtimeDir, "contexts");
  const sessionDigestPath = join(stateDir, "session-digest.md");
  const knowledgePath = join(runtimeDir, "knowledge.jsonl");
  const knowledgeDigestPath = join(stateDir, "knowledge-digest.md");
  const metaSkillPath = join(runtimeDir, "skills/${META_SKILL_NAME}/SKILL.md");

  function ensureRuntimeDirs() {
    try {
      mkdirSync(runtimeDir, { recursive: true });
    } catch {
      // ignore
    }
    try {
      mkdirSync(stateDir, { recursive: true });
    } catch {
      // ignore
    }
  }

  async function readFlowState() {
    try {
      const raw = await readFile(flowStatePath, "utf8");
      const state = JSON.parse(raw);
      return {
        stage: typeof state.currentStage === "string" ? state.currentStage : "none",
        completed: Array.isArray(state.completedStages) ? state.completedStages.length : 0,
        activeRunId: typeof state.activeRunId === "string" ? state.activeRunId : "none"
      };
    } catch {
      return { stage: "none", completed: 0, activeRunId: "none" };
    }
  }

  async function readFileText(filePath) {
    try {
      return await readFile(filePath, "utf8");
    } catch {
      return "";
    }
  }

  async function readTailLines(filePath, maxLines) {
    const text = (await readFileText(filePath)).trim();
    if (!text) return [];
    return text.split(/\\r?\\n/).slice(-maxLines);
  }

  async function readCheckpointSummary() {
    try {
      const raw = await readFileText(checkpointPath);
      if (!raw) return "";
      const cp = JSON.parse(raw);
      return \`Checkpoint: stage=\${cp.stage || "none"}, status=\${cp.status || "unknown"}, run=\${cp.runId || "none"}, at=\${cp.timestamp || "unknown"}\`;
    } catch {
      return "";
    }
  }

  async function readContextMode() {
    let mode = "default";
    try {
      const parsed = JSON.parse(await readFileText(contextModePath));
      if (parsed && typeof parsed.activeMode === "string" && parsed.activeMode.trim().length > 0) {
        mode = parsed.activeMode.trim();
      }
    } catch {
      // keep default
    }
    const guidePath = join(contextsDir, mode + ".md");
    const guide = existsSync(guidePath) ? "${RUNTIME_ROOT}/contexts/" + mode + ".md" : "";
    return { mode, guide };
  }

  async function readRecentActivity() {
    try {
      const lines = await readTailLines(activityPath, 5);
      if (lines.length === 0) return [];
      return lines
        .map((line) => {
          try {
            return JSON.parse(line);
          } catch {
            return null;
          }
        })
        .filter(Boolean)
        .map((entry) => \`- \${entry.ts || "unknown"} [\${entry.phase || "unknown"}] \${entry.tool || "unknown"} (stage=\${entry.stage || "unknown"}, run=\${entry.runId || "none"})\`);
    } catch {
      return [];
    }
  }

  async function readLatestContextWarning() {
    try {
      const line = (await readTailLines(contextWarningsPath, 1))[0];
      if (!line) return "";
      try {
        const parsed = JSON.parse(line);
        if (parsed && typeof parsed.note === "string") return parsed.note;
      } catch {
        // non-json fallback
      }
      return line;
    } catch {
      return "";
    }
  }

  async function readKnowledgeDigest() {
    const digest = (await readFileText(knowledgeDigestPath)).trim();
    if (!digest) {
      return readTailLines(knowledgePath, 12);
    }
    return digest
      .split(/\\r?\\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .filter((line) => !line.startsWith("#"));
  }

  const BOOTSTRAP_MARKER = "<!-- cclaw-bootstrap-v1 -->";

  async function buildBootstrap() {
    const flow = await readFlowState();
    const parts = [
      BOOTSTRAP_MARKER,
      \`cclaw loaded. Flow: stage=\${flow.stage} (\${flow.completed}/8 completed, run=\${flow.activeRunId}). Active artifacts: ${RUNTIME_ROOT}/artifacts/\`
    ];
    const contextMode = await readContextMode();
    parts.push(
      contextMode.guide
        ? \`Context mode: \${contextMode.mode} (guide: \${contextMode.guide})\`
        : \`Context mode: \${contextMode.mode}\`
    );

    const checkpoint = await readCheckpointSummary();
    if (checkpoint) parts.push(checkpoint);

    const digest = (await readFileText(sessionDigestPath)).trim();
    if (digest) parts.push("Last session:", digest);

    const activity = await readRecentActivity();
    if (activity.length > 0) parts.push("Recent stage activity:", ...activity);

    const warning = await readLatestContextWarning();
    if (warning) parts.push("Latest context warning:", warning);

    const knowledge = await readKnowledgeDigest();
    if (knowledge.length > 0) parts.push("Knowledge digest (top relevant entries):", ...knowledge);

    parts.push(
      "If you discover a non-obvious rule or pattern, append one strict-schema JSON line to .cclaw/knowledge.jsonl using type: rule, pattern, lesson, or compound."
    );

    const meta = (await readFileText(metaSkillPath)).trim();
    if (meta) parts.push("", meta);
    return parts.join("\\n");
  }

  let bootstrapCache = "";
  let bootstrapMtimes = new Map();
  let bootstrapRefreshPromise = null;
  const BOOTSTRAP_SOURCE_PATHS = [
    flowStatePath,
    checkpointPath,
    activityPath,
    contextWarningsPath,
    contextModePath,
    sessionDigestPath,
    knowledgePath,
    knowledgeDigestPath,
    metaSkillPath
  ];

  async function readMtimeMs(filePath) {
    try {
      const st = await stat(filePath);
      return Number.isFinite(st.mtimeMs) ? st.mtimeMs : 0;
    } catch {
      return 0;
    }
  }

  async function snapshotBootstrapMtimes() {
    const next = new Map();
    for (const filePath of BOOTSTRAP_SOURCE_PATHS) {
      next.set(filePath, await readMtimeMs(filePath));
    }
    return next;
  }

  async function bootstrapNeedsRefresh() {
    if (!bootstrapCache) return true;
    for (const filePath of BOOTSTRAP_SOURCE_PATHS) {
      const prev = bootstrapMtimes.get(filePath) ?? 0;
      const now = await readMtimeMs(filePath);
      if (prev !== now) return true;
    }
    return false;
  }

  async function refreshBootstrapCache(force = false) {
    if (!force && !(await bootstrapNeedsRefresh())) {
      return bootstrapCache;
    }
    if (bootstrapRefreshPromise) {
      return bootstrapRefreshPromise;
    }
    bootstrapRefreshPromise = (async () => {
      const nextBootstrap = await buildBootstrap();
      const nextMtimes = await snapshotBootstrapMtimes();
      bootstrapCache = nextBootstrap;
      bootstrapMtimes = nextMtimes;
      return bootstrapCache;
    })();
    try {
      return await bootstrapRefreshPromise;
    } finally {
      bootstrapRefreshPromise = null;
    }
  }

  function getBootstrap() {
    return bootstrapCache;
  }

  const MAX_CONCURRENT_HOOKS = 2;
  let runningHookTasks = 0;
  const pendingHookTasks = [];

  function runNextHookTask() {
    if (runningHookTasks >= MAX_CONCURRENT_HOOKS) return;
    const queued = pendingHookTasks.shift();
    if (!queued) return;
    runningHookTasks += 1;
    queued()
      .catch(() => false)
      .finally(() => {
        runningHookTasks -= 1;
        runNextHookTask();
      });
  }

  function scheduleHookTask(task) {
    return new Promise((resolve) => {
      const wrapped = async () => {
        try {
          resolve(await task());
        } catch {
          resolve(false);
        }
      };
      pendingHookTasks.push(wrapped);
      runNextHookTask();
    });
  }

  async function runHookScript(hookName, payload = {}) {
    const { spawn } = await import("node:child_process");
    const hookRuntimePath = join(root, "${RUNTIME_ROOT}/hooks/run-hook.mjs");
    const input = typeof payload === "string" ? payload : JSON.stringify(payload ?? {});
    return scheduleHookTask(() => new Promise((resolve) => {
      let stderr = "";
      let settled = false;
      const finish = (ok) => {
        if (settled) return;
        settled = true;
        resolve(ok);
      };

      let child;
      try {
        child = spawn(process.execPath, [hookRuntimePath, hookName], {
          cwd: root,
          stdio: ["pipe", "ignore", "pipe"]
        });
      } catch {
        finish(false);
        return;
      }

      const timer = setTimeout(() => {
        child.kill("SIGKILL");
        if (stderr.length > 0) {
          console.error("[cclaw] opencode hook timeout: " + hookName + " stderr=" + stderr.slice(-1200));
        }
        finish(false);
      }, 20_000);

      child.stderr?.on("data", (chunk) => {
        stderr += String(chunk ?? "");
        if (stderr.length > 4000) {
          stderr = stderr.slice(-4000);
        }
      });
      child.on("error", () => {
        clearTimeout(timer);
        finish(false);
      });
      child.on("close", (code) => {
        clearTimeout(timer);
        const ok = code === 0;
        if (!ok && stderr.length > 0) {
          console.error("[cclaw] opencode hook failed: " + hookName + " stderr=" + stderr.slice(-1200));
        }
        finish(ok);
      });
      if (child.stdin) {
        child.stdin.on("error", (error) => {
          const code =
            error && typeof error === "object" && "code" in error
              ? String(error.code)
              : "";
          if (code === "EPIPE" || code === "ERR_STREAM_DESTROYED") {
            return;
          }
          clearTimeout(timer);
          finish(false);
        });
        try {
          child.stdin.end(input);
        } catch (error) {
          const code =
            error && typeof error === "object" && "code" in error
              ? String(error.code)
              : "";
          if (code !== "EPIPE" && code !== "ERR_STREAM_DESTROYED") {
            clearTimeout(timer);
            finish(false);
          }
        }
      }
    }));
  }

  function normalizeToolPayload(input, output) {
    if (typeof output === "undefined") return input ?? {};
    return { input: input ?? {}, output: output ?? {} };
  }

  function resolveEventType(payload) {
    if (typeof payload === "string") return payload;
    if (payload && typeof payload === "object") {
      if (typeof payload.type === "string") return payload.type;
      if (typeof payload.eventType === "string") return payload.eventType;
      if (typeof payload.kind === "string") return payload.kind;
      if (typeof payload.topic === "string") return payload.topic;
      if (typeof payload.name === "string") return payload.name;
      if (payload.event && typeof payload.event === "object") {
        if (typeof payload.event.type === "string") return payload.event.type;
        if (typeof payload.event.eventType === "string") return payload.event.eventType;
        if (typeof payload.event.kind === "string") return payload.event.kind;
        if (typeof payload.event.topic === "string") return payload.event.topic;
        if (typeof payload.event.name === "string") return payload.event.name;
      }
    }
    return "";
  }

  function resolveEventData(payload) {
    if (payload && typeof payload === "object") {
      if (payload.event && typeof payload.event === "object") {
        if (payload.event.data && typeof payload.event.data === "object") {
          return payload.event.data;
        }
        if (payload.event.payload && typeof payload.event.payload === "object") {
          return payload.event.payload;
        }
        return payload.event;
      }
      if (payload.data && typeof payload.data === "object") {
        return payload.data;
      }
      if (payload.payload && typeof payload.payload === "object") {
        return payload.payload;
      }
    }
    return payload;
  }

  ensureRuntimeDirs();
  void refreshBootstrapCache(true);

  return {
    event: async (payload) => {
      const eventType = resolveEventType(payload);
      const eventData = resolveEventData(payload);
      if (!eventType) {
        const keys =
          payload && typeof payload === "object"
            ? Object.keys(payload).slice(0, 10).join(", ")
            : typeof payload;
        console.error("[cclaw] opencode unknown event payload keys: " + keys);
      }
      if (
        eventType === "session.created" ||
        eventType === "session.resumed" ||
        eventType === "session.compacted" ||
        eventType === "session.cleared" ||
        eventType === "session.updated"
      ) {
        // Avoid writing directly to stdout in lifecycle hooks because it can
        // interfere with OpenCode TUI rendering. Bootstrap is injected via
        // the system transform hook instead.
        // session.updated covers config reloads and artifact/rules edits
        // that happen mid-session; without it the cache would stay stale
        // until the next compaction or restart.
        await refreshBootstrapCache(true);
      }
      if (eventType === "session.compacted") {
        await runHookScript("pre-compact.sh", eventData ?? {});
      }
      if (eventType === "session.idle") {
        await runHookScript("stop-checkpoint.sh", { loop_count: 0 });
      }
    },
    "tool.execute.before": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      const promptOk = await runHookScript("prompt-guard.sh", payload);
      const workflowOk = await runHookScript("workflow-guard.sh", payload);
      if (!promptOk || !workflowOk) {
        throw new Error(
          "cclaw OpenCode guard blocked tool.execute.before (prompt/workflow guard non-zero exit)."
        );
      }
    },
    "tool.execute.after": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      await runHookScript("context-monitor.sh", payload);
      void refreshBootstrapCache(false);
    },
    "experimental.chat.system.transform": (payload) => {
      const bootstrap = getBootstrap();
      if (!bootstrap) return payload;
      if (typeof payload === "string") {
        return payload.includes(BOOTSTRAP_MARKER) ? payload : \`\${payload}\\n\\n\${bootstrap}\`;
      }
      if (payload && typeof payload === "object" && typeof payload.system === "string") {
        if (payload.system.includes(BOOTSTRAP_MARKER)) return payload;
        return { ...payload, system: \`\${payload.system}\\n\\n\${bootstrap}\` };
      }
      return payload;
    }
  };
}
`;
}
