import { RUNTIME_ROOT } from "../constants.js";
import { META_SKILL_NAME } from "./meta-skill.js";

export function opencodePluginJs(_options: Record<string, never> = {}): string {
  return `// cclaw OpenCode plugin — generated by cclaw sync
import { existsSync, mkdirSync, readFileSync } from "node:fs";
import { join } from "node:path";

export default function cclawPlugin(ctx) {
  const root = ctx.directory || process.cwd();
  const runtimeDir = join(root, "${RUNTIME_ROOT}");
  const stateDir = join(runtimeDir, "state");
  const flowStatePath = join(stateDir, "flow-state.json");
  const checkpointPath = join(stateDir, "checkpoint.json");
  const activityPath = join(stateDir, "stage-activity.jsonl");
  const contextWarningsPath = join(stateDir, "context-warnings.jsonl");
  const contextModePath = join(stateDir, "context-mode.json");
  const contextsDir = join(runtimeDir, "contexts");
  const sessionDigestPath = join(stateDir, "session-digest.md");
  const knowledgePath = join(runtimeDir, "knowledge.jsonl");
  const knowledgeDigestPath = join(stateDir, "knowledge-digest.md");
  const metaSkillPath = join(runtimeDir, "skills/${META_SKILL_NAME}/SKILL.md");

  function ensureRuntimeDirs() {
    try {
      mkdirSync(runtimeDir, { recursive: true });
    } catch {
      // ignore
    }
    try {
      mkdirSync(stateDir, { recursive: true });
    } catch {
      // ignore
    }
  }

  function readFlowState() {
    try {
      const raw = readFileSync(flowStatePath, "utf8");
      const state = JSON.parse(raw);
      return {
        stage: typeof state.currentStage === "string" ? state.currentStage : "none",
        completed: Array.isArray(state.completedStages) ? state.completedStages.length : 0,
        activeRunId: typeof state.activeRunId === "string" ? state.activeRunId : "none"
      };
    } catch {
      return { stage: "none", completed: 0, activeRunId: "none" };
    }
  }

  function readFileText(filePath) {
    try {
      return readFileSync(filePath, "utf8");
    } catch {
      return "";
    }
  }

  function readTailLines(filePath, maxLines) {
    const text = readFileText(filePath).trim();
    if (!text) return [];
    return text.split(/\\r?\\n/).slice(-maxLines);
  }

  function readCheckpointSummary() {
    try {
      const raw = readFileText(checkpointPath);
      if (!raw) return "";
      const cp = JSON.parse(raw);
      return \`Checkpoint: stage=\${cp.stage || "none"}, status=\${cp.status || "unknown"}, run=\${cp.runId || "none"}, at=\${cp.timestamp || "unknown"}\`;
    } catch {
      return "";
    }
  }

  function readContextMode() {
    let mode = "default";
    try {
      const parsed = JSON.parse(readFileText(contextModePath));
      if (parsed && typeof parsed.activeMode === "string" && parsed.activeMode.trim().length > 0) {
        mode = parsed.activeMode.trim();
      }
    } catch {
      // keep default
    }
    const guidePath = join(contextsDir, mode + ".md");
    const guide = existsSync(guidePath) ? "${RUNTIME_ROOT}/contexts/" + mode + ".md" : "";
    return { mode, guide };
  }

  function readRecentActivity() {
    try {
      const lines = readTailLines(activityPath, 5);
      if (lines.length === 0) return [];
      return lines
        .map((line) => {
          try {
            return JSON.parse(line);
          } catch {
            return null;
          }
        })
        .filter(Boolean)
        .map((entry) => \`- \${entry.ts || "unknown"} [\${entry.phase || "unknown"}] \${entry.tool || "unknown"} (stage=\${entry.stage || "unknown"}, run=\${entry.runId || "none"})\`);
    } catch {
      return [];
    }
  }

  function readLatestContextWarning() {
    try {
      const line = readTailLines(contextWarningsPath, 1)[0];
      if (!line) return "";
      try {
        const parsed = JSON.parse(line);
        if (parsed && typeof parsed.note === "string") return parsed.note;
      } catch {
        // non-json fallback
      }
      return line;
    } catch {
      return "";
    }
  }

  function readKnowledgeDigest() {
    const digest = readFileText(knowledgeDigestPath).trim();
    if (!digest) {
      return readTailLines(knowledgePath, 12);
    }
    return digest
      .split(/\\r?\\n/)
      .map((line) => line.trim())
      .filter((line) => line.length > 0)
      .filter((line) => !line.startsWith("#"));
  }

  function buildBootstrap() {
    const flow = readFlowState();
    const parts = [
      \`cclaw loaded. Flow: stage=\${flow.stage} (\${flow.completed}/8 completed, run=\${flow.activeRunId}). Active artifacts: ${RUNTIME_ROOT}/artifacts/\`
    ];
    const contextMode = readContextMode();
    parts.push(
      contextMode.guide
        ? \`Context mode: \${contextMode.mode} (guide: \${contextMode.guide})\`
        : \`Context mode: \${contextMode.mode}\`
    );

    const checkpoint = readCheckpointSummary();
    if (checkpoint) parts.push(checkpoint);

    const digest = readFileText(sessionDigestPath).trim();
    if (digest) parts.push("Last session:", digest);

    const activity = readRecentActivity();
    if (activity.length > 0) parts.push("Recent stage activity:", ...activity);

    const warning = readLatestContextWarning();
    if (warning) parts.push("Latest context warning:", warning);

    const knowledge = readKnowledgeDigest();
    if (knowledge.length > 0) parts.push("Knowledge digest (top relevant entries):", ...knowledge);

    parts.push(
      "If you discover a non-obvious rule or pattern, append one strict-schema JSON line to .cclaw/knowledge.jsonl using type: rule, pattern, lesson, or compound."
    );

    const meta = readFileText(metaSkillPath).trim();
    if (meta) parts.push("", meta);
    return parts.join("\\n");
  }

  let bootstrapCache = "";

  function refreshBootstrapCache() {
    bootstrapCache = buildBootstrap();
  }

  function getBootstrap() {
    if (!bootstrapCache) refreshBootstrapCache();
    return bootstrapCache;
  }

  async function runHookScript(scriptFileName, payload = {}) {
    const { spawnSync } = await import("node:child_process");
    const scriptPath = join(root, "${RUNTIME_ROOT}/hooks/" + scriptFileName);
    const input = typeof payload === "string" ? payload : JSON.stringify(payload ?? {});
    try {
      const result = spawnSync("bash", [scriptPath], {
        cwd: root,
        timeout: 20000,
        stdio: ["pipe", "ignore", "ignore"],
        input
      });
      return typeof result.status === "number" ? result.status === 0 : false;
    } catch {
      return false;
    }
  }

  function normalizeToolPayload(input, output) {
    if (typeof output === "undefined") return input ?? {};
    return { input: input ?? {}, output: output ?? {} };
  }

  function resolveEventType(payload) {
    if (typeof payload === "string") return payload;
    if (payload && typeof payload === "object") {
      if (typeof payload.type === "string") return payload.type;
      if (typeof payload.name === "string") return payload.name;
      if (payload.event && typeof payload.event === "object") {
        if (typeof payload.event.type === "string") return payload.event.type;
        if (typeof payload.event.name === "string") return payload.event.name;
      }
    }
    return "";
  }

  function resolveEventData(payload) {
    if (payload && typeof payload === "object" && payload.event && typeof payload.event === "object") {
      return payload.event;
    }
    return payload;
  }

  ensureRuntimeDirs();

  return {
    event: async (payload) => {
      const eventType = resolveEventType(payload);
      const eventData = resolveEventData(payload);
      if (
        eventType === "session.created" ||
        eventType === "session.resumed" ||
        eventType === "session.compacted" ||
        eventType === "session.cleared"
      ) {
        // Avoid writing directly to stdout in lifecycle hooks because it can
        // interfere with OpenCode TUI rendering. Bootstrap is injected via
        // the system transform hook instead.
        refreshBootstrapCache();
      }
      if (eventType === "session.idle") {
        await runHookScript("stop-checkpoint.sh", { loop_count: 0 });
      }
      if (eventType === "tool.execute.before") {
        const toolPayload = normalizeToolPayload(eventData, undefined);
        const promptOk = await runHookScript("prompt-guard.sh", toolPayload);
        const workflowOk = await runHookScript("workflow-guard.sh", toolPayload);
        if (!promptOk || !workflowOk) {
          throw new Error(
            "cclaw OpenCode guard blocked tool.execute.before (prompt/workflow guard non-zero exit)."
          );
        }
      }
      if (eventType === "tool.execute.after") {
        const toolPayload = normalizeToolPayload(eventData, undefined);
        await runHookScript("context-monitor.sh", toolPayload);
      }
    },
    "tool.execute.before": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      const promptOk = await runHookScript("prompt-guard.sh", payload);
      const workflowOk = await runHookScript("workflow-guard.sh", payload);
      if (!promptOk || !workflowOk) {
        throw new Error(
          "cclaw OpenCode guard blocked tool.execute.before (prompt/workflow guard non-zero exit)."
        );
      }
    },
    "tool.execute.after": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      await runHookScript("context-monitor.sh", payload);
    },
    "experimental.chat.system.transform": (payload) => {
      const bootstrap = getBootstrap();
      if (typeof payload === "string") {
        return payload.includes("cclaw loaded.") ? payload : \`\${payload}\\n\\n\${bootstrap}\`;
      }
      if (payload && typeof payload === "object" && typeof payload.system === "string") {
        if (payload.system.includes("cclaw loaded.")) return payload;
        return { ...payload, system: \`\${payload.system}\\n\\n\${bootstrap}\` };
      }
      return payload;
    }
  };
}
`;
}
