import { RUNTIME_ROOT } from "../constants.js";
import { META_SKILL_NAME } from "./meta-skill.js";
import {
  SHARED_FLOW_AND_KNOWLEDGE_SNIPPETS,
  SHARED_STAGE_SUPPORT_SNIPPETS
} from "./runtime-shared-snippets.js";

export function opencodePluginJs(_options: Record<string, never> = {}): string {
  return `// cclaw OpenCode plugin — generated by npx cclaw-cli sync
import { appendFileSync, existsSync, mkdirSync } from "node:fs";
import { readFile, stat } from "node:fs/promises";
import { basename, join } from "node:path";

export default function cclawPlugin(ctx) {
  const root = ctx.directory || process.cwd();
  const runtimeDir = join(root, "${RUNTIME_ROOT}");
  const stateDir = join(runtimeDir, "state");
  const logsDir = join(runtimeDir, "logs");
  const pluginLogPath = join(logsDir, "opencode-plugin.log");
  const configPath = join(runtimeDir, "config.yaml");
  const flowStatePath = join(stateDir, "flow-state.json");
  const knowledgePath = join(runtimeDir, "knowledge.jsonl");
  const metaSkillPath = join(runtimeDir, "skills/${META_SKILL_NAME}/SKILL.md");
  ${SHARED_FLOW_AND_KNOWLEDGE_SNIPPETS}
  ${SHARED_STAGE_SUPPORT_SNIPPETS}

  function ensureRuntimeDirs() {
    try {
      mkdirSync(runtimeDir, { recursive: true });
    } catch {
      // ignore
    }
    try {
      mkdirSync(stateDir, { recursive: true });
    } catch {
      // ignore
    }
  }

  /**
   * Diagnostic log used instead of console.error on the hot path.
   * Writing to a file keeps hook failures and unknown events from
   * racing OpenCode's TUI renderer (which causes the overlapping-text
   * artifact users have reported). Best-effort: any I/O failure is
   * swallowed so logging never itself blocks or throws.
   */
  function logToFile(line) {
    try {
      mkdirSync(logsDir, { recursive: true });
    } catch {
      return;
    }
    const timestamp = new Date().toISOString();
    try {
      appendFileSync(pluginLogPath, timestamp + " " + line + "\\n", "utf8");
    } catch {
      // ignore — never let logging fail the hook
    }
  }

  async function readFlowState() {
    try {
      const raw = await readFile(flowStatePath, "utf8");
      return summarizeFlowState(JSON.parse(raw));
    } catch {
      return summarizeFlowState({});
    }
  }

  async function readFileText(filePath) {
    try {
      return await readFile(filePath, "utf8");
    } catch {
      return "";
    }
  }

  async function readKnowledgeDigest(stage) {
    const raw = await readFileText(knowledgePath);
    return parseKnowledgeDigest(raw, stage, 6).lines;
  }

  async function readStageSupportContext(stage) {
    if (!isKnownStageId(stage)) return [];
    const parts = [];
    const contract = (await readFileText(join(runtimeDir, "templates/state-contracts", stage + ".json"))).trim();
    if (contract.length > 0) {
      parts.push(
        "Current stage state contract (read before drafting or editing the stage artifact):\\n" +
          contract
      );
    }
    const reviewPromptName = reviewPromptFileName(stage);
    if (reviewPromptName) {
      const prompt = (await readFileText(join(runtimeDir, "skills/review-prompts", reviewPromptName))).trim();
      if (prompt.length > 0) {
        parts.push(
          "Current stage calibrated review prompt (use before asking for approval/completion):\\n" +
            prompt
        );
      }
    }
    return parts;
  }

  const BOOTSTRAP_MARKER = "<!-- cclaw-bootstrap-v1 -->";

  async function buildBootstrap() {
    const flow = await readFlowState();
    const parts = [
      BOOTSTRAP_MARKER,
      \`cclaw loaded. Flow: stage=\${flow.stage} (\${flow.completed}/8 completed, run=\${flow.activeRunId}). Active artifacts: \${activeArtifactsPathLabel("${RUNTIME_ROOT}")}\`
    ];



    const knowledge = await readKnowledgeDigest(flow.stage);
    if (knowledge.length > 0) parts.push("Knowledge digest (top relevant entries):", ...knowledge);

    const stageSupport = await readStageSupportContext(flow.stage);
    if (stageSupport.length > 0) parts.push(...stageSupport);

    parts.push(
      "If you discover a non-obvious rule or pattern during stage work, add it to the current artifact ## Learnings section; stage-complete harvests it into .cclaw/knowledge.jsonl. If this plugin does not load, run \`npx cclaw-cli sync\`, verify opencode.json(.c) includes the cclaw plugin registration, then run \`npx cclaw-cli sync\`. Direct JSONL append is only for explicit manual learnings operations."
    );

    const meta = (await readFileText(metaSkillPath)).trim();
    if (meta) parts.push("", meta);
    return parts.join("\\n");
  }

  let bootstrapCache = "";
  let bootstrapMtimes = new Map();
  let bootstrapRefreshPromise = null;
  const BOOTSTRAP_SOURCE_PATHS = [
    flowStatePath,
    knowledgePath,
    metaSkillPath,
    ...STAGE_IDS.map((stage) => join(runtimeDir, "templates/state-contracts", stage + ".json")),
    ...REVIEW_PROMPT_FILES.map((file) => join(runtimeDir, "skills/review-prompts", file))
  ];

  async function readMtimeMs(filePath) {
    try {
      const st = await stat(filePath);
      return Number.isFinite(st.mtimeMs) ? st.mtimeMs : 0;
    } catch {
      return 0;
    }
  }

  async function snapshotBootstrapMtimes() {
    const next = new Map();
    for (const filePath of BOOTSTRAP_SOURCE_PATHS) {
      next.set(filePath, await readMtimeMs(filePath));
    }
    return next;
  }

  async function bootstrapNeedsRefresh() {
    if (!bootstrapCache) return true;
    for (const filePath of BOOTSTRAP_SOURCE_PATHS) {
      const prev = bootstrapMtimes.get(filePath) ?? 0;
      const now = await readMtimeMs(filePath);
      if (prev !== now) return true;
    }
    return false;
  }

  async function refreshBootstrapCache(force = false) {
    if (!force && !(await bootstrapNeedsRefresh())) {
      return bootstrapCache;
    }
    if (bootstrapRefreshPromise) {
      return bootstrapRefreshPromise;
    }
    bootstrapRefreshPromise = (async () => {
      const nextBootstrap = await buildBootstrap();
      const nextMtimes = await snapshotBootstrapMtimes();
      bootstrapCache = nextBootstrap;
      bootstrapMtimes = nextMtimes;
      return bootstrapCache;
    })();
    try {
      return await bootstrapRefreshPromise;
    } finally {
      bootstrapRefreshPromise = null;
    }
  }

  function getBootstrap() {
    return bootstrapCache;
  }

  const MAX_CONCURRENT_HOOKS = 2;
  let runningHookTasks = 0;
  const pendingHookTasks = [];

  function runNextHookTask() {
    if (runningHookTasks >= MAX_CONCURRENT_HOOKS) return;
    const queued = pendingHookTasks.shift();
    if (!queued) return;
    runningHookTasks += 1;
    queued()
      .catch(() => false)
      .finally(() => {
        runningHookTasks -= 1;
        runNextHookTask();
      });
  }

  function scheduleHookTask(task) {
    return new Promise((resolve) => {
      const wrapped = async () => {
        try {
          resolve(await task());
        } catch {
          resolve(false);
        }
      };
      pendingHookTasks.push(wrapped);
      runNextHookTask();
    });
  }

  const lastHookStderr = new Map();
  function recordHookStderr(hookName, stderr) {
    if (typeof hookName !== "string" || hookName.length === 0) return;
    const trimmed = typeof stderr === "string" ? stderr.trim() : "";
    if (trimmed.length === 0) {
      lastHookStderr.delete(hookName);
      return;
    }
    lastHookStderr.set(hookName, trimmed);
  }

  /**
   * A hook process can exit non-zero for two very different reasons:
   *   (a) the guard legitimately decided to refuse an operation
   *       (strict-mode refusal — this is the *only* case we ever want
   *       to surface as a block to the user), or
   *   (b) the hook infrastructure itself failed — the runtime crashed,
   *       a child binary was missing, stderr is a chunk of yargs help
   *       from some unrelated process, timeout, etc.
   *
   * Treating (b) as a block is what produces the "guard blocked
   * tool.execute.before" error on a user who did nothing wrong. The
   * heuristic below trims guaranteed-infra signals so only cleanly
   * structured guard output is eligible for a real strict-mode block.
   */
  const INFRA_NOISE_PATTERNS = [
    /^\\s*(Usage|Options|Commands|Examples|Positionals|Aliases):/im,
    /^\\s*--[a-z][a-z0-9-]*\\b.*\\[(string|boolean|number|array)\\]/im,
    /\\bcommand (not found|failed)\\b/i,
    /\\bno such file or directory\\b/i,
    /\\bCannot find module\\b/i,
    /\\bThrowsCompletion\\b/,
    /\\b(Reference|Syntax|Type|Range)Error\\b/,
    /^\\s*at [^\\n]+\\([^)]*:\\d+:\\d+\\)/im,
    /^\\s*node:internal\\b/im
  ];
  function looksLikeInfrastructureFailure(stderr) {
    if (typeof stderr !== "string") return true;
    const trimmed = stderr.trim();
    if (trimmed.length === 0) return true;
    for (const pattern of INFRA_NOISE_PATTERNS) {
      if (pattern.test(trimmed)) return true;
    }
    return false;
  }

  function resolveNodeExecutable() {
    const override = typeof process.env.CCLAW_NODE_EXECUTABLE === "string"
      ? process.env.CCLAW_NODE_EXECUTABLE.trim()
      : "";
    if (override.length > 0) return override;

    const execName = basename(process.execPath || "").toLowerCase();
    if (execName === "node" || execName === "node.exe") {
      return process.execPath;
    }

    // OpenCode can host plugins from its own CLI binary, making
    // process.execPath point at opencode instead of Node. Fall back to the
    // user's Node on PATH so generated cclaw hooks execute as JavaScript.
    return "node";
  }

  async function runHookScript(hookName, payload = {}) {
    const { spawn } = await import("node:child_process");
    const hookRuntimePath = join(root, "${RUNTIME_ROOT}/hooks/run-hook.mjs");
    const input = typeof payload === "string" ? payload : JSON.stringify(payload ?? {});
    return scheduleHookTask(() => new Promise((resolve) => {
      let stderr = "";
      let settled = false;
      const finish = (ok) => {
        if (settled) return;
        settled = true;
        recordHookStderr(hookName, stderr);
        resolve(ok);
      };

      let child;
      try {
        child = spawn(resolveNodeExecutable(), [hookRuntimePath, hookName], {
          cwd: root,
          stdio: ["pipe", "ignore", "pipe"]
        });
      } catch {
        finish(false);
        return;
      }

      // Tool.execute.before is a user-facing hot path: 20s is far too
      // long to wait on a guard. 5s gives the hook real breathing room
      // (typical runtime is well under 500ms) while capping the worst-
      // case stall at a number the user will still tolerate.
      const timer = setTimeout(() => {
        child.kill("SIGKILL");
        if (stderr.length > 0) {
          logToFile("hook timeout: " + hookName + " stderr=" + stderr.slice(-1200));
        } else {
          logToFile("hook timeout: " + hookName + " (no stderr)");
        }
        finish(false);
      }, 5_000);

      child.stderr?.on("data", (chunk) => {
        stderr += String(chunk ?? "");
        if (stderr.length > 4000) {
          stderr = stderr.slice(-4000);
        }
      });
      child.on("error", () => {
        clearTimeout(timer);
        finish(false);
      });
      child.on("close", (code) => {
        clearTimeout(timer);
        const ok = code === 0;
        if (!ok && stderr.length > 0) {
          logToFile("hook failed: " + hookName + " exit=" + code + " stderr=" + stderr.slice(-1200));
        }
        finish(ok);
      });
      if (child.stdin) {
        child.stdin.on("error", (error) => {
          const code =
            error && typeof error === "object" && "code" in error
              ? String(error.code)
              : "";
          if (code === "EPIPE" || code === "ERR_STREAM_DESTROYED") {
            return;
          }
          clearTimeout(timer);
          finish(false);
        });
        try {
          child.stdin.end(input);
        } catch (error) {
          const code =
            error && typeof error === "object" && "code" in error
              ? String(error.code)
              : "";
          if (code !== "EPIPE" && code !== "ERR_STREAM_DESTROYED") {
            clearTimeout(timer);
            finish(false);
          }
        }
      }
    }));
  }

  function normalizeToolPayload(input, output) {
    if (typeof output === "undefined") return input ?? {};
    return { input: input ?? {}, output: output ?? {} };
  }

  /**
   * Read-only tools cannot mutate state or execute arbitrary code, so
   * running prompt/workflow guards on them is pure overhead and — worse —
   * surfaces a hard block when guards are misconfigured. OpenCode tool
   * names vary (Claude/Codex use PascalCase; opencode-native often uses
   * lowercase), so we normalize and match against a tight allow-list.
   * Anything not in this list (bash, edit, write, patch, task, run, …)
   * still runs through guards.
   */
  const SAFE_READONLY_TOOLS = new Set([
    // Filesystem / search reads — no state mutation possible.
    "read",
    "glob",
    "grep",
    "list",
    "ls",
    "view",
    "find",
    // Network reads — no local state mutation.
    "webfetch",
    "websearch",
    // User-facing question / ask tools: they only ask the human for
    // input and cannot touch the filesystem or execute code. Blocking
    // them strands the plugin mid-decision (see OpenCode's \`question\`).
    "question",
    "ask",
    "askuser",
    "askquestion",
    "ask_question",
    "ask_user",
    "ask_user_question",
    "askuserquestion",
    "request_user_input",
    "requestuserinput",
    "prompt",
    // Thinking / scratchpad tools — pure reasoning with no side effects.
    "think",
    "thinking",
    // Todo bookkeeping tools — they write only inside the harness's own
    // session state, not project files, and blocking them breaks agent
    // planning without protecting anything.
    "todo",
    "todoread",
    "todowrite",
    "todo_read",
    "todo_write"
  ]);

  function isSafeReadOnlyTool(payload) {
    if (!payload || typeof payload !== "object") return false;
    const candidates = [
      payload.tool,
      payload.name,
      payload.tool_name,
      payload.toolName
    ];
    const inner = payload.input;
    if (inner && typeof inner === "object") {
      candidates.push(inner.tool, inner.name, inner.tool_name, inner.toolName);
    }
    for (const candidate of candidates) {
      if (typeof candidate !== "string" || candidate.length === 0) continue;
      if (SAFE_READONLY_TOOLS.has(candidate.toLowerCase())) return true;
    }
    return false;
  }

  /**
   * Strictness derived from (in order of precedence): CCLAW_STRICTNESS
   * env override, \`.cclaw/config.yaml\` key \`strictness\`, or the
   * library default of "advisory". The plugin only ever *blocks* tool
   * execution when strictness resolves to "strict"; in advisory mode
   * guard failures are logged and the tool call proceeds. This mirrors
   * the Ralph-loop / hook-runtime semantics of
   * \`DEFAULT_STRICTNESS = advisory\`, so the plugin can no longer
   * accidentally be the stricter half of a mismatched pair.
   */
  async function readConfigStrictness() {
    try {
      if (!existsSync(configPath)) return "";
      const raw = await readFileText(configPath);
      if (typeof raw !== "string" || raw.length === 0) return "";
      const match = raw.match(/^\\s*strictness\\s*:\\s*([A-Za-z0-9_-]+)/m);
      return match && typeof match[1] === "string" ? match[1].trim().toLowerCase() : "";
    } catch {
      return "";
    }
  }

  async function resolveStrictness() {
    const envRaw = typeof process.env.CCLAW_STRICTNESS === "string"
      ? process.env.CCLAW_STRICTNESS.trim().toLowerCase()
      : "";
    if (envRaw === "strict") return "strict";
    if (envRaw === "advisory" || envRaw === "off" || envRaw === "disabled" || envRaw === "none") {
      return "advisory";
    }
    const fileRaw = await readConfigStrictness();
    if (fileRaw === "strict") return "strict";
    return "advisory";
  }

  /**
   * cclaw considers itself "active" in a project when both the state
   * file and the hook runtime script exist. If either is missing the
   * plugin behaves as a no-op for guards — this project hasn't been
   * initialized (or the install is corrupt) and blocking every tool
   * call would strand the user.
   */
  function isCclawInitialized() {
    try {
      const hookRuntimePath = join(runtimeDir, "hooks/run-hook.mjs");
      return existsSync(flowStatePath) && existsSync(hookRuntimePath);
    } catch {
      return false;
    }
  }

  let notInitializedAdvised = false;
  function noteNotInitialized() {
    if (notInitializedAdvised) return;
    notInitializedAdvised = true;
    logToFile(
      "guards skipped: cclaw is not initialized in this project. " +
      "Run \`npx cclaw-cli init\` in " + root + " to activate flow enforcement."
    );
  }

  /**
   * Escape hatch for a user stuck behind a misbehaving guard chain.
   * Reads a small set of env vars that all mean "turn cclaw off for this
   * session": CCLAW_DISABLE=1 (primary), CCLAW_STRICTNESS=off, or
   * CCLAW_GUARDS=off. Anything truthy disables both guards and the
   * advisory path. Logged once so users can confirm the bypass is in
   * effect without cluttering the TUI.
   */
  const DISABLE_ENV_KEYS = ["CCLAW_DISABLE", "CCLAW_GUARDS", "CCLAW_STRICTNESS"];
  let disabledAdvised = false;
  function isCclawDisabled() {
    for (const key of DISABLE_ENV_KEYS) {
      const raw = process.env[key];
      if (typeof raw !== "string") continue;
      const value = raw.trim().toLowerCase();
      if (value.length === 0) continue;
      if (key === "CCLAW_STRICTNESS") {
        if (value === "off" || value === "disabled" || value === "none") {
          return { disabled: true, key, value };
        }
        continue;
      }
      if (
        value === "1" ||
        value === "true" ||
        value === "yes" ||
        value === "on" ||
        value === "off" ||
        value === "disabled"
      ) {
        if (key === "CCLAW_GUARDS" && (value === "on" || value === "true" || value === "yes" || value === "1")) {
          continue;
        }
        return { disabled: true, key, value };
      }
    }
    return { disabled: false, key: "", value: "" };
  }
  function noteDisabled(reason) {
    if (disabledAdvised) return;
    disabledAdvised = true;
    logToFile(
      "guards disabled by env " + reason.key + "=" + reason.value + ". " +
      "All tool calls will pass through without prompt/workflow checks."
    );
  }

  function resolveEventType(payload) {
    if (typeof payload === "string") return payload;
    if (payload && typeof payload === "object") {
      if (typeof payload.type === "string") return payload.type;
      if (typeof payload.eventType === "string") return payload.eventType;
      if (typeof payload.kind === "string") return payload.kind;
      if (typeof payload.topic === "string") return payload.topic;
      if (typeof payload.name === "string") return payload.name;
      if (payload.event && typeof payload.event === "object") {
        if (typeof payload.event.type === "string") return payload.event.type;
        if (typeof payload.event.eventType === "string") return payload.event.eventType;
        if (typeof payload.event.kind === "string") return payload.event.kind;
        if (typeof payload.event.topic === "string") return payload.event.topic;
        if (typeof payload.event.name === "string") return payload.event.name;
      }
    }
    return "";
  }

  function resolveEventData(payload) {
    if (payload && typeof payload === "object") {
      if (payload.event && typeof payload.event === "object") {
        if (payload.event.data && typeof payload.event.data === "object") {
          return payload.event.data;
        }
        if (payload.event.payload && typeof payload.event.payload === "object") {
          return payload.event.payload;
        }
        return payload.event;
      }
      if (payload.data && typeof payload.data === "object") {
        return payload.data;
      }
      if (payload.payload && typeof payload.payload === "object") {
        return payload.payload;
      }
    }
    return payload;
  }

  ensureRuntimeDirs();
  void refreshBootstrapCache(true);

  return {
    event: async (payload) => {
      const eventType = resolveEventType(payload);
      const eventData = resolveEventData(payload);
      if (!eventType) {
        const keys =
          payload && typeof payload === "object"
            ? Object.keys(payload).slice(0, 10).join(", ")
            : typeof payload;
        logToFile("unknown event payload keys: " + keys);
      }
      const isSessionLifecycle =
        eventType === "session.created" ||
        eventType === "session.resumed" ||
        eventType === "session.compacted" ||
        eventType === "session.cleared" ||
        eventType === "session.updated";
      // session.compacted must run pre-compact BEFORE canonical rehydration,
      // otherwise the injected system prompt can show the pre-compact
      // digest/state until the next lifecycle event.
      if (eventType === "session.compacted") {
        await runHookScript("pre-compact", eventData ?? {});
      }
      if (isSessionLifecycle) {
        // Keep OpenCode aligned with Claude/Cursor/Codex: session-start is
        // the canonical rehydrate path that refreshes derived state such as
        // Ralph Loop, compound readiness, and hook-error breadcrumbs. The
        // plugin refreshes its local bootstrap cache afterwards so the system
        // transform sees the side effects from the hook runtime.
        await runHookScript("session-start", eventData ?? {});
        await refreshBootstrapCache(true);
      }
      if (eventType === "session.idle") {
        await runHookScript("stop-handoff", { loop_count: 0 });
      }
    },
    "tool.execute.before": async (input, output) => {
      const disabled = isCclawDisabled();
      if (disabled.disabled) {
        // Explicit user override (CCLAW_DISABLE=1 et al): stay fully out
        // of the way. Any real problem with the guard chain should not
        // prevent the user from unblocking themselves.
        noteDisabled(disabled);
        return;
      }
      const payload = normalizeToolPayload(input, output);
      if (isSafeReadOnlyTool(payload)) {
        // Read-only tools bypass guards — they cannot mutate state and
        // blocking them gives users an unusable session when guards are
        // misconfigured or cclaw isn't fully initialized.
        return;
      }
      if (!isCclawInitialized()) {
        // Project has no flow-state or hook runtime: cclaw isn't in use
        // here. Never block the user's tools because of setup they didn't
        // ask for. Surface a single advisory so they can notice.
        noteNotInitialized();
        return;
      }
      const [promptOk, workflowOk] = await Promise.all([
        runHookScript("prompt-guard", payload),
        runHookScript("workflow-guard", payload)
      ]);
      if (!promptOk || !workflowOk) {
        const failed = !promptOk ? "prompt-guard" : "workflow-guard";
        const rawDetail = lastHookStderr.get(failed) || "";
        const detail = rawDetail.length > 0 ? rawDetail.slice(-400) : "(no stderr captured)";
        if (looksLikeInfrastructureFailure(rawDetail)) {
          // Never let a broken hook runtime or misrouted child-process
          // stderr (yargs help, Node crash, ENOENT, timeout) masquerade
          // as a policy block. Log the infra hit and let the user keep
          // working regardless of strictness.
          logToFile(
            "infra: " + failed + " non-zero exit with non-guard stderr — treated as infrastructure failure, tool allowed. " +
            "stderr=" + detail.replace(/\\s+/g, " ").slice(0, 300)
          );
          return;
        }
        const strictness = await resolveStrictness();
        if (strictness !== "strict") {
          // Advisory mode (the default) — every guard refusal is a hint,
          // not a hard stop. Users report the "failure" as a log line
          // and keep working. Only \`strictness: strict\` in config.yaml
          // or CCLAW_STRICTNESS=strict upgrades this to a thrown block.
          logToFile(
            "advisory: " + failed + " flagged tool.execute.before (strictness=" +
            strictness + "). detail=" + detail.replace(/\\s+/g, " ").slice(0, 300)
          );
          return;
        }
        throw new Error(
          "cclaw " + failed + " blocked tool.execute.before.\\n" +
          "Reason: " + detail + "\\n" +
          "Diagnose: run \`npx cclaw-cli sync\` in project root.\\n" +
          "Bypass (temporary): export CCLAW_DISABLE=1 before starting OpenCode,\\n" +
          "or set \`strictness: advisory\` in .cclaw/config.yaml."
        );
      }
    },
    "tool.execute.after": async (input, output) => {
      const payload = normalizeToolPayload(input, output);
      await runHookScript("context-monitor", payload);
      void refreshBootstrapCache(false);
    },
    "experimental.chat.system.transform": (payload) => {
      const bootstrap = getBootstrap();
      if (!bootstrap) return payload;
      if (typeof payload === "string") {
        return payload.includes(BOOTSTRAP_MARKER) ? payload : \`\${payload}\\n\\n\${bootstrap}\`;
      }
      if (payload && typeof payload === "object" && typeof payload.system === "string") {
        if (payload.system.includes(BOOTSTRAP_MARKER)) return payload;
        return { ...payload, system: \`\${payload.system}\\n\\n\${bootstrap}\` };
      }
      return payload;
    }
  };
}
`;
}
