import fs from "node:fs/promises";
import path from "node:path";
import type { Writable } from "node:stream";
import { RUNTIME_ROOT } from "../constants.js";
import { writeFileSafe } from "../fs-utils.js";
import { readDelegationLedger } from "../delegation.js";

interface InternalIo {
  stdout: Writable;
  stderr: Writable;
}

export interface CohesionContractArgs {
  stub: boolean;
  force: boolean;
  reason: string | null;
}

export function parseCohesionContractArgs(
  tokens: string[]
): CohesionContractArgs | null {
  const args: CohesionContractArgs = { stub: false, force: false, reason: null };
  for (const token of tokens) {
    if (token === "--stub") {
      args.stub = true;
      continue;
    }
    if (token === "--force") {
      args.force = true;
      continue;
    }
    if (token.startsWith("--reason=")) {
      const raw = token.slice("--reason=".length).trim();
      if (raw.length > 0) args.reason = raw;
      continue;
    }
    return null;
  }
  if (!args.stub) return null;
  return args;
}

/**
 * v6.14.2 — emit a minimal advisory cohesion contract that satisfies
 * the linter shape check (`cohesion-contract.{md,json}`) so projects
 * with `legacyContinuation: true` and ≥ 2 completed slice-implementer
 * rows can clear the soft `tdd.cohesion_contract_missing` finding
 * without hand-authoring the document.
 *
 * The stub is intentionally bare — `sharedTypes`, `touchpoints`, and
 * `slices` are populated from the active run delegation ledger so
 * downstream tooling can see which slices the contract acknowledges,
 * but the contract carries `status.verdict: "advisory_legacy"` so
 * reviewers know not to treat it as authoritative.
 *
 * Refuses to overwrite an existing contract unless `--force` is
 * passed; the existing file is treated as authored work.
 */
export async function runCohesionContractCommand(
  projectRoot: string,
  tokens: string[],
  io: InternalIo
): Promise<number> {
  const parsed = parseCohesionContractArgs(tokens);
  if (!parsed) {
    io.stderr.write(
      "cclaw internal cohesion-contract: usage: --stub [--force] [--reason=\"<short>\"]\n"
    );
    return 1;
  }
  const artifactsDir = path.join(projectRoot, RUNTIME_ROOT, "artifacts");
  const mdPath = path.join(artifactsDir, "cohesion-contract.md");
  const jsonPath = path.join(artifactsDir, "cohesion-contract.json");

  if (!parsed.force) {
    const mdExists = await fileExists(mdPath);
    const jsonExists = await fileExists(jsonPath);
    if (mdExists || jsonExists) {
      io.stderr.write(
        "cclaw internal cohesion-contract: existing cohesion-contract.{md,json} present; pass --force to overwrite.\n"
      );
      return 1;
    }
  }

  const ledger = await readDelegationLedger(projectRoot).catch(() => null);
  const sliceIds = collectSliceIds(ledger?.entries ?? []);

  const reasonNote = parsed.reason
    ? `Reason: ${parsed.reason}`
    : "Reason: legacyContinuation auto-stub.";

  const md = [
    "# Cohesion Contract",
    "",
    "_Advisory stub generated by `cclaw-cli internal cohesion-contract --stub`._",
    "_Status: `advisory_legacy` — populated for legacyContinuation projects so the_",
    "_TDD linter does not block stage-complete on `tdd.cohesion_contract_missing`._",
    "",
    `${reasonNote}`,
    "",
    "## Shared Types & Interfaces",
    "| Symbol | Path | Signature | Owner slice |",
    "|---|---|---|---|",
    "| (none recorded) | (none) | (none) | (n/a) |",
    "",
    "## Naming Conventions",
    "- Stub: per-slice modules continue to follow the existing repo conventions.",
    "",
    "## Invariants",
    "- Stub: no cross-slice invariants asserted; treat each slice as independent until upgraded.",
    "",
    "## Integration Touchpoints",
    "| From slice | To slice | Surface | Integration test name |",
    "|---|---|---|---|",
    "| (none recorded) | (n/a) | (n/a) | (n/a) |",
    "",
    "## Behavior Specifications per Slice",
    sliceIds.length === 0
      ? "- (none recorded)"
      : sliceIds
          .map((sid) => `### Slice ${sid}\n- Behavior: see \`tdd-slices/${sid}.md\` (if present).`)
          .join("\n\n"),
    "",
    "## Status",
    "| Slice | Implemented | Tests pass | Cohesion verified |",
    "|---|---|---|---|",
    sliceIds.length === 0
      ? "| (none) | n/a | n/a | n/a |"
      : sliceIds.map((sid) => `| ${sid} | yes | yes | advisory |`).join("\n"),
    ""
  ].join("\n");

  const jsonStub = {
    version: 1,
    sharedTypes: [] as Array<Record<string, string>>,
    touchpoints: [] as Array<Record<string, string>>,
    slices: sliceIds.map((sid) => ({
      sliceId: sid,
      description: `Stub entry for ${sid}; advisory under legacyContinuation.`,
      implemented: true,
      testsPass: true,
      cohesionVerified: false
    })),
    status: {
      verdict: "advisory_legacy",
      generatedBy: "cclaw-cli internal cohesion-contract --stub",
      reason: parsed.reason ?? "legacyContinuation auto-stub"
    }
  };

  await writeFileSafe(mdPath, md);
  await writeFileSafe(jsonPath, `${JSON.stringify(jsonStub, null, 2)}\n`);

  io.stdout.write(
    `cclaw: cohesion-contract stub written (${sliceIds.length} slice(s) referenced). ` +
      "Status: advisory_legacy — review and replace once cross-slice cohesion data is real.\n"
  );
  return 0;
}

async function fileExists(filePath: string): Promise<boolean> {
  try {
    await fs.access(filePath);
    return true;
  } catch {
    return false;
  }
}

function collectSliceIds(
  entries: Array<{ agent?: string; status?: string; sliceId?: string }>
): string[] {
  const set = new Set<string>();
  for (const entry of entries) {
    if (entry.agent !== "slice-implementer") continue;
    if (entry.status !== "completed") continue;
    if (typeof entry.sliceId !== "string") continue;
    if (entry.sliceId.length === 0) continue;
    set.add(entry.sliceId);
  }
  return [...set].sort((a, b) => {
    const an = parseSliceNum(a);
    const bn = parseSliceNum(b);
    if (an !== null && bn !== null) return an - bn;
    return a.localeCompare(b);
  });
}

function parseSliceNum(sliceId: string): number | null {
  const m = /^S-(\d+)$/u.exec(sliceId);
  if (!m) return null;
  const n = Number.parseInt(m[1]!, 10);
  return Number.isFinite(n) ? n : null;
}
