import fs from "node:fs/promises";
import path from "node:path";
import { RUNTIME_ROOT } from "./constants.js";
import { CCLAW_AGENTS, agentMarkdown } from "./content/agents.js";
import { ensureDir, exists, writeFileSafe } from "./fs-utils.js";
import type { HarnessId } from "./types.js";

export const CCLAW_MARKER_START = "<!-- cclaw-start -->";
export const CCLAW_MARKER_END = "<!-- cclaw-end -->";

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const RUNTIME_AGENTS_BLOCK_SOURCE =
  `${escapeRegExp(CCLAW_MARKER_START)}[\\s\\S]*?${escapeRegExp(CCLAW_MARKER_END)}`;
const RUNTIME_AGENTS_BLOCK_PATTERN = new RegExp(RUNTIME_AGENTS_BLOCK_SOURCE, "u");
const RUNTIME_AGENTS_BLOCK_GLOBAL_PATTERN = new RegExp(RUNTIME_AGENTS_BLOCK_SOURCE, "gu");

export interface HarnessAdapter {
  id: HarnessId;
  commandDir: string;
}

export const HARNESS_ADAPTERS: Record<HarnessId, HarnessAdapter> = {
  claude: { id: "claude", commandDir: ".claude/commands" },
  cursor: { id: "cursor", commandDir: ".cursor/commands" },
  opencode: { id: "opencode", commandDir: ".opencode/commands" },
  codex: { id: "codex", commandDir: ".codex/commands" }
};

function agentsMdBlock(): string {
  return `${CCLAW_MARKER_START}
## Cclaw — Workflow Adapter

> Auto-generated by \`cclaw sync\`. Do not edit this managed block manually.
> Existing project rules in this repository take precedence over cclaw defaults.

### Activation Rule

Before responding to a coding request:
1. Read \`.cclaw/state/flow-state.json\` for the current stage.
2. Use \`/cc\` to start or \`/cc-next\` to continue the flow.
3. If no stage applies, respond normally.

### Commands (3 total)

| Command | Purpose |
|---|---|
| \`/cc\` | **Entry point.** No args = resume current stage. With prompt = start brainstorm with idea. |
| \`/cc-next\` | **Progression.** Advances to the next stage when current is complete. |
| \`/cc-learn\` | **Cross-cutting.** Capture or review project learnings. |

**Stage order:** brainstorm > scope > design > spec > plan > test > build > review > ship.
\`/cc-next\` loads the right stage skill automatically. Gates must pass before handoff.

### Verification Discipline

No completion claims without fresh evidence. No "Done" / "All good" / "Tests pass" without running the command in this message.

### Detail Level

- This managed AGENTS block is intentionally minimal for cross-project use.
- Detailed operating procedures live in \`.cclaw/skills/using-cclaw/SKILL.md\`.
${CCLAW_MARKER_END}`;
}


/** Removes the cclaw AGENTS.md block. */
export function stripCclawBlock(content: string): string {
  let updated = content.replace(RUNTIME_AGENTS_BLOCK_GLOBAL_PATTERN, "");
  return updated.replace(/\n{3,}/g, "\n\n").trim();
}

async function syncAgentsMd(projectRoot: string): Promise<void> {
  const agentsPath = path.join(projectRoot, "AGENTS.md");
  const block = agentsMdBlock();

  if (!(await exists(agentsPath))) {
    await writeFileSafe(agentsPath, `# AGENTS\n\n${block}\n`);
    return;
  }

  const content = await fs.readFile(agentsPath, "utf8");
  if (RUNTIME_AGENTS_BLOCK_PATTERN.test(content)) {
    const stripped = stripCclawBlock(content);
    const updated = stripped.length > 0 ? `${stripped}\n\n${block}\n` : `${block}\n`;
    await writeFileSafe(agentsPath, updated);
  } else {
    await writeFileSafe(agentsPath, `${content.trimEnd()}\n\n${block}\n`);
  }
}

export async function removeCclawFromAgentsMd(projectRoot: string): Promise<void> {
  const agentsPath = path.join(projectRoot, "AGENTS.md");
  if (!(await exists(agentsPath))) return;

  const content = await fs.readFile(agentsPath, "utf8");
  if (!RUNTIME_AGENTS_BLOCK_PATTERN.test(content)) return;

  const stripped = stripCclawBlock(content);
  if (stripped.replace(/\s/g, "").length === 0) {
    await fs.rm(agentsPath, { force: true });
  } else {
    await writeFileSafe(agentsPath, `${stripped}\n`);
  }
}

function utilityShimContent(harness: HarnessId, command: string, skillFolder: string, commandFile: string): string {
  return `---
name: cc-${command}
description: Generated shim for ${harness}. Utility command — not a flow stage.
source: generated-by-cclaw
---

# cclaw ${command}

Load and execute:
1. \`.cclaw/skills/${skillFolder}/SKILL.md\`
2. \`.cclaw/commands/${commandFile}\`

This is a utility command (not a flow stage). It does not advance flow state.
`;
}

async function syncAgentFiles(projectRoot: string): Promise<void> {
  const agentsDir = path.join(projectRoot, RUNTIME_ROOT, "agents");
  await ensureDir(agentsDir);
  for (const agent of CCLAW_AGENTS) {
    await writeFileSafe(
      path.join(agentsDir, `${agent.name}.md`),
      agentMarkdown(agent)
    );
  }
}

export async function syncHarnessShims(projectRoot: string, harnesses: HarnessId[]): Promise<void> {
  for (const harness of harnesses) {
    const adapter = (HARNESS_ADAPTERS as Record<string, { commandDir: string }>)[harness];
    if (!adapter) {
      continue;
    }
    const commandDir = path.join(projectRoot, adapter.commandDir);
    await ensureDir(commandDir);

    await writeFileSafe(
      path.join(commandDir, "cc.md"),
      utilityShimContent(harness, "cc", "flow-start", "start.md")
    );
    await writeFileSafe(
      path.join(commandDir, "cc-next.md"),
      utilityShimContent(harness, "next", "flow-next-step", "next.md")
    );
    await writeFileSafe(
      path.join(commandDir, "cc-learn.md"),
      utilityShimContent(harness, "learn", "learnings", "learn.md")
    );
  }

  await syncAgentFiles(projectRoot);
  await syncAgentsMd(projectRoot);
}
