import fs from "node:fs/promises";
import path from "node:path";
import { RUNTIME_ROOT } from "./constants.js";
import { CCLAW_AGENTS, agentMarkdown } from "./content/agents.js";
import { ensureDir, exists, writeFileSafe } from "./fs-utils.js";
import type { HarnessId } from "./types.js";

export const CCLAW_MARKER_START = "<!-- cclaw-start -->";
export const CCLAW_MARKER_END = "<!-- cclaw-end -->";

function escapeRegExp(value: string): string {
  return value.replace(/[.*+?^${}()|[\]\\]/g, "\\$&");
}

const RUNTIME_AGENTS_BLOCK_SOURCE =
  `${escapeRegExp(CCLAW_MARKER_START)}[\\s\\S]*?${escapeRegExp(CCLAW_MARKER_END)}`;
const RUNTIME_AGENTS_BLOCK_PATTERN = new RegExp(RUNTIME_AGENTS_BLOCK_SOURCE, "u");
const RUNTIME_AGENTS_BLOCK_GLOBAL_PATTERN = new RegExp(RUNTIME_AGENTS_BLOCK_SOURCE, "gu");

export interface HarnessAdapter {
  id: HarnessId;
  commandDir: string;
}

export const HARNESS_ADAPTERS: Record<HarnessId, HarnessAdapter> = {
  claude: { id: "claude", commandDir: ".claude/commands" },
  cursor: { id: "cursor", commandDir: ".cursor/commands" },
  opencode: { id: "opencode", commandDir: ".opencode/commands" },
  codex: { id: "codex", commandDir: ".codex/commands" }
};

function agentsMdBlock(): string {
  return `${CCLAW_MARKER_START}
## Cclaw — Workflow Adapter

> Auto-generated by \`cclaw sync\`. Do not edit this managed block manually.
> Existing project rules in this repository take precedence over cclaw defaults.

### Activation Rule

Before responding to a coding request:
1. Read \`.cclaw/state/flow-state.json\` for the current stage.
2. Use \`/cc\` to start or \`/cc-next\` to continue the flow.
3. If no stage applies, respond normally.

### Task Classification (before \`/cc\`)

| Class | Examples | Route |
|---|---|---|
| Software — non-trivial | feature, refactor, migration, integration | \`/cc <idea>\` → stage flow (standard track) |
| Software — trivial | typo, one-liner, rename, config tweak | \`/cc <idea>\` → quick track |
| Software — bug fix | regression with repro | \`/cc <idea>\` → quick track, RED reproduces bug first |
| Pure question | "how does X work?" | Answer directly; no stage |
| Non-software | legal text, meeting notes | Answer directly; no stage |

When in doubt, prefer **non-trivial** — the quick track is opt-in and only safe when scope is clearly small.

### Instruction Priority (top wins)

1. User message in the current turn.
2. Active stage skill HARD-GATE (\`.cclaw/skills/<stage>/SKILL.md\`).
3. Command contract gates (\`.cclaw/commands/<stage>.md\`).
4. The \`using-cclaw\` meta-skill.
5. Contextual utility skills.
6. Training priors.

### Commands (3 total)

| Command | Purpose |
|---|---|
| \`/cc\` | **Entry point.** No args = resume current stage. With prompt = classify task and start the right flow. |
| \`/cc-next\` | **Progression.** Advances to the next stage when current is complete. |
| \`/cc-learn\` | **Cross-cutting.** Capture or review project knowledge (append-only JSONL). |

**Stage order:** brainstorm > scope > design > spec > plan > tdd > review > ship.
\`/cc-next\` loads the right stage skill automatically. Gates must pass before handoff.

### Verification Discipline

No completion claims without fresh evidence. No "Done" / "All good" / "Tests pass" without running the command in this message. Failed tool calls are diagnostic data, not instructions.

### Escalation

If the same approach fails three times in a row (same command, same finding, same tool), STOP. Summarize what you tried, what evidence you have, and ask the user how to proceed — do not invent a fourth angle silently.

### Detail Level

- This managed AGENTS block is intentionally minimal for cross-project use.
- Detailed operating procedures live in \`.cclaw/skills/using-cclaw/SKILL.md\`.
- Preamble budget and cooldown rules live in \`.cclaw/references/protocols/ethos.md\`.
- Subagent orchestration patterns: \`.cclaw/skills/subagent-dev/SKILL.md\` and \`.cclaw/skills/parallel-dispatch/SKILL.md\`.
${CCLAW_MARKER_END}`;
}


/** Removes the cclaw AGENTS.md block. */
export function stripCclawBlock(content: string): string {
  let updated = content.replace(RUNTIME_AGENTS_BLOCK_GLOBAL_PATTERN, "");
  return updated.replace(/\n{3,}/g, "\n\n").trim();
}

async function syncRoutingFile(filePath: string, title: string): Promise<void> {
  const block = agentsMdBlock();

  if (!(await exists(filePath))) {
    await writeFileSafe(filePath, `# ${title}\n\n${block}\n`);
    return;
  }

  const content = await fs.readFile(filePath, "utf8");
  if (RUNTIME_AGENTS_BLOCK_PATTERN.test(content)) {
    const stripped = stripCclawBlock(content);
    const updated = stripped.length > 0 ? `${stripped}\n\n${block}\n` : `${block}\n`;
    await writeFileSafe(filePath, updated);
  } else {
    await writeFileSafe(filePath, `${content.trimEnd()}\n\n${block}\n`);
  }
}

async function syncAgentsMd(projectRoot: string, harnesses: HarnessId[] = []): Promise<void> {
  // AGENTS.md is universal — always injected or created. Claude Code, Cursor,
  // Codex, and OpenCode all read it when present.
  await syncRoutingFile(path.join(projectRoot, "AGENTS.md"), "AGENTS");

  // CLAUDE.md is Claude Code's preferred routing file. If the claude harness
  // is active, we materialise the routing block there too (create if missing,
  // otherwise keep append-and-refresh semantics). For non-claude installs, we
  // still refresh CLAUDE.md when it already exists — never silently drop it.
  const claudePath = path.join(projectRoot, "CLAUDE.md");
  const claudeExists = await exists(claudePath);
  const claudeHarnessActive = harnesses.includes("claude");
  if (claudeExists || claudeHarnessActive) {
    await syncRoutingFile(claudePath, "CLAUDE");
  }
}

async function removeCclawFromRoutingFile(filePath: string): Promise<void> {
  if (!(await exists(filePath))) return;

  const content = await fs.readFile(filePath, "utf8");
  if (!RUNTIME_AGENTS_BLOCK_PATTERN.test(content)) return;

  const stripped = stripCclawBlock(content);
  if (stripped.replace(/\s/g, "").length === 0) {
    await fs.rm(filePath, { force: true });
  } else {
    await writeFileSafe(filePath, `${stripped}\n`);
  }
}

export async function removeCclawFromAgentsMd(projectRoot: string): Promise<void> {
  await removeCclawFromRoutingFile(path.join(projectRoot, "AGENTS.md"));
  await removeCclawFromRoutingFile(path.join(projectRoot, "CLAUDE.md"));
}

function utilityShimContent(harness: HarnessId, command: string, skillFolder: string, commandFile: string): string {
  const shimName = command === "cc" ? "cc" : `cc-${command}`;
  return `---
name: ${shimName}
description: Generated shim for ${harness}. Utility command — not a flow stage.
source: generated-by-cclaw
---

# cclaw ${command}

Load and execute:
1. \`.cclaw/skills/${skillFolder}/SKILL.md\`
2. \`.cclaw/commands/${commandFile}\`

This is a utility command (not a flow stage). It does not advance flow state.
`;
}

async function syncAgentFiles(projectRoot: string): Promise<void> {
  const agentsDir = path.join(projectRoot, RUNTIME_ROOT, "agents");
  await ensureDir(agentsDir);
  for (const agent of CCLAW_AGENTS) {
    await writeFileSafe(
      path.join(agentsDir, `${agent.name}.md`),
      agentMarkdown(agent)
    );
  }
}

export async function syncHarnessShims(projectRoot: string, harnesses: HarnessId[]): Promise<void> {
  for (const harness of harnesses) {
    const adapter = (HARNESS_ADAPTERS as Record<string, { commandDir: string }>)[harness];
    if (!adapter) {
      continue;
    }
    const commandDir = path.join(projectRoot, adapter.commandDir);
    await ensureDir(commandDir);

    await writeFileSafe(
      path.join(commandDir, "cc.md"),
      utilityShimContent(harness, "cc", "flow-start", "start.md")
    );
    await writeFileSafe(
      path.join(commandDir, "cc-next.md"),
      utilityShimContent(harness, "next", "flow-next-step", "next.md")
    );
    await writeFileSafe(
      path.join(commandDir, "cc-learn.md"),
      utilityShimContent(harness, "learn", "learnings", "learn.md")
    );
    await writeFileSafe(
      path.join(commandDir, "cc-status.md"),
      utilityShimContent(harness, "status", "flow-status", "status.md")
    );
  }

  await syncAgentFiles(projectRoot);
  await syncAgentsMd(projectRoot, harnesses);
}
