import fs from "node:fs/promises";
import path from "node:path";
import { CCLAW_VERSION, RUNTIME_ROOT } from "./constants.js";
import { ACTIVE_ARTIFACT_DIRS, type ArtifactStage } from "./artifact-paths.js";
import { CORE_AGENTS, renderAgentMarkdown } from "./content/core-agents.js";
import { ARTIFACT_TEMPLATES, planTemplateForSlug, templateBody } from "./content/artifact-templates.js";
import { AUTO_TRIGGER_SKILLS } from "./content/skills.js";
import { EXAMPLES, EXAMPLES_INDEX } from "./content/examples.js";
import { REFERENCE_PATTERNS, REFERENCE_PATTERNS_INDEX } from "./content/reference-patterns.js";
import { STAGE_PLAYBOOKS, STAGE_PLAYBOOKS_INDEX } from "./content/stage-playbooks.js";
import { RESEARCH_PLAYBOOKS, RESEARCH_PLAYBOOKS_INDEX } from "./content/research-playbooks.js";
import { RECOVERY_PLAYBOOKS, RECOVERY_INDEX } from "./content/recovery.js";
import { ANTIPATTERNS } from "./content/antipatterns.js";
import { DECISION_PROTOCOL } from "./content/decision-protocol.js";
import { META_SKILL } from "./content/meta-skill.js";
import {
  COMMIT_HELPER_HOOK_SPEC,
  NODE_HOOKS,
  SESSION_START_HOOK_SPEC,
  STOP_HANDOFF_HOOK_SPEC,
  type NodeHookSpec
} from "./content/node-hooks.js";
import { renderStartCommand } from "./content/start-command.js";
import { renderCancelCommand } from "./content/cancel-command.js";
import { renderIdeaCommand } from "./content/idea-command.js";
import { ensureDir, exists, removePath, writeFileSafe } from "./fs-utils.js";
import { ensureRunSystem } from "./run-persistence.js";
import { createDefaultConfig, readConfig, renderConfig, type CclawConfig } from "./config.js";
import { HARNESS_IDS, type HarnessId } from "./types.js";
import { ironLawsMarkdown } from "./content/iron-laws.js";

export interface HarnessLayout {
  id: HarnessId;
  commandsDir: string;
  agentsDir: string;
  skillsDir: string;
  hooksConfig: { dir: string; fileName: string } | null;
}

const HARNESS_LAYOUTS: Record<HarnessId, HarnessLayout> = {
  claude: {
    id: "claude",
    commandsDir: ".claude/commands",
    agentsDir: ".claude/agents",
    skillsDir: ".claude/skills/cclaw",
    hooksConfig: { dir: ".claude/hooks", fileName: "hooks.json" }
  },
  cursor: {
    id: "cursor",
    commandsDir: ".cursor/commands",
    agentsDir: ".cursor/agents",
    skillsDir: ".cursor/skills/cclaw",
    hooksConfig: { dir: ".cursor", fileName: "hooks.json" }
  },
  opencode: {
    id: "opencode",
    commandsDir: ".opencode/commands",
    agentsDir: ".opencode/agents",
    skillsDir: ".opencode/skills/cclaw",
    hooksConfig: { dir: ".opencode/plugins", fileName: "cclaw-plugin.mjs" }
  },
  codex: {
    id: "codex",
    commandsDir: ".codex/commands",
    agentsDir: ".codex/agents",
    skillsDir: ".codex/skills/cclaw",
    hooksConfig: { dir: ".codex", fileName: "hooks.json" }
  }
};

export interface SyncOptions {
  cwd: string;
  harnesses?: HarnessId[];
  generateAgentsBlock?: boolean;
}

export interface SyncResult {
  installedHarnesses: HarnessId[];
  configPath: string;
}

const AGENTS_BLOCK_BEGIN = "<!-- cclaw-routing:start";
const AGENTS_BLOCK_END = "<!-- cclaw-routing:end -->";

export async function ensureRuntimeRoot(projectRoot: string): Promise<void> {
  const root = path.join(projectRoot, RUNTIME_ROOT);
  for (const dir of [
    "state",
    ...Object.values(ACTIVE_ARTIFACT_DIRS),
    "shipped",
    "cancelled",
    "agents",
    "hooks",
    "skills",
    "templates",
    "runbooks",
    "patterns",
    "research",
    "recovery",
    "examples"
  ]) {
    await ensureDir(path.join(root, dir));
  }
  await writeFileSafe(
    path.join(root, ".gitkeep"),
    "cclaw v8 runtime root. Generated by cclaw-cli; safe to keep in version control.\n"
  );
}

async function writeHookFile(projectRoot: string, hook: NodeHookSpec): Promise<void> {
  const hookPath = path.join(projectRoot, RUNTIME_ROOT, "hooks", hook.fileName);
  await writeFileSafe(hookPath, hook.body);
  await fs.chmod(hookPath, 0o755);
}

async function writeAgentFiles(projectRoot: string): Promise<void> {
  for (const agent of CORE_AGENTS) {
    const agentPath = path.join(projectRoot, RUNTIME_ROOT, "agents", `${agent.id}.md`);
    await writeFileSafe(agentPath, renderAgentMarkdown(agent));
  }
}

async function writeRuntimeSkills(projectRoot: string): Promise<void> {
  for (const skill of AUTO_TRIGGER_SKILLS) {
    const target = path.join(projectRoot, RUNTIME_ROOT, "skills", skill.fileName);
    await writeFileSafe(target, skill.body);
  }
}

async function writeTemplates(projectRoot: string): Promise<void> {
  for (const template of ARTIFACT_TEMPLATES) {
    const target = path.join(projectRoot, RUNTIME_ROOT, "templates", template.fileName);
    await writeFileSafe(target, template.body);
  }
  await writeFileSafe(
    path.join(projectRoot, RUNTIME_ROOT, "templates", "iron-laws.md"),
    ironLawsMarkdown()
  );
}

async function writeIdeasSeed(projectRoot: string): Promise<void> {
  const target = path.join(projectRoot, RUNTIME_ROOT, "ideas.md");
  if (await exists(target)) return;
  await writeFileSafe(target, templateBody("ideas"));
}

async function writeStageRunbooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, RUNTIME_ROOT, "runbooks");
  for (const playbook of STAGE_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), STAGE_PLAYBOOKS_INDEX);
}

async function writeReferencePatterns(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, RUNTIME_ROOT, "patterns");
  for (const pattern of REFERENCE_PATTERNS) {
    await writeFileSafe(path.join(dir, pattern.fileName), pattern.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), REFERENCE_PATTERNS_INDEX);
}

async function writeResearchPlaybooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, RUNTIME_ROOT, "research");
  for (const playbook of RESEARCH_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), RESEARCH_PLAYBOOKS_INDEX);
}

async function writeRecoveryPlaybooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, RUNTIME_ROOT, "recovery");
  for (const playbook of RECOVERY_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), RECOVERY_INDEX);
}

async function writeExamples(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, RUNTIME_ROOT, "examples");
  for (const example of EXAMPLES) {
    await writeFileSafe(path.join(dir, example.fileName), example.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), EXAMPLES_INDEX);
}

async function writeAntipatterns(projectRoot: string): Promise<void> {
  await writeFileSafe(path.join(projectRoot, RUNTIME_ROOT, "antipatterns.md"), ANTIPATTERNS);
}

async function writeDecisionProtocol(projectRoot: string): Promise<void> {
  await writeFileSafe(
    path.join(projectRoot, RUNTIME_ROOT, "decisions", "decision-protocol.md"),
    DECISION_PROTOCOL
  );
}

async function writeMetaSkill(projectRoot: string): Promise<void> {
  await writeFileSafe(
    path.join(projectRoot, RUNTIME_ROOT, "skills", "cclaw-meta.md"),
    META_SKILL
  );
}

async function writeHarnessAssets(projectRoot: string, layout: HarnessLayout): Promise<void> {
  await ensureDir(path.join(projectRoot, layout.commandsDir));
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc.md"), renderStartCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-cancel.md"), renderCancelCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-idea.md"), renderIdeaCommand());

  await ensureDir(path.join(projectRoot, layout.agentsDir));
  for (const agent of CORE_AGENTS) {
    await writeFileSafe(
      path.join(projectRoot, layout.agentsDir, `${agent.id}.md`),
      renderAgentMarkdown(agent)
    );
  }

  await ensureDir(path.join(projectRoot, layout.skillsDir));
  for (const skill of AUTO_TRIGGER_SKILLS) {
    await writeFileSafe(path.join(projectRoot, layout.skillsDir, skill.fileName), skill.body);
  }

  if (layout.hooksConfig) {
    const { dir, fileName } = layout.hooksConfig;
    await ensureDir(path.join(projectRoot, dir));
    if (fileName.endsWith(".mjs")) {
      const moduleBody = `// cclaw v${CCLAW_VERSION} opencode plugin (minimal). Wires session-start and stop-handoff hooks.\nimport { spawn } from \"node:child_process\";\nimport path from \"node:path\";\nfunction run(filePath) {\n  return () => spawn(process.execPath, [path.join(\".cclaw\", \"hooks\", filePath)], { stdio: \"inherit\" });\n}\nexport default {\n  events: {\n    \"session.start\": run(\"session-start.mjs\"),\n    \"session.stop\": run(\"stop-handoff.mjs\")\n  }\n};\n`;
      await writeFileSafe(path.join(projectRoot, dir, fileName), moduleBody);
    } else {
      const hooksJson = {
        version: 1,
        generatedBy: `cclaw-cli@${CCLAW_VERSION}`,
        events: {
          "session.start": [
            { command: "node", args: [`./${RUNTIME_ROOT}/hooks/${SESSION_START_HOOK_SPEC.fileName}`] }
          ],
          "session.stop": [
            { command: "node", args: [`./${RUNTIME_ROOT}/hooks/${STOP_HANDOFF_HOOK_SPEC.fileName}`] }
          ]
        }
      };
      await writeFileSafe(path.join(projectRoot, dir, fileName), `${JSON.stringify(hooksJson, null, 2)}\n`);
    }
  }
}

async function writeAgentsBlock(projectRoot: string): Promise<void> {
  const targetPath = path.join(projectRoot, "AGENTS.md");
  const block = templateBody("agents-block");
  let next: string;
  if (await exists(targetPath)) {
    const current = await fs.readFile(targetPath, "utf8");
    if (current.includes(AGENTS_BLOCK_BEGIN) && current.includes(AGENTS_BLOCK_END)) {
      const start = current.indexOf(AGENTS_BLOCK_BEGIN);
      const end = current.indexOf(AGENTS_BLOCK_END) + AGENTS_BLOCK_END.length;
      next = `${current.slice(0, start)}${block.trim()}\n${current.slice(end).replace(/^\n+/u, "")}`;
    } else {
      next = `${current.replace(/\n+$/u, "")}\n\n${block}\n`;
    }
  } else {
    next = block.endsWith("\n") ? block : `${block}\n`;
  }
  await writeFileSafe(targetPath, next);
}

async function writeConfig(projectRoot: string, config: CclawConfig): Promise<string> {
  const configPath = path.join(projectRoot, RUNTIME_ROOT, "config.yaml");
  await writeFileSafe(configPath, renderConfig(config));
  return configPath;
}

export async function syncCclaw(options: SyncOptions): Promise<SyncResult> {
  const projectRoot = options.cwd;
  await ensureRuntimeRoot(projectRoot);
  const existing = await readConfig(projectRoot);
  const harnesses = options.harnesses ?? existing?.harnesses ?? ["cursor"];
  for (const harness of harnesses) {
    if (!HARNESS_IDS.includes(harness)) {
      throw new Error(`Unknown harness: ${harness}. Supported: ${HARNESS_IDS.join(", ")}`);
    }
  }
  const config = existing
    ? { ...existing, version: CCLAW_VERSION, flowVersion: "8" as const, harnesses }
    : createDefaultConfig(harnesses);
  await ensureRunSystem(projectRoot);
  await writeAgentFiles(projectRoot);
  for (const hook of NODE_HOOKS) {
    await writeHookFile(projectRoot, hook);
  }
  await writeRuntimeSkills(projectRoot);
  await writeMetaSkill(projectRoot);
  await writeTemplates(projectRoot);
  await writeStageRunbooks(projectRoot);
  await writeReferencePatterns(projectRoot);
  await writeResearchPlaybooks(projectRoot);
  await writeRecoveryPlaybooks(projectRoot);
  await writeExamples(projectRoot);
  await writeAntipatterns(projectRoot);
  await writeDecisionProtocol(projectRoot);
  await writeIdeasSeed(projectRoot);
  for (const harness of harnesses) {
    await writeHarnessAssets(projectRoot, HARNESS_LAYOUTS[harness]);
  }
  if (options.generateAgentsBlock !== false) {
    await writeAgentsBlock(projectRoot);
  }
  const configPath = await writeConfig(projectRoot, config);
  return { installedHarnesses: harnesses, configPath };
}

export async function initCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

async function removeAgentsBlock(projectRoot: string): Promise<void> {
  const target = path.join(projectRoot, "AGENTS.md");
  if (!(await exists(target))) return;
  const current = await fs.readFile(target, "utf8");
  if (!current.includes(AGENTS_BLOCK_BEGIN) || !current.includes(AGENTS_BLOCK_END)) return;
  const start = current.indexOf(AGENTS_BLOCK_BEGIN);
  const end = current.indexOf(AGENTS_BLOCK_END) + AGENTS_BLOCK_END.length;
  const next = `${current.slice(0, start)}${current.slice(end).replace(/^\n+/u, "")}`;
  if (next.trim().length === 0) {
    await removePath(target);
  } else {
    await writeFileSafe(target, next);
  }
}

export async function uninstallCclaw(options: { cwd: string }): Promise<void> {
  const projectRoot = options.cwd;
  const config = await readConfig(projectRoot);
  const harnesses = config?.harnesses ?? (HARNESS_IDS as readonly HarnessId[]);
  await removePath(path.join(projectRoot, RUNTIME_ROOT));
  for (const harness of harnesses as HarnessId[]) {
    const layout = HARNESS_LAYOUTS[harness];
    for (const filename of ["cc.md", "cc-cancel.md", "cc-idea.md"]) {
      await removePath(path.join(projectRoot, layout.commandsDir, filename));
    }
    for (const agent of CORE_AGENTS) {
      await removePath(path.join(projectRoot, layout.agentsDir, `${agent.id}.md`));
    }
    await removePath(path.join(projectRoot, layout.skillsDir));
    if (layout.hooksConfig) {
      await removePath(path.join(projectRoot, layout.hooksConfig.dir, layout.hooksConfig.fileName));
    }
    if (await exists(path.join(projectRoot, layout.commandsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.commandsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.commandsDir));
    }
    if (await exists(path.join(projectRoot, layout.agentsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.agentsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.agentsDir));
    }
  }
  await removeAgentsBlock(projectRoot);
}

export async function upgradeCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

export function planSeedForSlug(slug: string): string {
  return planTemplateForSlug(slug);
}

export const HARNESS_LAYOUT_TABLE = HARNESS_LAYOUTS;
export type { NodeHookSpec };
export const COMMIT_HELPER_HOOK = COMMIT_HELPER_HOOK_SPEC;
