import fs from "node:fs/promises";
import path from "node:path";
import {
  CANCELLED_DIR_REL_PATH,
  CCLAW_VERSION,
  FLOWS_ROOT,
  HOOKS_REL_PATH,
  LIB_ROOT,
  RUNTIME_ROOT,
  SHIPPED_DIR_REL_PATH,
  STATE_REL_PATH
} from "./constants.js";
import { CORE_AGENTS, renderAgentMarkdown } from "./content/core-agents.js";
import { ARTIFACT_TEMPLATES, planTemplateForSlug, templateBody } from "./content/artifact-templates.js";
import { AUTO_TRIGGER_SKILLS } from "./content/skills.js";
import { EXAMPLES, EXAMPLES_INDEX } from "./content/examples.js";
import { REFERENCE_PATTERNS, REFERENCE_PATTERNS_INDEX } from "./content/reference-patterns.js";
import { STAGE_PLAYBOOKS, STAGE_PLAYBOOKS_INDEX } from "./content/stage-playbooks.js";
import { RESEARCH_PLAYBOOKS, RESEARCH_PLAYBOOKS_INDEX } from "./content/research-playbooks.js";
import { RECOVERY_PLAYBOOKS, RECOVERY_INDEX } from "./content/recovery.js";
import { ANTIPATTERNS } from "./content/antipatterns.js";
import { DECISION_PROTOCOL } from "./content/decision-protocol.js";
import { META_SKILL } from "./content/meta-skill.js";
import {
  COMMIT_HELPER_HOOK_SPEC,
  NODE_HOOKS,
  SESSION_START_HOOK_SPEC,
  STOP_HANDOFF_HOOK_SPEC,
  type NodeHookSpec
} from "./content/node-hooks.js";
import { renderStartCommand } from "./content/start-command.js";
import { renderCancelCommand } from "./content/cancel-command.js";
import { renderIdeaCommand } from "./content/idea-command.js";
import { ensureDir, exists, removePath, writeFileSafe } from "./fs-utils.js";
import { ensureRunSystem } from "./run-persistence.js";
import { createDefaultConfig, readConfig, renderConfig, type CclawConfig } from "./config.js";
import { detectHarnesses, NO_HARNESS_DETECTED_MESSAGE } from "./harness-detect.js";
import { ensureGitignorePatterns, removeGitignorePatterns } from "./gitignore.js";
import { isInteractive, runPicker } from "./harness-prompt.js";
import { HARNESS_IDS, type HarnessId } from "./types.js";
import { ironLawsMarkdown } from "./content/iron-laws.js";
import type { ProgressEvent, SummaryCounts } from "./ui.js";

export interface HarnessLayout {
  id: HarnessId;
  commandsDir: string;
  agentsDir: string;
  skillsDir: string;
  hooksConfig: { dir: string; fileName: string } | null;
}

const HARNESS_LAYOUTS: Record<HarnessId, HarnessLayout> = {
  claude: {
    id: "claude",
    commandsDir: ".claude/commands",
    agentsDir: ".claude/agents",
    skillsDir: ".claude/skills/cclaw",
    hooksConfig: { dir: ".claude/hooks", fileName: "hooks.json" }
  },
  cursor: {
    id: "cursor",
    commandsDir: ".cursor/commands",
    agentsDir: ".cursor/agents",
    skillsDir: ".cursor/skills/cclaw",
    hooksConfig: { dir: ".cursor", fileName: "hooks.json" }
  },
  opencode: {
    id: "opencode",
    commandsDir: ".opencode/commands",
    agentsDir: ".opencode/agents",
    skillsDir: ".opencode/skills/cclaw",
    hooksConfig: { dir: ".opencode/plugins", fileName: "cclaw-plugin.mjs" }
  },
  codex: {
    id: "codex",
    commandsDir: ".codex/commands",
    agentsDir: ".codex/agents",
    skillsDir: ".codex/skills/cclaw",
    hooksConfig: { dir: ".codex", fileName: "hooks.json" }
  }
};

export interface SyncOptions {
  cwd: string;
  harnesses?: HarnessId[];
  /**
   * When true (default for `init` from a real TTY), `cclaw` shows the
   * interactive harness picker if no `--harness` flag and no existing
   * `.cclaw/config.yaml` are available. Set to false in CI/non-TTY paths
   * (smoke scripts, programmatic callers) to fall back to auto-detect or
   * a hard error if nothing is found.
   */
  interactive?: boolean;
  /**
   * Optional progress callback invoked once per major install step
   * (agents written, hooks installed, etc.). The CLI wires this to a
   * `✓` line printer; programmatic callers (smoke, tests, MCP wrappers)
   * can leave it undefined to stay silent.
   */
  onProgress?: (event: ProgressEvent) => void;
}

export interface SyncResult {
  installedHarnesses: HarnessId[];
  configPath: string;
  /**
   * Counts of every asset family written during this sync. Surfaced so
   * the CLI can render an "Installed: ..." summary block, and so tests
   * can assert against concrete numbers without re-reading the disk.
   */
  counts: SummaryCounts;
}

export async function ensureRuntimeRoot(projectRoot: string): Promise<void> {
  const root = path.join(projectRoot, RUNTIME_ROOT);
  for (const dir of [
    STATE_REL_PATH,
    HOOKS_REL_PATH,
    FLOWS_ROOT,
    SHIPPED_DIR_REL_PATH,
    CANCELLED_DIR_REL_PATH,
    LIB_ROOT,
    path.join(LIB_ROOT, "agents"),
    path.join(LIB_ROOT, "skills"),
    path.join(LIB_ROOT, "templates"),
    path.join(LIB_ROOT, "runbooks"),
    path.join(LIB_ROOT, "patterns"),
    path.join(LIB_ROOT, "research"),
    path.join(LIB_ROOT, "recovery"),
    path.join(LIB_ROOT, "examples")
  ]) {
    await ensureDir(path.join(projectRoot, dir));
  }
  await writeFileSafe(
    path.join(root, ".gitkeep"),
    "cclaw runtime root. Generated by cclaw-cli; safe to keep in version control.\n"
  );
}

async function writeHookFile(projectRoot: string, hook: NodeHookSpec): Promise<void> {
  const hookPath = path.join(projectRoot, HOOKS_REL_PATH, hook.fileName);
  await writeFileSafe(hookPath, hook.body);
  await fs.chmod(hookPath, 0o755);
}

async function writeAgentFiles(projectRoot: string): Promise<void> {
  for (const agent of CORE_AGENTS) {
    const agentPath = path.join(projectRoot, LIB_ROOT, "agents", `${agent.id}.md`);
    await writeFileSafe(agentPath, renderAgentMarkdown(agent));
  }
}

async function writeRuntimeSkills(projectRoot: string): Promise<void> {
  for (const skill of AUTO_TRIGGER_SKILLS) {
    const target = path.join(projectRoot, LIB_ROOT, "skills", skill.fileName);
    await writeFileSafe(target, skill.body);
  }
}

async function writeTemplates(projectRoot: string): Promise<void> {
  for (const template of ARTIFACT_TEMPLATES) {
    const target = path.join(projectRoot, LIB_ROOT, "templates", template.fileName);
    await writeFileSafe(target, template.body);
  }
  await writeFileSafe(
    path.join(projectRoot, LIB_ROOT, "templates", "iron-laws.md"),
    ironLawsMarkdown()
  );
}

async function writeIdeasSeed(projectRoot: string): Promise<void> {
  const target = path.join(projectRoot, RUNTIME_ROOT, "ideas.md");
  if (await exists(target)) return;
  await writeFileSafe(target, templateBody("ideas"));
}

async function writeStageRunbooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, LIB_ROOT, "runbooks");
  for (const playbook of STAGE_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), STAGE_PLAYBOOKS_INDEX);
}

async function writeReferencePatterns(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, LIB_ROOT, "patterns");
  for (const pattern of REFERENCE_PATTERNS) {
    await writeFileSafe(path.join(dir, pattern.fileName), pattern.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), REFERENCE_PATTERNS_INDEX);
}

async function writeResearchPlaybooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, LIB_ROOT, "research");
  for (const playbook of RESEARCH_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), RESEARCH_PLAYBOOKS_INDEX);
}

async function writeRecoveryPlaybooks(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, LIB_ROOT, "recovery");
  for (const playbook of RECOVERY_PLAYBOOKS) {
    await writeFileSafe(path.join(dir, playbook.fileName), playbook.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), RECOVERY_INDEX);
}

async function writeExamples(projectRoot: string): Promise<void> {
  const dir = path.join(projectRoot, LIB_ROOT, "examples");
  for (const example of EXAMPLES) {
    await writeFileSafe(path.join(dir, example.fileName), example.body);
  }
  await writeFileSafe(path.join(dir, "index.md"), EXAMPLES_INDEX);
}

async function writeAntipatterns(projectRoot: string): Promise<void> {
  await writeFileSafe(path.join(projectRoot, LIB_ROOT, "antipatterns.md"), ANTIPATTERNS);
}

async function writeDecisionProtocol(projectRoot: string): Promise<void> {
  await writeFileSafe(
    path.join(projectRoot, LIB_ROOT, "decision-protocol.md"),
    DECISION_PROTOCOL
  );
}

async function writeMetaSkill(projectRoot: string): Promise<void> {
  await writeFileSafe(
    path.join(projectRoot, LIB_ROOT, "skills", "cclaw-meta.md"),
    META_SKILL
  );
}

async function writeHarnessAssets(projectRoot: string, layout: HarnessLayout): Promise<void> {
  await ensureDir(path.join(projectRoot, layout.commandsDir));
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc.md"), renderStartCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-cancel.md"), renderCancelCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-idea.md"), renderIdeaCommand());

  await ensureDir(path.join(projectRoot, layout.agentsDir));
  for (const agent of CORE_AGENTS) {
    await writeFileSafe(
      path.join(projectRoot, layout.agentsDir, `${agent.id}.md`),
      renderAgentMarkdown(agent)
    );
  }

  await ensureDir(path.join(projectRoot, layout.skillsDir));
  for (const skill of AUTO_TRIGGER_SKILLS) {
    await writeFileSafe(path.join(projectRoot, layout.skillsDir, skill.fileName), skill.body);
  }

  if (layout.hooksConfig) {
    const { dir, fileName } = layout.hooksConfig;
    await ensureDir(path.join(projectRoot, dir));
    if (fileName.endsWith(".mjs")) {
      const moduleBody = `// cclaw opencode plugin (minimal). Wires session-start and stop-handoff hooks.\nimport { spawn } from \"node:child_process\";\nimport path from \"node:path\";\nfunction run(filePath) {\n  return () => spawn(process.execPath, [path.join(\"${HOOKS_REL_PATH}\", filePath)], { stdio: \"inherit\" });\n}\nexport default {\n  events: {\n    \"session.start\": run(\"session-start.mjs\"),\n    \"session.stop\": run(\"stop-handoff.mjs\")\n  }\n};\n`;
      await writeFileSafe(path.join(projectRoot, dir, fileName), moduleBody);
    } else {
      const hooksJson = {
        version: 1,
        generatedBy: `cclaw-cli@${CCLAW_VERSION}`,
        events: {
          "session.start": [
            { command: "node", args: [`./${HOOKS_REL_PATH}/${SESSION_START_HOOK_SPEC.fileName}`] }
          ],
          "session.stop": [
            { command: "node", args: [`./${HOOKS_REL_PATH}/${STOP_HANDOFF_HOOK_SPEC.fileName}`] }
          ]
        }
      };
      await writeFileSafe(path.join(projectRoot, dir, fileName), `${JSON.stringify(hooksJson, null, 2)}\n`);
    }
  }
}

async function writeConfig(projectRoot: string, config: CclawConfig): Promise<string> {
  const configPath = path.join(projectRoot, RUNTIME_ROOT, "config.yaml");
  await writeFileSafe(configPath, renderConfig(config));
  return configPath;
}

async function resolveHarnesses(
  projectRoot: string,
  fromOptions: HarnessId[] | undefined,
  fromConfig: HarnessId[] | undefined,
  interactive: boolean
): Promise<HarnessId[]> {
  if (fromOptions && fromOptions.length > 0) return fromOptions;
  if (fromConfig && fromConfig.length > 0) return fromConfig;
  const detected = await detectHarnesses(projectRoot);
  if (interactive && isInteractive()) {
    return runPicker({ detected });
  }
  if (detected.length > 0) return detected;
  throw new Error(NO_HARNESS_DETECTED_MESSAGE);
}

export async function syncCclaw(options: SyncOptions): Promise<SyncResult> {
  const projectRoot = options.cwd;
  const emit = (step: string, detail?: string): void => {
    options.onProgress?.({ step, detail });
  };

  await ensureRuntimeRoot(projectRoot);
  const existing = await readConfig(projectRoot);
  const harnesses = await resolveHarnesses(
    projectRoot,
    options.harnesses,
    existing?.harnesses,
    options.interactive ?? false
  );
  for (const harness of harnesses) {
    if (!HARNESS_IDS.includes(harness)) {
      throw new Error(`Unknown harness: ${harness}. Supported: ${HARNESS_IDS.join(", ")}`);
    }
  }
  const config = existing
    ? { ...existing, version: CCLAW_VERSION, flowVersion: "8" as const, harnesses }
    : createDefaultConfig(harnesses);
  await ensureRunSystem(projectRoot);
  emit("Runtime root", `.cclaw/{state,hooks,flows,lib}`);

  await writeAgentFiles(projectRoot);
  emit("Wrote specialists", `${CORE_AGENTS.length} agents → .cclaw/lib/agents/`);

  for (const hook of NODE_HOOKS) {
    await writeHookFile(projectRoot, hook);
  }
  emit("Wrote hooks", `${NODE_HOOKS.length} hooks → .cclaw/hooks/`);

  await writeRuntimeSkills(projectRoot);
  await writeMetaSkill(projectRoot);
  emit("Wrote skills", `${AUTO_TRIGGER_SKILLS.length + 1} skills → .cclaw/lib/skills/`);

  await writeTemplates(projectRoot);
  emit("Wrote templates", `${ARTIFACT_TEMPLATES.length + 1} templates → .cclaw/lib/templates/`);

  await writeStageRunbooks(projectRoot);
  emit("Wrote runbooks", `${STAGE_PLAYBOOKS.length} stage runbooks → .cclaw/lib/runbooks/`);

  await writeReferencePatterns(projectRoot);
  emit("Wrote patterns", `${REFERENCE_PATTERNS.length} reference patterns → .cclaw/lib/patterns/`);

  await writeResearchPlaybooks(projectRoot);
  if (RESEARCH_PLAYBOOKS.length > 0) {
    emit("Wrote research", `${RESEARCH_PLAYBOOKS.length} research playbooks → .cclaw/lib/research/`);
  }

  await writeRecoveryPlaybooks(projectRoot);
  if (RECOVERY_PLAYBOOKS.length > 0) {
    emit("Wrote recovery", `${RECOVERY_PLAYBOOKS.length} recovery playbooks → .cclaw/lib/recovery/`);
  }

  await writeExamples(projectRoot);
  if (EXAMPLES.length > 0) {
    emit("Wrote examples", `${EXAMPLES.length} worked examples → .cclaw/lib/examples/`);
  }

  await writeAntipatterns(projectRoot);
  await writeDecisionProtocol(projectRoot);
  await writeIdeasSeed(projectRoot);
  emit("Wrote anti-patterns + decision protocol", "antipatterns.md + decision-protocol.md");

  for (const harness of harnesses) {
    await writeHarnessAssets(projectRoot, HARNESS_LAYOUTS[harness]);
  }
  emit(
    "Wired harnesses",
    `${harnesses.join(", ")} → commands · agents · skills${harnesses.some((h) => HARNESS_LAYOUTS[h].hooksConfig) ? " · hooks" : ""}`
  );

  await ensureGitignorePatterns(projectRoot);
  const configPath = await writeConfig(projectRoot, config);
  emit("Wrote .cclaw/config.yaml", `harnesses: ${harnesses.join(", ")}`);

  const counts: SummaryCounts = {
    harnesses: [...harnesses],
    agents: CORE_AGENTS.length,
    skills: AUTO_TRIGGER_SKILLS.length + 1,
    templates: ARTIFACT_TEMPLATES.length + 1,
    runbooks: STAGE_PLAYBOOKS.length,
    patterns: REFERENCE_PATTERNS.length,
    research: RESEARCH_PLAYBOOKS.length,
    recovery: RECOVERY_PLAYBOOKS.length,
    examples: EXAMPLES.length,
    hooks: NODE_HOOKS.length,
    commands: 3
  };
  return { installedHarnesses: harnesses, configPath, counts };
}

export async function initCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

export async function uninstallCclaw(options: { cwd: string }): Promise<void> {
  const projectRoot = options.cwd;
  const config = await readConfig(projectRoot);
  const harnesses = config?.harnesses ?? (HARNESS_IDS as readonly HarnessId[]);
  await removePath(path.join(projectRoot, RUNTIME_ROOT));
  for (const harness of harnesses as HarnessId[]) {
    const layout = HARNESS_LAYOUTS[harness];
    for (const filename of ["cc.md", "cc-cancel.md", "cc-idea.md"]) {
      await removePath(path.join(projectRoot, layout.commandsDir, filename));
    }
    for (const agent of CORE_AGENTS) {
      await removePath(path.join(projectRoot, layout.agentsDir, `${agent.id}.md`));
    }
    await removePath(path.join(projectRoot, layout.skillsDir));
    if (layout.hooksConfig) {
      await removePath(path.join(projectRoot, layout.hooksConfig.dir, layout.hooksConfig.fileName));
    }
    if (await exists(path.join(projectRoot, layout.commandsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.commandsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.commandsDir));
    }
    if (await exists(path.join(projectRoot, layout.agentsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.agentsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.agentsDir));
    }
  }
  await removeGitignorePatterns(projectRoot);
}

export async function upgradeCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

export function planSeedForSlug(slug: string): string {
  return planTemplateForSlug(slug);
}

export const HARNESS_LAYOUT_TABLE = HARNESS_LAYOUTS;
export type { NodeHookSpec };
export const COMMIT_HELPER_HOOK = COMMIT_HELPER_HOOK_SPEC;
