import fs from "node:fs/promises";
import path from "node:path";
import { CCLAW_VERSION, RUNTIME_ROOT } from "./constants.js";
import { ACTIVE_ARTIFACT_DIRS, type ArtifactStage } from "./artifact-paths.js";
import { CORE_AGENTS, renderAgentMarkdown } from "./content/core-agents.js";
import { COMMIT_HELPER_HOOK_SPEC, NODE_HOOKS, SESSION_START_HOOK_SPEC, STOP_HANDOFF_HOOK_SPEC, type NodeHookSpec } from "./content/node-hooks.js";
import { renderStartCommand } from "./content/start-command.js";
import { renderCancelCommand } from "./content/cancel-command.js";
import { renderIdeaCommand } from "./content/idea-command.js";
import { ensureDir, exists, writeFileSafe, removePath } from "./fs-utils.js";
import { ensureRunSystem } from "./run-persistence.js";
import { createDefaultConfig, readConfig, renderConfig, type CclawConfig } from "./config.js";
import { HARNESS_IDS, type HarnessId } from "./types.js";
import { ironLawsMarkdown } from "./content/iron-laws.js";

export interface HarnessLayout {
  id: HarnessId;
  commandsDir: string;
  agentsDir: string;
  hooksConfig: { dir: string; fileName: string } | null;
}

const HARNESS_LAYOUTS: Record<HarnessId, HarnessLayout> = {
  claude: {
    id: "claude",
    commandsDir: ".claude/commands",
    agentsDir: ".claude/agents",
    hooksConfig: { dir: ".claude/hooks", fileName: "hooks.json" }
  },
  cursor: {
    id: "cursor",
    commandsDir: ".cursor/commands",
    agentsDir: ".cursor/agents",
    hooksConfig: { dir: ".cursor", fileName: "hooks.json" }
  },
  opencode: {
    id: "opencode",
    commandsDir: ".opencode/commands",
    agentsDir: ".opencode/agents",
    hooksConfig: { dir: ".opencode/plugins", fileName: "cclaw-plugin.mjs" }
  },
  codex: {
    id: "codex",
    commandsDir: ".codex/commands",
    agentsDir: ".codex/agents",
    hooksConfig: { dir: ".codex", fileName: "hooks.json" }
  }
};

export interface SyncOptions {
  cwd: string;
  harnesses?: HarnessId[];
}

export interface SyncResult {
  installedHarnesses: HarnessId[];
  configPath: string;
}

const PLAN_TEMPLATE_BODY = `_Replace this paragraph with one or two sentences explaining what we are doing and why._\n\n## Context\n\n_(brainstormer fills this when invoked.)_\n\n## Acceptance Criteria\n\n- AC-1: _Describe a single observable outcome that closes one commit._\n\n## Plan\n\n- Step 1.\n\n## Traceability\n\n- AC-1 → commit pending\n`;

function planTemplate(slug: string): string {
  return `---\nslug: ${slug}\nstage: plan\nstatus: active\nac:\n  - id: AC-1\n    text: \"Replace with the first observable outcome.\"\n    status: pending\nlast_specialist: null\nrefines: null\nshipped_at: null\nship_commit: null\nreview_iterations: 0\nsecurity_flag: false\n---\n\n# ${slug}\n\n${PLAN_TEMPLATE_BODY}`;
}

export async function ensureRuntimeRoot(projectRoot: string): Promise<void> {
  const root = path.join(projectRoot, RUNTIME_ROOT);
  for (const dir of [
    "state",
    ...Object.values(ACTIVE_ARTIFACT_DIRS),
    "shipped",
    "agents",
    "hooks",
    "templates"
  ]) {
    await ensureDir(path.join(root, dir));
  }
  await writeFileSafe(
    path.join(root, ".gitkeep"),
    "cclaw v8 runtime root. Generated by cclaw-cli; safe to keep in version control.\n"
  );
}

async function writeHookFile(projectRoot: string, hook: NodeHookSpec): Promise<void> {
  const hookPath = path.join(projectRoot, RUNTIME_ROOT, "hooks", hook.fileName);
  await writeFileSafe(hookPath, hook.body);
  await fs.chmod(hookPath, 0o755);
}

async function writeAgentFiles(projectRoot: string): Promise<void> {
  for (const agent of CORE_AGENTS) {
    const agentPath = path.join(projectRoot, RUNTIME_ROOT, "agents", `${agent.id}.md`);
    await writeFileSafe(agentPath, renderAgentMarkdown(agent));
  }
}

async function writeTemplates(projectRoot: string): Promise<void> {
  await writeFileSafe(
    path.join(projectRoot, RUNTIME_ROOT, "templates", "plan.md"),
    planTemplate("EXAMPLE-SLUG")
  );
  await writeFileSafe(
    path.join(projectRoot, RUNTIME_ROOT, "templates", "iron-laws.md"),
    ironLawsMarkdown()
  );
}

async function writeHarnessAssets(projectRoot: string, layout: HarnessLayout): Promise<void> {
  await ensureDir(path.join(projectRoot, layout.commandsDir));
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc.md"), renderStartCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-cancel.md"), renderCancelCommand());
  await writeFileSafe(path.join(projectRoot, layout.commandsDir, "cc-idea.md"), renderIdeaCommand());

  await ensureDir(path.join(projectRoot, layout.agentsDir));
  for (const agent of CORE_AGENTS) {
    await writeFileSafe(
      path.join(projectRoot, layout.agentsDir, `${agent.id}.md`),
      renderAgentMarkdown(agent)
    );
  }

  if (layout.hooksConfig) {
    const { dir, fileName } = layout.hooksConfig;
    await ensureDir(path.join(projectRoot, dir));
    if (fileName.endsWith(".mjs")) {
      const moduleBody = `// cclaw v${CCLAW_VERSION} opencode plugin (minimal). Wires session-start and stop-handoff hooks.\nimport { spawn } from \"node:child_process\";\nimport path from \"node:path\";\nfunction run(filePath) {\n  return () => spawn(process.execPath, [path.join(\".cclaw\", \"hooks\", filePath)], { stdio: \"inherit\" });\n}\nexport default {\n  events: {\n    \"session.start\": run(\"session-start.mjs\"),\n    \"session.stop\": run(\"stop-handoff.mjs\")\n  }\n};\n`;
      await writeFileSafe(path.join(projectRoot, dir, fileName), moduleBody);
    } else {
      const hooksJson = {
        version: 1,
        generatedBy: `cclaw-cli@${CCLAW_VERSION}`,
        events: {
          "session.start": [
            { command: "node", args: [`./${RUNTIME_ROOT}/hooks/${SESSION_START_HOOK_SPEC.fileName}`] }
          ],
          "session.stop": [
            { command: "node", args: [`./${RUNTIME_ROOT}/hooks/${STOP_HANDOFF_HOOK_SPEC.fileName}`] }
          ]
        }
      };
      await writeFileSafe(path.join(projectRoot, dir, fileName), `${JSON.stringify(hooksJson, null, 2)}\n`);
    }
  }
}

async function writeConfig(projectRoot: string, config: CclawConfig): Promise<string> {
  const configPath = path.join(projectRoot, RUNTIME_ROOT, "config.yaml");
  await writeFileSafe(configPath, renderConfig(config));
  return configPath;
}

export async function syncCclaw(options: SyncOptions): Promise<SyncResult> {
  const projectRoot = options.cwd;
  await ensureRuntimeRoot(projectRoot);
  const existing = await readConfig(projectRoot);
  const harnesses = options.harnesses ?? existing?.harnesses ?? ["cursor"];
  for (const harness of harnesses) {
    if (!HARNESS_IDS.includes(harness)) {
      throw new Error(`Unknown harness: ${harness}. Supported: ${HARNESS_IDS.join(", ")}`);
    }
  }
  const config = existing ? { ...existing, version: CCLAW_VERSION, flowVersion: "8" as const, harnesses } : createDefaultConfig(harnesses);
  await ensureRunSystem(projectRoot);
  await writeAgentFiles(projectRoot);
  for (const hook of NODE_HOOKS) {
    await writeHookFile(projectRoot, hook);
  }
  await writeTemplates(projectRoot);
  for (const harness of harnesses) {
    await writeHarnessAssets(projectRoot, HARNESS_LAYOUTS[harness]);
  }
  const configPath = await writeConfig(projectRoot, config);
  return { installedHarnesses: harnesses, configPath };
}

export async function initCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

export async function uninstallCclaw(options: { cwd: string }): Promise<void> {
  const projectRoot = options.cwd;
  const config = await readConfig(projectRoot);
  const harnesses = config?.harnesses ?? (HARNESS_IDS as readonly HarnessId[]);
  await removePath(path.join(projectRoot, RUNTIME_ROOT));
  for (const harness of harnesses as HarnessId[]) {
    const layout = HARNESS_LAYOUTS[harness];
    for (const filename of ["cc.md", "cc-cancel.md", "cc-idea.md"]) {
      await removePath(path.join(projectRoot, layout.commandsDir, filename));
    }
    for (const agent of CORE_AGENTS) {
      await removePath(path.join(projectRoot, layout.agentsDir, `${agent.id}.md`));
    }
    if (layout.hooksConfig) {
      await removePath(path.join(projectRoot, layout.hooksConfig.dir, layout.hooksConfig.fileName));
    }
    if (await exists(path.join(projectRoot, layout.commandsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.commandsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.commandsDir));
    }
    if (await exists(path.join(projectRoot, layout.agentsDir))) {
      const remaining = await fs.readdir(path.join(projectRoot, layout.agentsDir));
      if (remaining.length === 0) await removePath(path.join(projectRoot, layout.agentsDir));
    }
  }
}

export async function upgradeCclaw(options: SyncOptions): Promise<SyncResult> {
  return syncCclaw(options);
}

export const HARNESS_LAYOUT_TABLE = HARNESS_LAYOUTS;
export type { NodeHookSpec };
export const COMMIT_HELPER_HOOK = COMMIT_HELPER_HOOK_SPEC;
